### ISSUE TITLE
[question] How to order top-level sections?

### ISSUE THREAD

**Issue by swese44** [storybooks/storybook#6327] opened 2019-03-28 00:12 UTC
We've just upgraded to latest version `5.0.5`. I'm organizing stories into sections with the `|` character in `storiesOf()`:
<img width="200" alt="Screen Shot 2019-03-27 at 5 07 03 PM" src="https://user-images.githubusercontent.com/471731/55120332-c9b51780-50b2-11e9-926b-a536abdeeaad.png">

But the sections seem to be organized randomly. How can I declare the sections order? Thanks

**Comment by shilman** [comment] 2019-03-28 02:00
I'm not sure it's possible. Related https://github.com/storybooks/storybook/issues/5827

**Comment by backbone87** [comment] 2019-03-29 02:10
we maybe could do this via parameters:
```js
addParameters({
  categoryOrder: ['Category A', 'Also a category'],
});
```

**Comment by swese44** [comment] 2019-03-29 02:17
array version would allow manual order so i'd be in favor of that approach.

for now i'm making sure the individual story files are imported in the section order i want, it works but isn't really scalable

**Comment by kevinSuttle** [comment] 2019-04-03 20:08
The demo here seems to be _mostly_ alphabetical. https://storybooks-official.netlify.com/

Anyone know where the source for the storybook-react demo is?

**Comment by shilman** [comment] 2019-04-04 14:47
@kevinSuttle All of our netlify deploys are in the repo in the `/examples/*` directories

**Comment by kevinSuttle** [comment] 2019-04-04 14:56
Thanks!

**Comment by shilman** [comment] 2019-04-06 01:27
Closing this as a dupe to #3730

**Closed by shilman** 2019-04-06 01:27 UTC
Labels: question / support, ui

**Comment by dcts** [comment] 2020-04-12 22:40
not sure if that is helpful to anyone but I had the same issue and solved it by simply changing the filenames of my `*.stories.mdx` files such that the components belonging to the section I wanted to be on top were alphabetically lower. So that they look like this:
```
1_atom_MyBttn.stories.mdx
1_atom_MyInput.stories.mdx
2_molecule_MyForm.stories.mdx
```

My setup is: I have a folder `stories` with all my `*.stories.mdx` files and inside `.storybook/main.js` i have added the following line to import these:
```js
stories: ['../stories/*.stories.{js,mdx}'],
```
Then inside my `*.stories.jsx` files I specify the section (in my case I have 3 sections: **atoms**, **molecules** and **ogranisms**) with the pipe character `|` like that:
```mdx
<Meta title="Atoms|my-button" parameters={{component: "my-button"}} />
```

I found it hard to find any documentation on this so i just share it here :)

**Comment by natearmagost** [comment] 2020-04-13 22:11
In the same boat as everyone else, just sharing because it was such a headache.
```
// In the stories...
// export default {
//   title: 'Components|Accordion',
//   component: Accordion,
// };
// export default {
//   title: 'Getting Started|Welcome',
// };


// In config.js
// The order for the headers
const headers = [
  'Getting Started',
  'Components',
  'Forms',
  'Page Examples',
];

const storySort = (a, b) => {
  // a[1].kind is something like: Components|Accordion. Using "Components" for the headers array.
  // Using Components from ^^^
  const aHeader = a[1].kind.substr(0, a[1].kind.indexOf('|'));
  const bHeader = b[1].kind.substr(0, b[1].kind.indexOf('|'));

  if (aHeader !== bHeader) {
    // Comparing something like "components-accordion--main" to "getting-started-app--main".
    const aHeaderIndex = headers.findIndex(h => h === aHeader);
    const bHeaderIndex = headers.findIndex(h => h === bHeader);
    return aHeaderIndex - bHeaderIndex;
  }

  return 0;
  /* Or instead of `return 0` compare something like "components-accordion--small" to "components-accordion--large"
   * and sort the stories inside each component...
   */
  // return a[1].id.localeCompare(b[1].id, undefined, { numeric: true });
};

addParameters({
  options: {
    storySort,
  },
});
```

**Comment by airtonix** [comment] 2020-07-28 09:04
There's a much simpler way: 

https://www.npmjs.com/package/anysort

```js
import anysort from 'anysort'
import { addParameters } from '@storybook/react'

addParameters({
  options: {
    /**
     * display the top-level grouping as a "root" in the sidebar
     * @type {Boolean}
     */
    showRoots: true,
    storySort: (previous, next) => {
      const [previousStory, previousMeta] = previous
      const [nextStory, nextMeta] = next

      return anysort(previousMeta.kind, nextMeta.kind, [
        'Overview/Introduction',
        'Overview/Getting Started',
        'Overview/Themes',
        'Overview/**',
        'Usage/**',
        'Views/**',
        'Layout/**',
        'Components/**',
        'Fields/**',
        'Widgets/**',
      ])
    }
  },
})

```

**Comment by SBoudrias** [comment] 2020-09-10 00:37
If you fall here from Google, there's now an easier interface to sort your stories: https://github.com/storybookjs/storybook/blob/f3a9117937205f88d8da0264b59942edcfe29cb6/docs/writing-stories/naming-components-and-hierarchy.md

**Comment by NishargShah** [comment] 2021-01-22 22:16
You can do it like that

**BEFORE**

![image](https://user-images.githubusercontent.com/35843261/105554509-84ed7c80-5d2d-11eb-9d04-70591634a7af.png)

**AFTER**

> .storybook/preview.js
```
export const parameters = {
  .........,
  options: {
    storySort: {
      order: ['Examples', ['Simple', 'Responsive Map', 'Area', 'Colors', 'Dynamic']],
    },
  },
};
```

![image](https://user-images.githubusercontent.com/35843261/105554486-74d59d00-5d2d-11eb-84d5-91611df5a815.png)

**Comment by rwieruch** [comment] 2022-02-23 23:12
> 

Perhaps related: https://github.com/storybookjs/storybook/issues/10086#issuecomment-1049299721 because I cannot reproduce what @NishargShah demonstrated here :(

**Comment by KatWorkGit** [comment] 2023-11-30 13:47
> Perhaps related: [#10086 (comment)](https://github.com/storybookjs/storybook/issues/10086#issuecomment-1049299721) because I cannot reproduce what @NishargShah demonstrated here :(

@rwieruch I did find this while stumbling on a similar issue to what you are facing:
https://github.com/storybookjs/storybook/issues/10086#issuecomment-624140690
Maybe it is related?

I am using Storybook `7.5.1` because I also cannot seem to reproduce what @NishargShah and the docs ([here](https://storybook.js.org/docs/writing-stories/naming-components-and-hierarchy#sorting-stories)) say about story sorting via arrays.

**Comment by notacouch** [comment] 2024-03-22 19:23
In Storybook 8, HTML + Vite framework, for the life of me I cannot get sorting to work at all.

I have tried the order array. I have tried the `anysort` solutions above but that is no longer feasible:

> "storySort must be a self-contained function that does not reference external variables."
- source: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#v7-style-story-sort

(The above should really be mentioned in the docs itself: https://storybook.js.org/docs/api/parameters#optionsstorysort)

I have tried this:

```js
      storySort: (previous, next) => {
        // .title returns the title as seen in Meta tag, e.g. Design/Colors
        console.log('previous: ', previous.title, 'next: ', next.title);
        const storyOrder = [
          'Design/Typography',
          'Design/Colors',
          'Design/Grid',
        ];
        const previousPosition = storyOrder.indexOf(previous.title);
        const nextPosition = storyOrder.indexOf(next.title);
        console.log('previous position? ', previousPosition, ' nextPosition? ', nextPosition);
        return nextPosition > -1 ? nextPosition : storyOrder.length + 1;
      },
```

It runs, but the return doesn't seem to matter.

Everything sorts alphabetically unfortunately.
