### ISSUE TITLE
Vue: HMR doesnt rerender story

### ISSUE THREAD

**Issue by casio** [storybooks/storybook#3205] opened 2018-03-14 13:55 UTC
Changing the source of both a story or a component will cause HMR to update the bundle accordingly, but the selected story will not be re-rendered, thus, not reflect the change.

To see the latest change you have to actually reload the whole page.

### Steps to reproduce

- setup a vanilla vue project using eg `vue-cli create # or init`
- add storybook using `getstorybook` (tried both stable & master)
- start & open the book
- change eg the Button story in `./src/stories/index.js` to have the button label read `Bye Button`
- in the browser, you'll see the module being re-bundled & updated in the console, but the actual story panel still render `Hello Button`

fyi when changing the story collection name, though(eg `Welcome` > `Good bye`), the change will be reflected w/o reloading

**Comment by tdkn** [comment] 2018-03-15 12:33
I ran into the same issue 🤔

**Comment by lgraziani2712** [comment] 2018-04-11 22:46
Bug still active in `"@storybook/vue": "^3.4.1"`

**Comment by Aaron-Pool** [comment] 2018-04-27 15:31
I'm also running into this issue.

**Comment by wagerfield** [comment] 2018-05-31 09:44
This is still an issue for me

**Comment by germanrcuriel** [comment] 2018-06-19 12:03
Still an issue for me too. CSS reloading works just fine but HMR doesn't.

**Comment by forforeach** [comment] 2018-07-12 08:09
I'm also experiencing the same issue with `"@storybook/vue": "^3.4.8"`

**Comment by igor-dv** [comment] 2018-08-05 16:12
I've tried to reproduce this with our example in the monorepo (@storybook/vue@alpha, webpack@4, vue@2.5.17, vue-loader@15.2.4 ) and HMR worked fine for me. 
I can assume that it's somehow related to the dependencies mismatch. Can anyone publish the reproduction repo?

**Comment by casio** [comment] 2018-08-26 17:32
Just did a test using `v4.0.0-alpha.18` and a vanilla project created with `vue-cli`.
Nice, HMR working fine there. So, unless someone needs this issue to be open until the v4 release we can close it?

**Comment by igor-dv** [comment] 2018-08-26 18:05
I am closing since it works in alpha

**Closed by igor-dv** 2018-08-26 18:05 UTC
Labels: app: vue, bug
