### ISSUE TITLE
Cannot read property 'decelerationRate' of undefined

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#889] opened 2017-04-15 17:39 UTC
<a href="https://github.com/xareelee"><img src="https://avatars2.githubusercontent.com/u/804308?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [xareelee](https://github.com/xareelee)**
_Thursday Mar 16, 2017 at 09:26 GMT_
_Originally opened as https://github.com/storybooks/storyshots/issues/86_

----

When I use jest/storyshots to run the snapshot tests. It shows an abnormal error (`TypeError: Cannot read property 'decelerationRate' of undefined `):

```
 FAIL  storybook/Storyshots.test.js
  ● Storyshots › [Page] CountryPolicy › entry

    TypeError: Cannot read property 'decelerationRate' of undefined
      
      at Object.<anonymous> (node_modules/react-native/Libraries/Components/WebView/WebView.ios.js:555:3254)
      at Object.get WebView [as WebView] (node_modules/react-native/Libraries/react-native/react-native.js:68:22)
      at CountryPolicy (src/ui/CountryPolicy/CountryPolicy.js:11:43)
      at node_modules/react-test-renderer/lib/ReactCompositeComponent.js:306:16
      at measureLifeCyclePerf (node_modules/react-test-renderer/lib/ReactCompositeComponent.js:75:12)
      at ReactCompositeComponentWrapper._constructComponentWithoutOwner (node_modules/react-test-renderer/lib/ReactCompositeComponent.js:305:14)
      at ReactCompositeComponentWrapper._constructComponent (node_modules/react-test-renderer/lib/ReactCompositeComponent.js:280:21)
```

Source code:

```js
// CountryPolicy.jsx
const CountryPolicy = () => (
  <WebView
    style={styles.wrapper}
    source={{ uri: policyUrl }}
  />
) 
```

Story:

```jsx
// CountryPolicy.stories.js
storiesOf('[Page] CountryPolicy', module)
  .add('entry', () => (
    <CountryPolicy />
  ));
```

The app displays normally. It seems something wrong when testing a DOM containing a `WebView`.

**Comment by shilman** [comment] 2017-04-15 17:39
<a href="https://github.com/jrdrg"><img src="https://avatars0.githubusercontent.com/u/11744407?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [jrdrg](https://github.com/jrdrg)**
_Friday Mar 17, 2017 at 12:45 GMT_

----

Possibly the same issue referenced in https://github.com/storybooks/storyshots/pull/76?

**Comment by tmeasday** [comment] 2017-05-15 05:08
@xareelee -  did you have any luck with this one? It sounds like an issue with React Native's implementation of the `<WebView/>` component which is still unresolved: https://github.com/facebook/react-native/issues/12440.

Is there anything we can do to avoid the problem? It sounds like the issue is with refs *inside* the `WebView` so I don't think the issue @shilman mentioned above will help (although I'm not sure).

I'll close this for now, but @-me or comment on this issue if there is something we could do to work around it.

**Closed by tmeasday** 2017-05-15 05:08 UTC
Labels: bug, storyshots

**Comment by xareelee** [comment] 2017-05-17 02:47
@tmeasday 

Currently, I fixed this by adding `jest.unmock('ScrollView')` in the `.fest_config.js` which is mentioned on https://github.com/facebook/react-native/issues/12440#issuecomment-282184173.

It seems that React Native team should fix the issue.

**Comment by tmeasday** [comment] 2017-05-17 20:08
@xareelee OK, thanks for posting that, hopefully it will help anyone else who runs into this problem!
