### ISSUE TITLE
Plugin/Preset files are not allowed to export objects, only functions

### ISSUE THREAD

**Issue by krini** [storybooks/storybook#5249] opened 2019-01-15 08:33 UTC
**Describe the bug**
I'm trying to run the storybook together with expo. But when I try to start storybook on web I get this error:

`ERROR in ./storybook/addons.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Plugin/Preset files are not allowed to export objects, only functions. In /Users/kristoffernielsen/repos/app/storybook/node_modules/babel-preset-react/lib/index.js`

**To Reproduce**
1. yarn storybook

**Expected behavior**
Storybook will start.

**System:**
 - OS: MacOS
 - Framework: [react
 - Addons: addon-actions, addon-links, addon-knobs - but it fails even though I remove them from addons.js

**package.json**
  "dependencies": {
    "expo": "^32.0.0",
    "react": "16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz"
  },
  "devDependencies": {
    "@storybook/addon-actions": "^4.1.6",
    "@storybook/addon-knobs": "^4.1.6",
    "@storybook/addon-links": "^4.1.6",
    "@storybook/addon-ondevice-knobs": "^4.1.6",
    "@storybook/addon-ondevice-notes": "^4.1.6",
    "@storybook/addons": "^4.1.6",
    "@storybook/react-native": "^4.1.6",
    "babel-core": "^6.26.3",
    "babel-preset-expo": "^5.0.0",
    "babel-runtime": "^6.26.0",
    "prop-types": "^15.6.2",
    "react-dom": "16.5.0"
  },

**babel.config.js**
module.exports = function(api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
  };
};

**Additional context**

**Comment by jwrlee88** [comment] 2019-01-18 20:33
I have the exact same setup and running into the same issue. 

My steps to come to this error were:

1) expo init 
2) npx -p @storybook/cli sb init 
3) npm run storybook

**Comment by fr-aaron** [comment] 2019-01-20 12:06
I am having this same issue and not able to resolve :(

 "dependencies": {
    "@expo/samples": "2.1.1",
    "apsl-react-native-button": "^3.1.1",
    "babel-loader": "8",
    "enzyme": "^3.8.0",
    "enzyme-adapter-react-16": "^1.7.1",
    "expo": "^32.0.0",
    "react": "16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",
    "react-navigation": "^3.0.9"
  },
  "devDependencies": {
    "@storybook/addon-actions": "^4.1.7",
    "@storybook/addon-links": "^4.1.7",
    "@storybook/addons": "^4.1.7",
    "@storybook/react-native": "^4.1.7",
    "babel-core": "7.0.0-bridge.0",
    "babel-eslint": "^10.0.1",
    "babel-preset-expo": "^5.0.0",
    "babel-runtime": "^6.26.0",
    "eslint": "^5.12.1",
    "eslint-config-airbnb": "^17.1.0",
    "eslint-config-prettier": "^3.5.0",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-jsx-a11y": "^6.1.2",
    "eslint-plugin-prettier": "^3.0.1",
    "eslint-plugin-react": "^7.12.4",
    "eslint-plugin-react-native": "^3.6.0",
    "jest-expo": "^32.0.0",
    "prop-types": "^15.6.2",
    "react-dom": "^16.7.0"
  }


module.exports = function(api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
    use: 'babel-loader',
  };
};

**Comment by shilman** [comment] 2019-01-20 14:53
I believe this is a babel 6/7 version mismatch issue, duplicate of #4011. It's being addressed in #4942, which is slated to go out in Storybook v5, hopefully ready to test in a few weeks. Will post here as soon as it's ready!

**Comment by shilman** [comment] 2019-03-12 21:01
FYI the RN changes got delayed.

SB5 launched last week without RN: https://medium.com/storybookjs/storybook-5-0-db1d0f9c83b8

We'll try to release an updated RN on `5.1-alpha` in the coming two weeks.

**Comment by Aleksion** [comment] 2019-03-15 17:55
@shilman so @storybook 5 doesn't work with react native right now?

**Comment by shilman** [comment] 2019-03-15 21:45
@Aleksion we just got it merged, so the next version of 5.1-alpha should contain it

**Comment by shilman** [comment] 2019-03-16 07:26
Gadzooks!! I just released https://github.com/storybooks/storybook/releases/tag/v5.1.0-alpha.7 containing PR #4942 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Closed by shilman** 2019-03-16 07:26 UTC
Labels: app: react-native, babel / webpack, compatibility with other tools

**Comment by andyford** [comment] 2019-03-28 15:36
I ran into this problem when we bumped babel-loader from 7.1.5 up to 8.0.5. Rolling babel-loader back to 7.1.5 worked in our situation. (your mileage may vary)

**Comment by minardimedia** [comment] 2019-07-02 19:23
I also have this issue I just change the babel-loader from 8.0.6 to 7.1.5 and it worked

**Comment by codesinghanoop** [comment] 2019-11-27 21:52
If someone is still facing this issue then please upgrade your babel-core version to latest. `npm install babel-core@latest`
