### ISSUE TITLE
@storybook/addon-knobs/react color picker hide behind

### ISSUE THREAD

**Issue by khaki4** [storybooks/storybook#4951] opened 2018-12-07 15:37 UTC
**Describe the bug**
when click color picker by @storybook/addon-knobs/react color.
The color picker is cut off and can not be seen.

when i edit css to
.css-8a9ncn {
    overflow: visible;
...
}
the issue has solved.

**Expected behavior**
show entire color picker.

**Screenshots**
<img width="992" alt="screen shot 2018-12-08 at 12 28 01 am" src="https://user-images.githubusercontent.com/8818375/49656366-8772b680-fa80-11e8-9fba-2efb01cf857a.png">

**Code snippets**
{
  "devDependencies": {
    "@babel/core": "7.2.0",
    "@storybook/addon-info": "^4.0.12",
    "@storybook/addon-knobs": "4.0.12",
    "@storybook/addons": "4.0.12",
    "@storybook/react": "4.0.12",
    "babel-core": "6.26.3",
    "babel-loader": "8.0.4",
    "storybook-addon-jsx": "6.0.0"
  },
  "dependencies": {
    "react": "^16.6.3",
    "react-dom": "^16.6.3"
  }
}

import { color } from '@storybook/addon-knobs/react';
**System:**
 - OS: MacOS
 - Browser: chrome
 - Framework: react
 - Addons: @storybook/addon-knobs/react
 - Version: 4.0.12

**Comment by maacky** [comment] 2018-12-08 18:55
This is related to #4694.

**Comment by maacky** [comment] 2018-12-08 18:55
Except for OS, this is duplicate of #4694.

**Comment by igor-dv** [comment] 2018-12-08 21:41
Do you want to take it?

**Comment by igor-dv** [comment] 2018-12-08 22:37
Cool! 
Closing it as a duplicate.

**Closed by igor-dv** 2018-12-08 22:37 UTC
Labels: addon: knobs, good first issue
