### ISSUE TITLE
@storybook/vue 4.0.0-alpha.18 addon-knobs: knob 'color' throw error

### ISSUE THREAD

**Issue by Eelsie** [storybooks/storybook#4093] opened 2018-08-29 12:22 UTC
### Bug or support request summary
With @storybook/vue 4.0.0-alpha.18 addon-knobs. knob "color" throw error: "Cannot read property 'contains' of undefined".
![screen shot 2018-08-29 at 15 18 36](https://user-images.githubusercontent.com/11568278/44787121-ecc02d00-ab9e-11e8-9f24-1909f11d8329.png)

### Steps to reproduce

I'm importing the knob like this:
`import {color} from '@storybook/addon-knobs/vue'`

and using it like this:
`const textColor = color('Text color', '#000000')`

It has been working in storybook 3.

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/vue 4.0.0-alpha.18
- @storybook/addon-knobs 4.0.0-alpha.18

**Comment by Primigenus** [comment] 2018-08-29 17:08
Was able to reproduce in official react storybook as well: https://storybooks-official.netlify.com/?selectedKind=Addons%7CKnobs.withKnobs&selectedStory=tweaks%20static%20values&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs

**Comment by anthon** [comment] 2018-09-20 14:51
+1 using @storybook/react@4.0.0-alpha.22 and @storybook/addon-knobs@4.0.0-alpha.22

```
import { color } from '@storybook/addon-knobs/react'

...color('label', 'green')...
```

Seems to be an issue with `this.popover` never being set.

**Comment by IanVS** [comment] 2018-10-05 16:04
Seems to be fixed on or before `alpha.24`, it's working now.  I think this issue can be closed.

**Comment by igor-dv** [comment] 2018-10-07 10:42
yep, fixed in alpha.24

**Closed by igor-dv** 2018-10-07 10:42 UTC
Labels: addon: knobs, bug
