### ISSUE TITLE
Generic styles overriding storybook UI styles

### ISSUE THREAD

**Issue by timoxley** [storybooks/storybook#693] opened 2017-02-14 03:33 UTC
The storybook UI gets somewhat trashed by my application's styles e.g. for `a`, `button`, `li`, etc.

I'm using webpack + postcss with style & css loaders.  It seems even if I only `import` the generic styles in the story itself, they still get loaded into the storybook container rather than only in the story's iframe. Decorator also not helpful here.

Any ideas on how I can apply generic styles to only my app, without affecting the storybook UI?

**Comment by timoxley** [comment] 2017-02-14 04:50
Found a workaround which may be acceptable.

* Automatically prefix my selectors using [postcss-prefix-selector](https://github.com/RadValentin/postcss-prefix-selector) (excluding html/body rules)
* Add a prefix to root element rendered with ReactDOM.render
* Wrap storybook rendered components in a `<div className='myPrefix'>` using `addDecorator` e.g.:

```js
// .storybook/config.js
addDecorator(story => <div className='myPrefix'>{story()}</div>)
```

**Comment by ndelangen** [comment] 2017-03-28 22:13
Thanks for posting your found solution!

What sort of styling overrides are you trying to do?

**Comment by timoxley** [comment] 2017-03-29 03:43
> What sort of styling overrides are you trying to do?

None. The problem is I don't want any of my application styles to affect the storybook interface, yet they do.

**Comment by ndelangen** [comment] 2017-03-29 04:45
Ah, sounds like a bug, thanks!

**Comment by ndelangen** [comment] 2017-07-07 13:19
Can you share your config?

**Comment by timoxley** [comment] 2017-07-07 17:18
@ndelangen i have mostly stopped using storybook these days, but having non-namespaced element styles in your app will cause this problem e.g. styles for headings, anchors or buttons.

**Comment by ndelangen** [comment] 2017-07-07 23:36
That's sad to hear, what setup have you migrated to?

**Comment by danielduan** [comment] 2017-08-27 20:51
You can add global styles to the `preview-header.html` file. It will only be included in the iframe.
https://storybook.js.org/configurations/add-custom-head-tags/ 

Closing this issue, please reopen if there's still a problem.

**Closed by danielduan** 2017-08-27 20:51 UTC
Labels: bug, needs reproduction

**Comment by Hypnosphi** [comment] 2017-08-30 12:02
If we inject styles imported from stories into manager html, it’s definitely a bug

**Comment by Hypnosphi** [comment] 2017-08-30 12:06
@timoxley is there a chance that you added `ExtractTextPlugin` to your custom webpack config in `.storybook` directory?

**Comment by Hypnosphi** [comment] 2017-08-31 00:54
Ok, I can't reproduce it even with `ExtractTextPlugin`

**Comment by danielduan** [comment] 2017-08-31 03:51
Could there be a possibility where something in `css-loader` was scoped with `:global` and therefore applies to all components, not just the ones in the iframe?

**Comment by Hypnosphi** [comment] 2017-08-31 11:14
@danielduan what do you mean? We don't use css module in our default config, so in default setup all styles are global.
https://github.com/storybooks/storybook/blob/master/app/react/src/server/config/defaults/webpack.config.js#L16-L19

But global means "applied all over the current document", and iframe is a separate document

**Comment by danielduan** [comment] 2017-08-31 15:33
A component could be used both inside and outside the iframe and therefore leak the styles right?
 Seems like a very unlikely scenario.

Given how old this issue is, without any solid reproduction, I think we should just let this die.

**Comment by aparij** [comment] 2018-06-06 13:55
I have similar issue. My app `body` style leaks into the iframe because I assume I'm using custom webpack config with LESS and other loaders.

``` 
      {  test: /\.less$/,
         loaders: ['style-loader', 'css-loader', 'postcss-loader', 'less-loader'],
         include: path.resolve(__dirname, "../")
       },
```

**Comment by Hypnosphi** [comment] 2018-06-08 08:20
Do you import `.less` file with your `body` styles from your stories or components? Then it looks like expected behavior to me
