### ISSUE TITLE
React Native Storybook is black on iOS

### ISSUE THREAD

**Issue by fo-fo** [storybooks/storybook#5628] opened 2019-02-17 11:48 UTC
**Describe the bug**
The React Native Storybook navigator is completely black on iOS. The menu items appear to exist (they react to clicks) but are not visible (black text on black background?). The story component is also visible on the right.

**To Reproduce**
1. Build a project with React Native storybook
2. Open the project in iOS simulator

**Expected behavior**
The navigator view should display the story names.

**Screenshots**
<img width="393" alt="screenshot 2019-02-17 at 13 37 19" src="https://user-images.githubusercontent.com/1111494/52912453-703f1900-32ba-11e9-89df-d73eb9ae5def.png">

**System:**
 - OS: macOS 10.14.3
 - Device: iPhone X (iOS simulator)
 - Browser: n/a
 - Framework: React Native
 - Addons: -
 - Version: 4.1.11

**Comment by shilman** [comment] 2019-02-18 12:58
Cc @Gongreg

**Comment by Gongreg** [comment] 2019-02-18 13:02
Duplicate of #5377

**Closed by Gongreg** 2019-02-18 13:02 UTC
Labels: app: react-native, question / support
