### ISSUE TITLE
Zooming on component causes overflow scrollbars to scale poorly

### ISSUE THREAD

**Issue by vvanpo** [storybooks/storybook#5812] opened 2019-03-01 17:18 UTC
**Describe the bug**
Overflow scrollbars in component views scale with the component as you zoom in, and the anti-aliasing scales as well leading to very ugly scrollbars.

**To Reproduce**
Navigate to any component in Storybook 5.0.0-rc.7, and zoom in drastically until the component overflows and scrollbars appear.

**Expected behavior**
I would expect scrollbars not to change size when zooming on a component, as they are not part of the component.

**Screenshots**
![screen shot 2019-03-01 at 9 11 55 am](https://user-images.githubusercontent.com/3506391/53654335-5e3a7000-3c02-11e9-855a-a4e32020daa9.png)

**System:**
 - OS: MacOS Mojave
 - Device: Macbook Pro
 - Browser: Chrome 72
 - Framework: html
 - Version: Storybook 5.0.0-rc.7

**Comment by Armanio** [comment] 2019-03-16 11:16
Hi!
I right understand, is it the expected behaviour?
![2019-03-16 14 11 55](https://user-images.githubusercontent.com/3195714/54474421-98586400-47f5-11e9-8571-03dc9d9940c3.gif)

**Comment by shilman** [comment] 2019-03-26 03:20
Jeepers creepers!! I just released https://github.com/storybooks/storybook/releases/tag/v5.1.0-alpha.15 containing PR #6126 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Closed by shilman** 2019-03-26 03:20 UTC
Labels: bug, ui
