### ISSUE TITLE
Storysource: clicking on stories does not update what is highlighted

### ISSUE THREAD

**Issue by domyen** [storybooks/storybook#5592] opened 2019-02-15 00:21 UTC
**Describe the bug**
When you click on a story in the sidebar, Storysource does not update the code area that is highlighted.

**To Reproduce**
1. Go to [`WithTooltip`](http://localhost:9011/?path=/story/basics-tooltip-withtooltip--simple-click)
2. Click on the stories in the sidebar
3. Observe that the code highlighted in Storysource does not change

**Expected behavior**
I expect the highlighted code to change.

**Screenshots**
Here's a gif of this behavior in the `Button` component. https://cl.ly/335848ffb52a

**Comment by tmeasday** [comment] 2019-02-15 02:19
I think the issue is more widespread than that. In general it doesn't seem to update (some rare times it does)

**Comment by shilman** [comment] 2019-02-18 12:32
This is an issue with the Storybook syntax highlighter component.

The problem is fixed when I edit `storysource/src/StoryPanel.js` and replace:

```js
import { Link, SyntaxHighlighter } from '@storybook/components';
```

With:

```js
import { Link } from '@storybook/components';
import SyntaxHighlighter from 'react-syntax-highlighter/prism-light';
```

However, we lose some functionality in the process.

At any rate there is no generic problem with addons. I think they just haven't been tested since the upgrade and are full of bugs.

**Comment by ndelangen** [comment] 2019-02-19 11:18
I'm on it

**Comment by shilman** [comment] 2019-02-21 10:24
Yay!! I just released https://github.com/storybooks/storybook/releases/tag/v5.0.0-rc.4 containing PR #5672 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Closed by shilman** 2019-02-21 10:24 UTC
Labels: addon: storysource, bug

**Comment by martinmcwhorter** [comment] 2019-03-25 12:16
I am seeing a similar possibly related issue with Storysource where the selected story does not get highlighted.

I am using "@storybook/angular": "^5.0.5" and  "@storybook/addon-storysource": "^5.0.5"

My .storybook/webpack.config.js is
```
const path = require('path');

module.exports = function({ config }) {
  config.module.rules.push({
    test: /\.stories\.ts?$/,
    loaders: [
      {
        loader: require.resolve('@storybook/addon-storysource/loader'),
        options: {
          parser: 'typescript',
        },
      },
    ],
    enforce: 'pre',
    include: [path.resolve(__dirname, '../src')],
  });

  return config;
};
```

The source shows up, there is just no highlight of the selected story. The source code is black-text on white-background which is different from all screenshots of this feature that I have seen. Could this be theming to styling issue?

**Comment by TerrenceLJones** [comment] 2019-05-17 20:50
I think this issue is related to https://github.com/storybooks/storybook/issues/6136

**Comment by MrBugatti** [comment] 2019-11-11 16:19
> I am seeing a similar possibly related issue with Storysource where the selected story does not get highlighted.
> 
> I am using "@storybook/angular": "^5.0.5" and "@storybook/addon-storysource": "^5.0.5"
> 
> My .storybook/webpack.config.js is
> 
> ```
> const path = require('path');
> 
> module.exports = function({ config }) {
>   config.module.rules.push({
>     test: /\.stories\.ts?$/,
>     loaders: [
>       {
>         loader: require.resolve('@storybook/addon-storysource/loader'),
>         options: {
>           parser: 'typescript',
>         },
>       },
>     ],
>     enforce: 'pre',
>     include: [path.resolve(__dirname, '../src')],
>   });
> 
>   return config;
> };
> ```
> 
> The source shows up, there is just no highlight of the selected story. The source code is black-text on white-background which is different from all screenshots of this feature that I have seen. Could this be theming to styling issue?

This is what I was looking for related to implementing with Angular.
