### ISSUE TITLE
"< />" symbols  in storiesOf name cause "Maximum call stack error"

### ISSUE THREAD

**Issue by tuchk4** [storybooks/storybook#6128] opened 2019-03-16 17:55 UTC
**Describe the bug**
"< />" symbols in `storiesOf` name cause "Maximum call stack error"

**Screenshots**
![image](https://user-images.githubusercontent.com/5140611/54479440-51826280-4825-11e9-8f2b-02ccc65f78a4.png)

**Code snippets**
```js
storiesOf('Vue <docs/>', module)
  .add('Button', () => {
    return {
      components: {
        MyButton,
      },
      template: `<my-button>My Button</my-button>`,
    };
  });
```

**System:**
 - OS: macOS
 - Device: [e.g. iPhoneX, Macbook Pro 2018]
 - Browser: Chrome latest
 - Framework: vue

**Comment by shilman** [comment] 2019-03-17 02:14
Thanks @tuchk4 -- good one! Can confirm this is an issue in core, reproducible in our examples for every view layer,.

**Comment by Armanio** [comment] 2019-03-17 11:10
Hi @tuchk4 
Interesting issue. I can reproduce on vue and svelte. On react app all is ok.
I'll do it. 🤔

**Comment by Armanio** [comment] 2019-03-17 11:22
I investigated this problem: look like trouble in your config:
if you add `hierarchySeparator: /\./,` in 'addParameters' arg problem is solved.
Of course, it's not very elegant solution, but it's working solution. 😄

**Comment by shilman** [comment] 2019-04-01 02:04
Just got a dupe to this. @Armanio what's a better long-term solution?

**Comment by Armanio** [comment] 2019-04-01 07:43
Sorry, guys. Honestly, I forgot about this issue. Today I'll try find better solution.

**Comment by Armanio** [comment] 2019-04-06 12:38
Hi, guys! I'm back with a possible fix. Invite you in PR for discussion.

**Comment by shilman** [comment] 2019-04-26 17:44
Gadzooks!! I just released https://github.com/storybooks/storybook/releases/tag/v5.1.0-alpha.35 containing PR #6607 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Closed by shilman** 2019-04-26 17:44 UTC
Labels: bug, core, good first issue, has workaround, high priority
