### ISSUE TITLE
sh: 1: start-storybook: Permission denied

### ISSUE THREAD

**Issue by Lazzaro83** [storybooks/storybook#2460] opened 2017-12-11 12:10 UTC
My storybook was working fine on Windows 10. I had to move to Linux Ubuntu 16 and after I have set my environment and typed in the terminal npm run storybook, this is what I get:

sh: 1: start-storybook: Permission denied
npm ERR! code ELIFECYCLE
npm ERR! errno 126
npm ERR! quinyx-components@1.0.0 storybook: `start-storybook -p 9001`
npm ERR! Exit status 126
npm ERR! 
npm ERR! Failed at the quinyx-components@1.0.0 storybook script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lazar/.npm/_logs/2017-12-11T12_01_09_276Z-debug.log

Does anybody know how to solve this problem?

**Comment by texttechne** [comment] 2017-12-11 12:20
Seems to me that it tries to start a shell script: `sh`.
The permissions are probably wrong, maybe the line encoding is wrong if you've moved it from windows...

Did you install it from scratch? With sudo or without?
Have you tried to nuke node_modules and npm install everything again?

**Comment by Lazzaro83** [comment] 2017-12-11 12:36
@texttechne thank you very much. I am new to Linux, so it will take some time to get into it :)

**Comment by texttechne** [comment] 2017-12-11 13:03
Did any of the tips solve your issue?

In any case, I think it would be best to close this issue, because it's really not an issue of storybook and the guys have enough tickets :-)

If you need more help then tell me more specifics..

**Closed** 2017-12-11 14:56 UTC
Labels: question / support

**Comment by frankred** [comment] 2017-12-15 11:58
The problem is that there is no `start-storybook` cmd or binary. How to get this tool?

**Comment by khatrimanoj** [comment] 2020-03-13 06:16
first delete your node_modules folder or rename it. And then again install node_modules by running "npm install". now working fine.

**Comment by xXACCEXx** [comment] 2025-02-20 23:07
Just experienced this issue, too. Built in Linux from day one.
Nuked node_modules and package-lock then reinstall, same error.
