### ISSUE TITLE
docs: website: links to "Made for" sections point to 404 errors

### ISSUE THREAD

**Issue by d2s** [storybooks/storybook#5994] opened 2019-03-10 05:31 UTC
**Describe the bug**
Links to _"Made for"_ sections on the front page of the Storybook website https://storybook.js.org/ point to a missing documentation pages (even while those pages exist on other URL addresses).

**To Reproduce**
1. Go to _'Storybook website'_ https://storybook.js.org/
2a. Click on _'Made for … HTML'_ link on the right side of the page (on larger screens)
2b. Click on _'Made for … Svelte'_ link on the right side of the page (on larger screens)
3a. Link points to URL: https://storybook.js.org/basics/guide-html/
3b. Link points to URL: https://storybook.js.org/basics/guide-svelte/
4. See error: _`404 - Yikes, this is embarassing - Try double-checking the link or going back.`_

**Expected behavior**
Expected links to point towards a working page address:
https://storybook.js.org/docs/guides/guide-html/
https://storybook.js.org/docs/guides/guide-svelte/

**Screenshots**
On the main page of the Storybook website:
<img width="280" alt="2019-03-09-Storybook-website-broken-link-404" src="https://user-images.githubusercontent.com/135053/54080946-0e476180-4304-11e9-8f6e-7ec9380fed89.PNG">

**Code snippets**
Potentially related snippets on the Storybook codebase:

https://github.com/storybooks/storybook/blob/953c43bec6e5ecf09689d1d86fcc01fee5eb11f4/docs/src/new-components/basics/shared/site.js#L74-L75

https://github.com/storybooks/storybook/blob/953c43bec6e5ecf09689d1d86fcc01fee5eb11f4/docs/gatsby-config.js#L16-L26

It might be that those two pages would need to be added to the `docs/gatsby-config.js` file.

```js
        '/guides/guide-html/',
        '/guides/guide-svelte/',
```

**System:**
 - OS: Windows10
 - Device: Desktop
 - Browser: Chrome-based browser
 - Framework: not relevant for this issue
 - Addons: not relevant for this issue
 - Version: 5.0.0 (website)

**Comment by shilman** [comment] 2019-03-10 09:53
@d2s Thanks for the report! It's strange -- I couldn't reproduce the behavior since the site was redirecting properly for me. Nevertheless I've updated the URLs in the docs site and also in the frontpage marketing site, so hopefully it should be fixed now.

**Comment by d2s** [comment] 2019-03-10 12:26
@shilman Yes, I thought it could be an issue with redirects. Generally it is a good idea to avoid adding the extra HTTP redirect step to the requests, as it slows down the page performance (even without having this kind of potential issues).

Thank you for the good tool. Lets make it even better, step by step. 😄

**Closed** 2019-03-10 15:10 UTC
Labels: bug, documentation
