### ISSUE TITLE
The knobs are not updating the component after change in Vue

### ISSUE THREAD

**Issue by caioincau** [storybooks/storybook#6312] opened 2019-03-27 12:37 UTC
**Describe the bug**
The knobs are not updating the component after change.

**To Reproduce**

The knobs are working, but when I change some value in storybook, the component doesn't chage at all, I am usign v5.0.5 and this is my config: 

```
import { configure, addDecorator } from '@storybook/vue';
import { withKnobs } from '@storybook/addon-knobs';

// automatically import all files ending in *.stories.js
const req = require.context('../stories', true, /\.stories\.js$/);
function loadStories() {
  req.keys().forEach(filename => req(filename));
}

addDecorator(withKnobs);

configure(loadStories, module);

```

My story:

```

import { storiesOf } from '@storybook/vue';
import { action } from '@storybook/addon-actions';
import { text, boolean } from '@storybook/addon-knobs';

import Vue from 'vue';
import Vuetify from 'vuetify';
import 'vuetify/dist/vuetify.css'
import theme from '../src/theme'


Vue.use(Vuetify, { theme })


import CustomButton from 'src/components/CustomButton'


const knobConfigs = {
  chevronRight: {
    default: boolean('chevronRight', false)
  },
  loading: {
    default: boolean('loading state', true)
  },
  full: {
    default: boolean('full layout', false)
  },
  iconName: {
    default: text('iconName', 'arrow-up')
  },
  layout: {
    default: text('layout', 'depressed')
  }
}

const stories = storiesOf('Button', module)

stories.add('with text', () => ({
  components: { CustomButton },
  props: knobConfigs,
  template: `<v-app><custom-button
    :chevronRight="chevronRight"
    :loading="loading"
    :full="full"
    :iconName="iconName"
    :layout="layout"
    @click="action">
      Hello Button
    </custom-button></v-app>`,
  methods: { action: action('clicked') }
}))

```

And my Component:

```
<template>
  <section class="custom-button" :data-test="dataTest">
    <template v-if="is_file">
      <label
        class="custom-button__btn-element v-btn v-btn--depressed theme--light"
        :class="file_classes"
        v-bind="$attrs"
        :for="name">
        <input type="file" :accept="accept" @change="$_broadcast($event)" :name="name" :id="name" v-show="false" />
        <template v-if="iconName && iconPosition === 'left'">
          <icon :name="iconName" class="custom-button__icon --left"></icon>
        </template>
        <slot></slot>
        <template v-if="iconName && iconPosition === 'right'">
          <icon :name="iconName" class="custom-button__icon --right"></icon>
        </template>
        <template v-if="chevronRight">
          <icon name="chevrons-right" class="custom-button__icon --right"></icon>
        </template>
      </label>
    </template>
    <template v-else>
      <v-btn
        v-bind="$attrs"
        :form="form"
        :block="full"
        :color="color"
        :loading="loading"
        :type="type"
        :depressed="is_depressed"
        :outline="is_outline"
        @click="$_broadcast($event)"
        class="custom-button__btn-element">
        <template v-if="iconName && iconPosition === 'left'">
          <icon :name="iconName" class="custom-button__icon --left"></icon>
        </template>
        <slot></slot>
        <template v-if="iconName && iconPosition === 'right'">
          <icon :name="iconName" class="custom-button__icon --right"></icon>
        </template>
        <template v-if="chevronRight">
          <icon name="chevrons-right" class="custom-button__icon --right"></icon>
        </template>
      </v-btn>
    </template>
  </section>
</template>

<style lang="less">
// ommited
</style>

<script>
import Interactions from 'src/mixins/interactions'
import InteractiveComponent from 'src/components/InteractiveComponent'
import Icon from 'src/components/Icon'

export default {
  inheritAttrs: true,
  extends: InteractiveComponent,
  name: 'custom-button',
  description: 'Button for all occasion.',
  mixins: [Interactions],
  components: {
    Icon
  },
  props: {
    accept: {
      type: String,
      description: 'Valid file extensions for File Selector.'
    },
    name: {
      type: String
    },
    iconName: {
      type: String,
      default: '',
      description: 'Adds an icon on the button, use just the name of the icon.'
    },
    full: {
      type: Boolean,
      default: false,
      description: 'Button width 100%. Translates to v-btn block prop'
    },
    chevronRight: {
      type: Boolean,
      default: false,
      description: 'Forced right chevron'
    },
    loading: {
      type: Boolean,
      default: false,
      description: 'Button\'s loading state'
    },
    layout: {
      type: String,
      default: 'depressed',
      description: 'Button layout. depressed or outline'
    },
    color: {
      type: String,
      default: 'primary',
      description: 'Button color. Translates to color prop for v-btn'
    },
    iconPosition: {
      type: String,
      default: 'left',
      description: 'Button icon position'
    },
    form: {
      type: String,
      description: 'The form ID to be targeted on Submit.'
    },
    type: {
      type: String,
      default: 'button',
      description: 'The button type'
    }
  },
  computed: {
    is_file() {
      return this.type === 'file'
    },
    is_depressed() {
      return this.layout === 'depressed'
    },
    is_outline() {
      return this.layout === 'outline'
    },
    file_classes() {
      return {
        [`${this.color}`]: true,
        'v-btn--depressed': this.is_depressed,
        'v-btn--outline': this.is_outline
      }
    }
  },
  methods: {
    $_broadcast(ev) {
      this.$emit(ev.type, ev)
    }
  }
}
</script>
```

Video:

[Screen Recording 2019-03-27 at 09.36.30.zip](https://github.com/storybooks/storybook/files/3013113/Screen.Recording.2019-03-27.at.09.36.30.zip)

**Comment by Kailaash-Balachandran** [comment] 2019-03-27 12:52
It doesn't work on v5.0.3 either.

**Comment by Kailaash-Balachandran** [comment] 2019-03-27 13:05
**Story:**
```
import { storiesOf } from '@storybook/vue'
import EmptyState from 'src/components/EmptyState.vue'
import { withKnobs, boolean } from '@storybook/addon-knobs'

storiesOf('EmptyState', module)
  .addDecorator(withKnobs)
  .add('default', () => {
    return {
      components: { EmptyState },
      props: {
        displayArrow: {
          type: Boolean,
          default: boolean('displayArrow', false),
        },
      },
      template: `<EmptyState :displayArrow="displayArrow"/>`,
    }
  })
```

**in Console when I toggle knob:**
```
index.js:11 message arrived at preview storybooks/knobs/change {name: "displayArrow", type: "boolean", value: true}
vendors~main.5ea49f4db22eb77e3e4a.bundle.js:8083 message arrived at manager forceReRender
vendors~main.5ea49f4db22eb77e3e4a.bundle.js:8083 message arrived at manager storybooks/knobs/set-options {escapeHTML: true}escapeHTML: true__proto__: Object
vendors~main.5ea49f4db22eb77e3e4a.bundle.js:8083 message arrived at manager registerSubscription ƒ connectCallbacks() {var channel = _addons.default.getChannel();channel.on(_shared.CHANGE, knobChanged);channel.on(_shared.CLICK, knobClicked);channel.on(_coreEvents.STORY_CHANGED, resetKnobs);channel…
vendors~main.5ea49f4db22eb77e3e4a.bundle.js:8083 message arrived at manager storyRendered emptystate--default
vendors~main.5ea49f4db22eb77e3e4a.bundle.js:8083 message arrived at manager storybooks/knobs/set {knobs: {…}, timestamp: 1553691367385}knobs: displayArrow: {type: "boolean", value: true, name: "displayArrow", defaultValue: false, used: true}__proto__: Objecttimestamp: 1553691367385__proto__: Object
```

**Comment by exlame** [comment] 2019-03-27 13:56
I can reproduce this problem when I am using imported components:
## Working
```
import { withKnobs, text } from '@storybook/addon-knobs';

storiesOf('Knobs', module)
  .addDecorator(withKnobs)
  .add('Simple', () => ({
    props: {
      name: {
        type: String,
        default: text('Name', 'John Doe'),
      },
    },

    template: '<div @click="age++">I am {{ name }} and I\'m {{ age }} years old.</div>',

    data() {
      return { age: 40 };
    },

  }));

```

# Not working
```
import { withKnobs } from '@storybook/addon-knobs';
import Simple from './Simple/Simple.vue';

storiesOf('Knobs', module)
  .addDecorator(withKnobs)
  .add('Simple', () => (Simple));
```
./Simple/Simple.vue
```
<script>
import { text } from '@storybook/addon-knobs';

export default {
  props: {
    name: {
      type: String,
      default: text('Name', 'John Doe'),
    },
  },
  template: '<div @click="age++">I am {{ name }} and I\'m {{ age }} years old.</div>',
  data() {
    return { age: 40 };
  },
};
</script>
```

**Comment by caioincau** [comment] 2019-03-27 15:50
@Kailaash-Balachandran I just tested with V5.0.5, because it is a new project.

**Comment by shilman** [comment] 2019-03-28 01:17
cc @backbone87

**Comment by backbone87** [comment] 2019-03-28 02:35
in your example from the opening post you define your `knobConfigs` outside of your story function. the knob calls must occur inside the story function (knob calls have sideeffects that get tracked during story function execution)

your example from https://github.com/storybooks/storybook/issues/6312#issuecomment-477143974 should work

**Comment by Kailaash-Balachandran** [comment] 2019-03-28 15:12
@backbone87 It doesn't seem to work in the example.

**Comment by backbone87** [comment] 2019-03-28 18:09
@Kailaash-Balachandran what example? https://github.com/storybooks/storybook/issues/6312#issuecomment-477143974 should work, if storybook is set up correctly

**Comment by Kailaash-Balachandran** [comment] 2019-03-28 18:55
@backbone87 No, it does not work. I added the example story as a reply to https://github.com/storybooks/storybook/issues/6312#issuecomment-477138728

Other addons seems to work just fine. If the issue is not reported by anyone else, I should check the webpack setup as you suggested.

**Comment by backbone87** [comment] 2019-03-28 19:04
without more context, i cant judge, the story itself is fine

**Comment by caioincau** [comment] 2019-04-01 10:43
Thanks @backbone87 I moved the config to an inline one and it worked.

**Comment by backbone87** [comment] 2019-04-01 19:13
ok, gonna close this.

@Kailaash-Balachandran if you still have problems please open a new issue

**Closed by backbone87** 2019-04-01 19:13 UTC
Labels: addon: knobs, app: vue, question / support
