### ISSUE TITLE
Uncaught Error: Target container is not a DOM element.

### ISSUE THREAD

**Issue by pelotom** [storybooks/storybook#2615] opened 2018-01-01 22:58 UTC
I am getting this error since upgrading from `3.2.18` to `3.3.3`:

```
Uncaught Error: Target container is not a DOM element.
    at invariant (invariant.js:42)
    at renderSubtreeIntoContainer (react-dom.development.js:15180)
    at Object.render (react-dom.development.js:15290)
    at exports.default (routes.js:39)
    at App.init (app.js:119)
    at exports.default (index.js:41)
    at Object.<anonymous> (index.js:16)
    at __webpack_require__ (bootstrap 77c5cb83d0653d7a60e4:678)
    at fn (bootstrap 77c5cb83d0653d7a60e4:88)
    at Object.defineProperty.value (fuse.js:996)
```

And the page is just showing the following text:

```
/static/media/index.html.3cbc7277.ejs
```

**Comment by ndelangen** [comment] 2018-01-02 14:42
@pelotom Thanks for opening up an issue, I've seen this error during development on 3.3.
It was when running storyshots, We fixed it there, but it seems you're experiencing it in a different scenario.

Can you make sure all storybook related packages are at the same version?

It looks like it's related to a webpack config. We use the HTMLplugin with a template, seems that's where the problem might be.

**Comment by ndelangen** [comment] 2018-01-02 14:43
Are you using a custom webpack config? If so, can you share it?

**Comment by aaronfullerton** [comment] 2018-01-02 15:45
@ndelangen I'm also getting this exact error using a custom webpack config since upgrading to 3.3.

If it's helpful, here's my [webpack config](https://gist.github.com/aaronfullerton/48a52d99763b68fd6bb5d84a4f4d44b2), which is more or less the version that ships with create-react-app.

**Comment by pelotom** [comment] 2018-01-02 15:58
I’m also using a webpack config derived from CRA.

**Comment by ndelangen** [comment] 2018-01-02 22:01
Do you have a repo I can checkout @aaronfullerton or @pelotom ?

I'm trying the webpack config @aaronfullerton provided, but it's demanding a lot of time getting it setup in a way for me to reproduce.

**Comment by aaronfullerton** [comment] 2018-01-03 00:02
@ndelangen sure, You can try this: https://github.com/aaronfullerton/storybook-issue-2615

I pulled this from our existing codebase and attempted to remove as much noise as possible. My apologies if there's still a bit of unnecessary code in there.

**Comment by ndelangen** [comment] 2018-01-03 16:53
Thank you, I have found the solution to the problem thanks to your reproduction repo ❤️ 

Here's the required change:
https://github.com/aaronfullerton/storybook-issue-2615/pull/1

**Comment by ndelangen** [comment] 2018-01-03 16:53
Please let me know if this doesn't solve the problem for you, or something else breaks.

I'll close the issue, but happy to re-open if it still goes 💥

**Closed by ndelangen** 2018-01-03 16:53 UTC
Labels: bug, question / support

**Comment by aaronfullerton** [comment] 2018-01-03 17:06
Excellent, thank you. I can confirm this solves the problem. I'll look into updating the docs to indicate this.

**Comment by loadingwyn** [comment] 2018-01-16 03:31
I find this error in`3.3.9` too.  I’m also using a webpack config derived from CRA. If I remove file-loader from the config, this problem can be solved.
Here is the file-loader config:

```js
{
                exclude: [
                    /\.html$/,
                    /\.(js|jsx)$/,
                    /\.css$/,
                    /\.scss$/,
                    /\.json$/,
                    /\.bmp$/,
                    /\.gif$/,
                    /\.jpe?g$/,
                    /\.png$/,
                ],
                loader: 'file-loader',
                options: {
                    name: 'static/media/[name].[hash:8].[ext]',
                },
            },
````

**Comment by pelotom** [comment] 2018-01-16 04:03
You don't have to remove the file loader, just exclude `*.ejs`:

```diff
{
  exclude: [
    /\.html$/,
    /\.(js|jsx)$/,
    /\.css$/,
    /\.scss$/,
    /\.json$/,
    /\.bmp$/,
    /\.gif$/,
    /\.jpe?g$/,
    /\.png$/,
+   /\.ejs$/,
  ],
  loader: 'file-loader',
  options: {
    name: 'static/media/[name].[hash:8].[ext]',
  },
},
```

**Comment by loadingwyn** [comment] 2018-01-18 02:18
It works. Thank you!

**Comment by switz** [comment] 2018-03-07 17:43
What if my webpack config doesn't use file-loader and I'm seeing this?

Running:

```
    "@storybook/addon-actions": "^3.3.15",
    "@storybook/addon-info": "^3.3.15",
    "@storybook/addon-links": "^3.3.15",
    "@storybook/addon-options": "^3.3.15",
    "@storybook/addons": "^3.3.15",
    "@storybook/react": "^3.3.15",
```

**Comment by Hypnosphi** [comment] 2018-03-18 14:28
> And the page is just showing the following text:
>```
>/static/media/index.html.3cbc7277.ejs
>```

Is it the case for you @switz ?

**Comment by sathiyaanbu** [comment] 2018-07-13 07:55
I got the same error :  Target container is not a DOM element.

Here is my webpack.config,.js:
```
const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = {
  entry: './src/index.js',
  output: {
    path: path.join(__dirname, '/dist'),
    filename: 'bundle.js'
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        use: {
          loader: 'babel-loader'
        }
      },
      {
        test: /\.css$/,
        use: ['style-loader', 'css-loader']
      }
    ]
  },
  plugins: [
    new HtmlWebpackPlugin({
      template: './src/index.html'
    })
  ]
};

```
 ```
 "babel-core": "^6.26.3",
    "babel-loader": "^7.1.5",
    "babel-preset-env": "^1.7.0",
    "babel-preset-react": "^6.24.1",
    "css-loader": "^1.0.0",
    "html-webpack-plugin": "^3.2.0",
    "json-loader": "^0.5.7",
    "style-loader": "^0.21.0",
    "webpack": "^4.15.1",
    "webpack-cli": "^3.0.8",
    "webpack-dev-server": "^3.1.4"

 
```
   ```
 "axios": "^0.18.0",
    "prop-types": "^15.6.2",
    "react": "^16.4.1",
    "react-dom": "^16.4.1",
    "react-redux": "^5.0.7",
    "reactstrap": "^6.3.0",
    "redux": "^4.0.0",
    "redux-promise": "^0.6.0",
    "redux-thunk": "^2.3.0"
  
```
Any solutions pls?

**Comment by ndelangen** [comment] 2018-07-14 05:53
@sathiyaanbu The webpack config you provide is getting merged with a base-config..
The base already has everything you add to it. This causes the html-plugin to be registered twice. That results in the error you see, I think.

Try removing your webpack config completely or removing the html-webpack plugin from your storybook's webpack config.

**Comment by sathiyaanbu** [comment] 2018-07-14 06:03
@ndelangen Thanks for your suggestion. I fixed the error. It's because of my silly mistake. I added (.) along with the classname in index.js. That's why it couldn't render and  showed error. 

But Now I got another issue.  I need to fetch all data in a table. I confused with the data structure. I can only fetch only One row not all. any suggestions pls? 
```
import { connect } from 'react-redux';
import { fetchData } from '../actions/index';

import { Table, img } from 'reactstrap';

class DataList extends Component {
  componentWillMount() {
    this.props.fetchData();
  }

  render() {
    const dataItems = this.props.results.map(result => (
      <tr key={result.results[0].id}>
        <td>{result.results[0].id}</td>
        <td>
          <img
            style={{ width: '150px', height: '100px' }}
            src={result.results[0].image}
          />
        </td>
        <td>{result.results[0].name}</td>
        <td>{result.results[0].status}</td>
        <td>{result.results[0].species}</td>
      </tr>
    ));

    return (
      <Table bordered>
        <thead>
          <tr>
            <th>id</th>
            <th>Character image</th>
            <th>Name</th>
            <th>Status</th>
            <th>Species</th>
          </tr>
        </thead>
        <tbody>{dataItems}</tbody>
      </Table>
    );
  }
}

const mapStateToProps = state => ({
  results: state.results
});

export default connect(mapStateToProps, { fetchData })(DataList);
````
<img width="1173" alt="screen shot 2018-07-13 at 22 57 44" src="https://user-images.githubusercontent.com/23448180/42721512-7e93cc5c-8744-11e8-9d16-1a8da4469f13.png">

**Comment by ndelangen** [comment] 2018-07-14 06:14
@sathiyaanbu that doesn't seem like a storybook issue, sorry.

I highly recommend you fill your component-stories with mockdata, not with data fetched from an API.

**Comment by Mandy94** [comment] 2018-07-15 12:29
If there is someone who hasn't fix the problem jet, check the order of your tag elements in html.
For example I wrote ( as in tutorial )
  
```
    <script src="/app/something.js"></script>
    <div id="root"> x </div>
```

But the script tag should be **below** the DOM element.
I've lost 2h on this :/
Cheers!

**Comment by marisev** [comment] 2018-07-18 18:17
Got the same error after upgrading react-styleguidist from 7.0.20 to 7.1.0.  I have .ejs in the list of excluded. Wonder if anyone has any new thoughts on this topic :)

**Comment by epoz** [comment] 2018-09-03 10:58
Yowzers, thanks for the heads-up @Mandy94 that saved me a lot of time.

**Comment by chiholiu** [comment] 2018-09-11 12:03
Check in your html file if the id attribute has the same name as 
ReactDOM.render(<App />, document.getElementById('index'));

**Comment by BinitaBharati** [comment] 2019-03-06 06:56
I bumped into this thread while searching for "React Target container is not a DOM element". This is not related to storybook, nevertheless, I will leave my comments here, as it may help some other person. So, I was facing the same error with minimal React.js code. I had a basic html with a empty target div, which had to be populated by React js code.  As mentioned by @Mandy94, moving the dom container before the script tag worked.

**Comment by wangsongiam** [comment] 2019-03-17 03:14
It looks like an erroring indicating the "root" dom element for targeting/mounting from js was not found.

**Comment by bensampaio** [comment] 2019-11-29 15:43
I am having this exact same problem apparently because I am changing the id of `root` to `app-root`. I am doing this because I would like the dom in my storybook to look just like the dom of my application. This also makes it easier to test modals and so on. Currently I am doing this via a global decorator that basically does this:

```
const appRoot = document.getElementById('root');

appRoot.setAttribute('id', 'app-root');
```

Is there any better way of doing this?

**Comment by ndelangen** [comment] 2019-12-05 13:19
How about wrapping it?

```html
<div id="app-root">
  <div id="root">
  </div>
</div>
```
?

**Comment by Jinujs** [comment] 2020-07-14 05:35
please add these lines to your index.js file
 ReactDOM.render(
     <React.StrictMode>
      <App />     //  render your component
     </React.StrictMode>,
     document.getElementById("root")
  );

**Comment by sideeq12** [comment] 2020-11-08 14:46
I'm having same issue "Target container is not a DOM"
 and I specify <script></script> below the <div id="root"></div>

**Comment by pmongkho** [comment] 2021-02-09 22:40
![image](https://user-images.githubusercontent.com/71842268/107437935-5d502f80-6af5-11eb-834c-6df52a862a56.png)

is this the same issue? i have the right lines of code but it doesnt resolve, is it a webpack error?

**Comment by newcanopies** [comment] 2021-04-09 15:04
hi @ndelangen 

there is no root div in my index.html

![image](https://user-images.githubusercontent.com/65022111/114200540-98d07400-9955-11eb-8606-69aa1495132b.png)

**Comment by sunidhi56** [comment] 2021-08-01 05:46
> ![image](https://user-images.githubusercontent.com/71842268/107437935-5d502f80-6af5-11eb-834c-6df52a862a56.png)
> 
> is this the same issue? i have the right lines of code but it doesnt resolve, is it a webpack error?

how did you solve this issue
