### ISSUE TITLE
Number Knob throws error when clearing value

### ISSUE THREAD

**Issue by amcdnl** [storybooks/storybook#2693] opened 2018-01-08 22:56 UTC
## Issue
When using knobs with Angular, when I created a number knob and then removed the value in the ui it throws the following error:

```javascript
manager.bundle.js:6680 Warning: Received NaN for the `value` attribute. If this is expected, cast the value to a string.
    in input (created by NumberType)
    in NumberType (created by PropField)
    in div (created by PropField)
    in PropField (created by propForm)
```

from this config:

```javascript
storiesOf('Stepper', module)
    .add(
        'Basic Stepper',
        withNotes(docs)(() => ({
            component: BasicStepperComponent,
            props: {
                step: number('Step', 0)
            },
            moduleMetadata: {
                imports: [StepperModule]
            }
        }))
    );

```

## Versions
```
        "@angular/common": "^5.1.3",
        "@angular/compiler": "^5.1.3",
        "@angular/core": "^5.1.3",
        "@angular/platform-browser": "^5.1.3",
        "@angular/platform-browser-dynamic": "^5.1.3",
        "@storybook/addon-actions": "^3.4.0-alpha.0",
        "@storybook/addon-knobs": "^3.4.0-alpha.0",
        "@storybook/addon-links": "^3.4.0-alpha.0",
        "@storybook/addon-notes": "^3.4.0-alpha.0",
        "@storybook/addon-options": "^3.4.0-alpha.0",
        "@storybook/angular": "^3.4.0-alpha.0",
````

**Comment by alterx** [comment] 2018-01-17 16:02
This is a knobs issue not directly related to the Angular implementation. I just tested the cra kitchen sink app and this is also happening. We should fix this in the addon itself.

**Comment by Hypnosphi** [comment] 2018-01-27 11:50
Looks like a duplicate of https://github.com/storybooks/storybook/issues/2475, closing this one. Feel free to open a PR

**Closed by Hypnosphi** 2018-01-27 11:51 UTC
Labels: addon: knobs, bug
