### ISSUE TITLE
Expecting a valid React element from the story with Knobs

### ISSUE THREAD

**Issue by leonidax** [storybooks/storybook#1160] opened 2017-05-30 15:47 UTC
Hi recently there was a change in the types definitios of 

https://github.com/storybooks/storybook/blob/master/addons/knobs/storybook-addon-knobs.d.ts

withKnobs was converted to an interface and replaced by withKnobsOptions

This mismatches the documentation and also seems to break the functionality since even by replacing withKnobs by withKnobsOptions doesn't work, now I get an error:

_Expecting a valid React element from the story: "foostory"_

**Comment by Gongreg** [comment] 2017-05-30 15:50
Hey, @leonidax  
I made that change. Sorry if it broke something, that means I made a mistake, since that update shouldn't have changed anything for current users. If you try to change withKnobs to previous definition, it works properly?

**Comment by leonidax** [comment] 2017-05-30 15:59
Yes it does, I replaced the storybook-addon-knobs.d.ts file with the previous revision in my node_modules and it works fine as before.

**Comment by Gongreg** [comment] 2017-05-30 16:26
@leonidax,
Thank you for checking it. Once again I am sorry. I will try to get this one working asap.

**Comment by leonidax** [comment] 2017-05-30 16:28
@Gongreg, 
Thanks :)

**Comment by Gongreg** [comment] 2017-05-30 17:36
@leonidax,
I made a PR, can you take a quick look if that will work? I don't know how to properly test it.

**Comment by tmeasday** [comment] 2017-05-30 23:02
Maybe it would help to get a simple reproduction of the story that highlights the problem?

**Comment by Gongreg** [comment] 2017-05-31 07:47
As I understand simply users using typescript and trying to use withKnobs were getting an error.

**Comment by leonidax** [comment] 2017-05-31 08:28
I downloaded the latest definition that you added in the PR and it's working.

**Comment by darekkay** [comment] 2017-05-31 16:56
I'm also having problems with knobs now showing after updating the package version to `3.0.0`. However, I get a different error(s):

```
WrapStory.js:74 Uncaught TypeError: Cannot read property 'removeListener' of null
    at WrapStory.componentWillUnmount (WrapStory.js:74)
```

and

```
KnobManager.js:111 Uncaught TypeError: Cannot read property 'emit' of null
    at KnobManager.js:111
```

Applying the PR didn't solve this problem.

After updating my code from `.addDecorator(withKnobs)` (as described in the [readme](https://github.com/storybooks/storybook/tree/master/addons/knobs#getting-started)) to `.addDecorator(withKnobsOptions)`, I get no errors - but the whole story doesn't load anymore.

**Comment by Gongreg** [comment] 2017-05-31 20:25
Hey, @darekkay,
It looks like addon fails to get channel inside storybook. 
I never had this issue while working on this addon.
Maybe you could create a small example which gets this error?

Also if you want to use withKnobsOptions you have to call it like this: 
```.addDecorator(withKnobsOptions(optionsObject))```.

But that will not change situation for you in this case..

**Comment by ndelangen** [comment] 2017-05-31 21:01
@darekkay Please remove all node_modules and reinstall. Check if there are any @kadira packages present after. I have a suspicion you're using some addons still dependent on @kadira/addons.

**Comment by darekkay** [comment] 2017-06-01 09:31
@Gongreg @ndelangen - Thanks for the quick reply! Removing and reinstalling `node_modules` solved the problem. I didn't have to apply the PR or change `withKnobs` to `withKnobsOptions`.

**Comment by Gongreg** [comment] 2017-06-01 09:43
@darekkay Thanks, good to know! Can the close the issue now? :)

**Comment by darekkay** [comment] 2017-06-01 13:05
Fine with me 👍

**Closed** 2017-06-01 13:08 UTC
Labels: addon: knobs, bug, needs reproduction
