### ISSUE TITLE
Upgrading to 5 results in `useBuiltIns` option without declaring a core-js version.

### ISSUE THREAD

**Issue by mohamedmansour** [storybooks/storybook#6261] opened 2019-03-25 18:00 UTC
When upgrading to v5, I get the following warnings:

    WARNING: We noticed you're using the `useBuiltIns` option without declaring a core-js version.

I fixed it by adding the following babel preset:

    ['@babel/preset-env', { useBuiltIns: 'usage', corejs: 2 }]

**Comment by felipe-norato-movile** [comment] 2019-03-25 20:09
Same problem,
Adding this property at `node_modules/@storybook/core/dist/server/common/babel.js` solved

**Comment by shilman** [comment] 2019-03-26 01:01
Anybody wanna put together  a small PR for this?

**Comment by mohamedmansour** [comment] 2019-03-26 01:12
@shilman  sure, I was gonna do it this morning but wanted to see if anyone else had the same issue

**Comment by shilman** [comment] 2019-03-26 01:13
@mohamedmansour Everybody who uses Storybook has it. It's another babel minor version upgrade doozy 😆

**Comment by shilman** [comment] 2019-03-26 03:20
Egads!! I just released https://github.com/storybooks/storybook/releases/tag/v5.1.0-alpha.15 containing PR #6267 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Closed by shilman** 2019-03-26 03:20 UTC
Labels: babel / webpack, bug, core

**Comment by shilman** [comment] 2019-04-01 04:50
Jiminy cricket!! I just released https://github.com/storybooks/storybook/releases/tag/v5.0.6 containing PR #6267 that references this issue. Upgrade today to try it out!

**Comment by ryancat** [comment] 2019-04-06 15:54
Upgrade to 5.0.6 and I am no longer seeing this issue. Thanks @shilman !

**Comment by pelotom** [comment] 2019-04-22 20:28
I'm seeing this issue in v4.1.18, does the fix need to be backported?

**Comment by shilman** [comment] 2019-04-22 21:53
@pelotom It might. I'll patch it back today!

**Comment by pelotom** [comment] 2019-04-22 22:02
@shilman I opened a PR [here](https://github.com/storybooks/storybook/pull/6579).

**Comment by shilman** [comment] 2019-04-22 22:29
Hmm. Actually the PR you duplicated was buggy and required a second PR to fix it, which changes some core dependencies https://github.com/storybooks/storybook/pull/6281

How important is it to get rid of this warning? On the one hand I appreciate that lots of people are stuck on 4.x. On the other hand, this is a bigger change than I would like for a patch release, and I'm tempted to say "upgrade to 5". But open to discussion.

**Comment by pelotom** [comment] 2019-04-22 22:55
@shilman I would be happy to upgrade but I've had issues with HMR on v5 that are preventing it... haven't had time to get it down to a minimal reproduction yet.
