### ISSUE TITLE
Function in props gets dropped when changing knob

### ISSUE THREAD

**Issue by ljowen** [storybooks/storybook#6162] opened 2019-03-19 03:30 UTC
**Describe the bug**
When trying to pass in an object containing a function selectable through a knob the function gets dropped. On initial render the value returned by the function is rendered, when a different option is selected the following error is shown:
```    TypeError: props.option.fn is not a function```

**To Reproduce**
See code snippet

**Expected behavior**
The function provided by the select option is not removed

**Code snippets**
```
import React from 'react';
import { storiesOf } from '@storybook/react';
import { select, withKnobs } from '@storybook/addon-knobs';

const selectOptions = {
  a: { fn: () => 1 },
  b: { fn: () => 2 },
  c: { fn: () => 3 }
};

const Wrapper = props => {
  return <pre>{props.option.fn()}</pre>;
};

storiesOf('Example', module)
  .addDecorator(withKnobs)
  .add('Default', () => {
    const option = select('Result Set: ', selectOptions, selectOptions.a);
    return <Wrapper option={option} />;
  });
```

**System:**
 - OS: MacOS
 - Device: Macbook Pro 2010
 - Browser: chrome
 - Framework: react
 - Addons: withKnobs, select
 - Version: 4.0.12

**Comment by mihaisavezi** [comment] 2019-03-19 15:32
Duplicate of #3977

**Closed** 2019-03-19 15:53 UTC
Labels: addon: knobs, question / support

**Comment by ljowen** [comment] 2019-03-20 05:48
I can see the relation to #3977 and why ```object```` knob serializes it's value but why would the options provided to ```select``` get serialized?
