### ISSUE TITLE
Support RN 0.43.x

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#849] opened 2017-04-15 15:41 UTC
<a href="https://github.com/xareelee"><img src="https://avatars2.githubusercontent.com/u/804308?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [xareelee](https://github.com/xareelee)**
_Thursday Apr 13, 2017 at 03:57 GMT_
_Originally opened as https://github.com/storybooks/react-native-storybook/issues/135_

----

After installing RN `0.43.x`, I got those warning using `yarn install`:

```
warning "@kadira/react-native-storybook@2.3.0" has incorrect peer dependency "react@^15.3.2".
warning "@kadira/react-native-storybook@2.3.0" has incorrect peer dependency "react-native@0.27.0 - 0.42.x".
```

RN `0.43.x` depends on react `16.0.0-alpha.6`. Is it possible to make react-native-storybook support RN `0.43x` and react `16.0.0-alpha.6`?

**Comment by ndelangen** [comment] 2017-04-15 20:48
Duplicate of https://github.com/storybooks/storybook/issues/893

**Closed by ndelangen** 2017-04-15 20:48 UTC
