### ISSUE TITLE
Default text and background are the same color on react native 0.58

### ISSUE THREAD

**Issue by ryanmagoon** [storybooks/storybook#5377] opened 2019-01-27 04:32 UTC
**Describe the bug**
In react native 58+, the default background color is black instead of white, and so the default UI theming that comes out of the box with storybook UI is invisible

**To Reproduce**
Follow the instructions to install storybook on a newly created react native project
`react-native init newProject`
`cd newProject`
`npx -p @storybook/cli sb init `

**Expected behavior**
Expected the default text color to not be the same as the background

**Screenshots**
<img width="475" alt="screen shot 2019-01-26 at 11 26 39 pm" src="https://user-images.githubusercontent.com/5327290/51796502-7ada2700-21c2-11e9-817f-2bba9b7b5688.png">

**Code snippets**
adding this to the style file for the preview list component shows the ui
```
flex: {
    backgroundColor: 'white',
    flex: 1
  },
```
<img width="449" alt="screen shot 2019-01-26 at 11 26 46 pm" src="https://user-images.githubusercontent.com/5327290/51796505-8decf700-21c2-11e9-8bed-9fbf92335e18.png">

**System:**
 - MacOS
 - Device: Macbook pro 2015
 - Framework: react native
 - Version: 4.1.11

**Comment by kdenz** [comment] 2019-02-06 16:32
For me I realized it's caused by this line in `AppDelegate.m` for 0.58.x
It becomes
```  rootView.backgroundColor = [UIColor blackColor];```
from previously
```  rootView.backgroundColor = [[UIColor alloc] initWithRed:1.0f green:1.0f blue:1.0f alpha:1];```

Now I changed it to 
```  rootView.backgroundColor = [UIColor whiteColor];```
and it defaults to white again

**Comment by fo-fo** [comment] 2019-03-24 09:35
Non-intrusive workaround is to wrap the `StorybookUIRoot` component inside a `View` with its background color set to white:

```jsx
const WrappedStorybook = () => (
  <View style={{ flex: 1, backgroundColor: "white" }}>
    <StorybookUIRoot />
  </View>
);
```

**Comment by kaiwen-zhang-ck** [comment] 2019-04-02 23:59
what a hack. is there official issue to change this? why is default black?

**Comment by shilman** [comment] 2019-04-03 01:11
This has been fixed in https://github.com/storybooks/storybook/releases/tag/v5.1.0-alpha.19
by https://github.com/storybooks/storybook/pull/6315

**Closed by shilman** 2019-04-03 01:11 UTC
Labels: app: react-native, bug, has workaround
