### ISSUE TITLE
Could not run tests exit with "dataId is not supplied via queryString"

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#883] opened 2017-04-15 17:39 UTC
<a href="https://github.com/felquis"><img src="https://avatars3.githubusercontent.com/u/736728?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [felquis](https://github.com/felquis)**
_Sunday Jan 29, 2017 at 06:03 GMT_
_Originally opened as https://github.com/storybooks/storyshots/issues/77_

----

How to reproduce
```
git clone git@github.com:felquis/webpack.git
```
Then install deps `yarn`

Run `yarn test` then you will see.
![screen shot 2017-01-29 at 3 57 39 am](https://cloud.githubusercontent.com/assets/736728/22402279/c8fd783e-e5d7-11e6-9c9e-dddd239732c5.png)

Im not sure what is going on.

**Comment by shilman** [comment] 2017-04-15 17:39
<a href="https://github.com/botteu"><img src="https://avatars3.githubusercontent.com/u/164277?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [botteu](https://github.com/botteu)**
_Thursday Mar 30, 2017 at 08:47 GMT_

----

I have the same problem. I don't know where to look…

**Comment by dezoxel** [comment] 2017-04-20 12:02
@shilman @arunoda, I've found that having `.babelrc`causes this issue. I've remove it and everything worked fine.

**Comment by dezoxel** [comment] 2017-04-20 12:04
@arunoda Here is my config that causes an issue:

```
{
  "presets": ["react-app"],
  "plugins": [
    [
      "react-intl", {
        "messagesDir": "src/i18n/extractedMessages",
        "enforceDescriptions": false
      }
    ]
  ]
}
```

Any ideas of how to fix the original issue but also keep my custom `.babelrc`?

**Comment by xavcz** [comment] 2017-04-20 12:34
Does placing `.babelrc` in `.storybook` folder solves the problem?

**Comment by dezoxel** [comment] 2017-04-20 14:13
@xavcz Well, I believe I was wrong with my assumption about `.babelrc`, because when I deleted my `node_modules` folder and installed everything from scratch (`npm i`) and eventually the issue reproduced again, even without `.babelrc`.

**Comment by dezoxel** [comment] 2017-04-20 14:16
Eventually I was able to resolve this issue. My steps:
1. Updated`@kadira/storybook` from `2.21.0` to `2.35.3`
2. Removed `react-storybook": "1.0.0"`
3. `rm -rf node_modules && npm i`

**Comment by tmeasday** [comment] 2017-05-31 00:56
Confirmed that updating to v3 (via `getstorybook`) resolves the issue. Closing. Thanks @dezoxel!

**Closed by tmeasday** 2017-05-31 00:56 UTC
Labels: addon: storyshots, bug
