### ISSUE TITLE
Change template for storybook generation

### ISSUE THREAD

**Issue by vvscode** [storybooks/storybook#3800] opened 2018-06-26 11:43 UTC
Is it possible to change the template ( except header/preview header)? reorganize menu / add custom footer etc.

Thanks in advance (I believe it's quite common request)

**Comment by igor-dv** [comment] 2018-06-27 16:16
It's a duplicate of #3696 (I assume that there are much more duplications). Closing this one since it's the newest.

**Closed** 2018-06-27 16:16 UTC
Labels: question / support
