### ISSUE TITLE
action is not sending output to action panel (3.0.0-rc2)

### ISSUE THREAD

**Issue by smiket** [storybooks/storybook#1153] opened 2017-05-29 21:52 UTC
Hi,
Thank you for such an excellent tool!  I wanted to let you know that after installing 3.0.0-rc2, my actions are not sending output to the action panel.  I rimraf'd node_modules to clean everything, then did npm i followed by npm start storybook.  Perhaps I have something misconfigured (was all working when I was using kadira/storybook):

In my package.json:

    "devDependencies": {
        "@storybook/addon-actions": "^3.0.0-alpha.0",
        "@storybook/addon-comments": "^3.0.0-alpha.0",
        "@storybook/addon-info": "^3.0.0-alpha.0",
        "@storybook/react": "^3.0.0-alpha.0",

In my config.js:

    import infoAddon from "@storybook/addon-info";
    setAddon(infoAddon);

In my story:

    import { action } from "@storybook/addon-actions";
    export default storiesOf('EseButton', module)
        .addWithInfo('Enabled', () => (
            <EseButton name="ese-button" onClick={action('button-click')}>
               <span>ESE Button</span>
            </EseButton>
        ));

Everything works as expected, except I do not get output in the action logger.
Let me know if you'd like more information - 

Thank you,
Steve

**Comment by shilman** [comment] 2017-05-29 22:10
@smiket Hi Steve, Is the repro public? If so I can take a look!nIf not, does it work with you register the addons in `.storybook/addons.js`?

NOTE: I tried to repro myself, but `addon-actions` is working for me:
```
  505  yarn create react-app testapp
  506  cd testapp/
  507  yarn add getstorybook
  508  ./node_modules/.bin/getstorybook 
```
Then upgrade by hand according to `MIGRATION.md`

**Comment by dangreen** [comment] 2017-05-30 06:10
I'm also have this issue.
It seems that the problem is in styles:
![display: none](https://puu.sh/w5gRP/f990686510.png)
![display: block](https://puu.sh/w5gRJ/0d513955d2.png)

**Comment by leonidax** [comment] 2017-05-30 15:51
I also have the same issue, I don't get the action in the logger

**Comment by smiket** [comment] 2017-05-30 18:46
@shilman I updated to the released version (3.0) and everything started working for me.  Initially it did not show messages, but I happened to click the link button in the action-logger panel and messages started to display.  Not sure if the click had anything to do with it, but all is working for me.  Thanks again for following up with me on this - I'm all set now.

**Comment by dangreen** [comment] 2017-05-31 03:39
@shilman nope

**Comment by shilman** [comment] 2017-05-31 06:37
@dangreen do you have a public example i could look at?

**Comment by dangreen** [comment] 2017-06-01 08:32
@shilman suddenly now all works&

**Comment by shilman** [comment] 2017-06-01 09:13
@dangreen 

![magic](https://cloud.githubusercontent.com/assets/488689/26672913/1271115e-470f-11e7-818a-14a842e6f08e.gif)

**Comment by leonidax** [comment] 2017-06-01 11:30
Well I still have the problem but it might be only a typescript problem.

**Comment by shilman** [comment] 2017-06-01 11:55
@leonidax do you have a public repo I could look at?

**Comment by leonidax** [comment] 2017-06-01 13:03
Sure, the same example that I posted in the typescript issue ticket:

[https://github.com/leonidax/storybook-ts-less-example](https://github.com/leonidax/storybook-ts-less-example)

**Comment by shilman** [comment] 2017-06-01 13:33
@leonidax there was a bug in the code. try:

```ts
            <Button settings={{title: "?" , callback: action("hello")}}/>
```

I'm going to close this for now, but feel free to reopen if you have more issues on this!

**Closed by shilman** 2017-06-01 13:33 UTC
Labels: addon: actions, question / support

**Comment by leonidax** [comment] 2017-06-01 14:53
I see thanks :)

**Comment by nathancahill** [comment] 2017-06-05 16:40
Oh jeez, just wasted a couple hours debugging this after upgrading. Actions don't show up until you click "Action Logger" in the pane. storybook/addon-actions and storybook/react versions 3.0.1.

**Comment by shilman** [comment] 2017-06-06 08:47
Sorry to hear it @nathancahill. Can you explain the problem in more detail?

**Comment by nathancahill** [comment] 2017-06-06 15:41
Well, it seemed like a CSS issue. However, after wiping node_modules are reinstalling all dependencies, the issue has gone away. So maybe a conflicting storybook file from before.

**Comment by rkoberg** [comment] 2017-09-07 17:13
**_
> Oh jeez, just wasted a couple hours debugging this after upgrading. Actions don't show up until you click "Action Logger" in the pane.
_**
Ufff... add this to the docs. There is no indication that you need click what looks like the title to the actions pane to see actions show up

**Comment by Hypnosphi** [comment] 2017-09-07 21:41
If the actions tab is empty unless you click to its title, it’s a bug

@rkoberg do you have any other addon tabs? Can you take a screenshot of your storybook page when it shows action logger without actions?

**Comment by rkoberg** [comment] 2017-09-07 22:11
When this happened, the Actions Logger was the only tab. In other words there is no clicking around. Now that I have multiple tabs, I don't see the behavior. The Actions Logger was the first one I tried. Was banging my head why nothing would show. When I saw the post above (that I quoted using bold for some reason), I clicked the title/tab and actions started to show.

**Comment by michaellee8** [comment] 2017-09-16 16:08
I have this issue as well. I have tried clicking "ACTION LOGGER" button but still nothing shown. I decided to use `console.log` and `action` in the same time, but only `console.log` show the result but `action` results in nothing.
![screenshot from 2017-09-17 00-07-40](https://user-images.githubusercontent.com/16556558/30513819-4c641e66-9b3c-11e7-908e-c295153f1536.png)

**Comment by cuzzins** [comment] 2017-11-03 19:25
Having same issue with a VUE based project, just installed and totally clean and using the demo files.  Clicking the button does nothing. No errors in the console either.

**Comment by andrerpena** [comment] 2018-03-08 14:50
Having this problem with React now

**Comment by patrickmcelwee** [comment] 2018-03-08 21:50
The problem seems to be when &addOnPanel is the final url param and the page is loaded. An extra slash is being appended to the URL.

I believe it is most likely caused when running python -m SimpleHTTPServer. I get this error when running python 2.7.5. I do not get it with python 2.7.13. I believe it is most likely caused by this issue: https://bugs.python.org/issue23112, which was resolved at some point in the 2.7 series.

**Comment by patrickmcelwee** [comment] 2018-03-08 21:57
A workaround is either to upgrade Python or, in case you can't, as I can't on a RHEL Linux server, use one of these methods for a simple HTTP server instead: https://gist.github.com/willurd/5720255

I'd suggest closing this ticket, and possibly replacing SimpleHTTPServer with an alternative in the documentation.

**Comment by Fatal1stZ** [comment] 2018-06-20 07:59
i got this error aswell,
i'm starting storybook via npm and action logger doesn't work
installed python 2.7.13 but it didnt help
any idea why plugin not working?
```
    "@storybook/addon-actions": "^3.4.6",
    "@storybook/cli": "^3.4.6",
    "@storybook/react": "^3.4.6",
```

**Comment by adyz** [comment] 2018-07-02 09:09
Actions don't work for me neither...

    "@storybook/addon-actions": "^3.4.8",
    "@storybook/react": "^4.0.0-alpha.10",
    "react": "^16.4.1",
   "react-dom": "^16.4.1",
    "ts-loader": "^4.4.1",

**Comment by lcampanis** [comment] 2018-08-26 15:34
Also facing this issue, with no actions being logged.

package.json
```bash
    "@babel/cli": "7.0.0-beta.49",
    "@babel/core": "7.0.0-beta.49",
    "@babel/node": "7.0.0-beta.49",
    "@babel/plugin-proposal-object-rest-spread": "7.0.0-beta.49",
    "@babel/preset-env": "7.0.0-beta.49",
    "@babel/preset-es2015": "7.0.0-beta.49",
    "@babel/preset-react": "^7.0.0-beta.49",
    "@babel/preset-stage-2": "7.0.0-beta.49",
    "@reactioncommerce/eslint-config": "1.8.0",
    "@storybook/addon-actions": "^4.0.0-alpha.16",
    "@storybook/addon-centered": "^4.0.0-alpha.16",
    "@storybook/addon-knobs": "^4.0.0-alpha.16",
    "@storybook/addon-links": "^4.0.0-alpha.16",
    "@storybook/addon-options": "^4.0.0-alpha.16",
    "@storybook/addon-viewport": "^4.0.0-alpha.16",
    "@storybook/addons": "^4.0.0-alpha.16",
    "@storybook/react": "^4.0.0-alpha.16",
    "babel-bridge": "^1.12.11",
    "babel-core": "^6.26.3",
```

addon.js
```
import '@storybook/addon-actions/register';
import '@storybook/addon-links/register';
import '@storybook/addon-options/register';
import '@storybook/addon-knobs/register';
import '@storybook/addon-viewport/register';
```

**Comment by yeou** [comment] 2018-12-17 12:54
I'm seeing the same as @fadomire. Is this correct? Should we update the documentation?

**Comment by acnebs** [comment] 2019-03-12 01:30
I actually bumped into this issue because my MetaMask extension was intercepting the `action` calls for some reason. Removed MetaMask and action logs started showing up in the action panel.

**Comment by Jack-Barry** [comment] 2019-06-13 12:18
I ran into this on `5.0.11`, the fix proposed by @fadomire worked, doesn't even need a parameter just need to call the function.

```ts
action('Button was clicked')()
```

**Comment by Hypnosphi** [comment] 2019-06-14 17:42
@fadomire @Jack-Barry can you please share the particular code examples? The result of calling `action(name)` is indeed a function, and the docs assume that you pass it as an event handler

**Comment by Jack-Barry** [comment] 2019-06-14 21:09
```ts
import { storiesOf, Story } from '@storybook/vue'
import { action } from '@storybook/addon-actions'

// @ts-ignore
import MyButton from './MyButton.vue'

const stories: Story = storiesOf('Buttons/MyButton', module)

stories.add(
  'Default',
  () => ({
    components: { MyButton },
    methods: {
      logAction() {
        // action('Button was clicked') <- This doesn't work
        action('Button was clicked')()  // This does
      }
    },
    template: `
      <my-button @click="logAction">
        Click Me
      </my-button>`
  })
)
```
I don't have this project running on the computer I'm at, but the output in the action panel shows `'Button was clicked': []` when calling `action('Button was clicked')()` if I remember correctly.

**Comment by Hypnosphi** [comment] 2019-06-15 11:10
@Jack-Barry `methods: {logAction: action('Button was clicked')}` should work as well

**Comment by Jack-Barry** [comment] 2019-06-17 14:35
That does work, guess I just overlooked the slight difference in how the functions in `methods` are declared when using `action`, since typically I declare functions in `methods` along the lines of

```js
...
methods: {
  someFunction(someParam) {
    // does things with someParam
  }
}
...
```

Thanks for pointing that out @Hypnosphi!

**Comment by yog3sha** [comment] 2020-10-28 11:42
> @Jack-Barry does the following work?
> 
> ```
> ...
> methods: {logAction: action('Button was clicked')}
> ...
> ```
> 
> That's how it's used in [official vue examples](https://storybooks-vue.netlify.com/?path=/story/addon-actions--action-only)

This works for me too. It is almost end of 2020 and sadly still official docs lacks enough examples with vue + TS. Disappointed!

**Comment by vmnog** [comment] 2022-03-23 21:06
For me I solved the problem by removing the implementation in my `Template.bind({}).args`
I setup my storie like that:

```typescript
// button.stories.ts
export default {
  argTypes: {
      onClick: { action: 'clicked' },
    }
}
...
interface ArgTypes {
  onClick?(e: Event): void;
}
...
// In my case I'm building a design system with Lit and OpenWC, but you get the idea
const Template: Story<ArgTypes> = ({ onClick }: ArgTypes) => html`
  <button-component @click=${onClick}></button-component>
`;
...
export const Default = Template.bind({});

Default.args = {
  onClick: (e) => { console.log(e) } // <-- ❗Remove this implementation, it's overriding the ArgType Action Handler
};
```

After removing the `Default.args.onClick` implementation in the `button.stories.ts` it worked.
