### ISSUE TITLE
3.3.0-alpha.4 `preview-head` does not work with a custom configDir

### ISSUE THREAD

**Issue by Skovy** [storybooks/storybook#2501] opened 2017-12-18 03:21 UTC
### Issue details

On `3.3.0-alpha.4`, we use a custom config directory (`frontend/.storybook`). This works on `3.2`, but is broken on `3.3.0-alpha.4`. This appears to be fixed on `master` but not `release/3.3`. It appears the ENV var is always undefined:

https://github.com/storybooks/storybook/blob/3c1715dacaf95a789e4e024cdb1e8993bf3ada9b/app/react/src/server/config/utils.js#L37

### Steps to reproduce

Add a custom config directory (`start-storybook -c frontend/.storybook -p 6006`), with a `preview-head.html` file in the config directory (`frontend/.storybook/preview-head.html`).

### Temporary Solution

I was able to work around this issue for the time being by adding this config var:

`SBCONFIG_CONFIG_DIR=frontend/.storybook start-storybook -c frontend/.storybook -p 6006`

### Please specify which version of Storybook and optionally any affected addons that you're running

- `@storybook/react`@`3.3.0-alpha.4`

### Affected platforms 

- All.

**Comment by shilman** [comment] 2017-12-27 06:34
I'm able to reproduce this exactly as described here by @Skovy. Looking into a fix.

cc @danielduan

**Comment by samouss** [comment] 2017-12-27 09:07
The issue seems to come from the fact that in the `webpack.config` the `configDir` is always read from the `ENV` instead of coming from the program (see [config/webpack.config.js#L37-L53](https://github.com/storybooks/storybook/blob/master/app/react/src/server/config/webpack.config.js#L37-L53)). If you follow the call to `getConfigDir` you will see that the function always read the `configDir` from the `ENV` or the default one (see [config/utils.js#L37](https://github.com/storybooks/storybook/blob/79c07c727a2f5eedf34502df4207d7a6527fedf0/app/vue/src/server/config/utils.js#L37)). 

Since the `webpack.config` is a function we can probably pass the configuration directory as argument and get rid of the `getConfigDir` function. The `webpack.config` function is called from the middleware module (see [server/middleware.js](https://github.com/storybooks/storybook/blob/master/app/react/src/server/middleware.js#L20)), we have access to the `configDir` variable so we can pass it as argument. Not sure of the implication, but I tried and it works. Happy to send a PR if you think that is a viable solution 🙂

**Comment by shilman** [comment] 2017-12-28 02:34
@samouss I have also tried this fix out and have something basic working, but don't understand the implications of the fix. If you could put together a PR and we can get other people on the team to comment, that would be really awesome!!

**Comment by danielduan** [comment] 2017-12-28 02:40
I'm quite confused as to why this was working before and not anymore. I think there might be a PR somewhere to enable configuration via environment variables.

**Comment by samouss** [comment] 2017-12-28 08:31
It seems that a recent change introduce the `HtmlWebpackPlugin` for generate both manager & iframe html files. Previously they was generate in the `build.js` file where the `configDir` was available in the current scope (see https://github.com/storybooks/storybook/commit/f42248157b3cf9b49de98ea9bca1f88495d6d58a#diff-ba110c4fe305160aa94df6d17e4235dcL102).

But now they are generated form the `webpack.config.js` file where `configDir` is not available. So the function `getConfigDir` has been created and that's where the problem come from (see https://github.com/storybooks/storybook/commit/f42248157b3cf9b49de98ea9bca1f88495d6d58a#diff-917756e90ff65c053bce52389df3c81bR49).

> https://github.com/storybooks/storybook/pull/1775

**Comment by shilman** [comment] 2018-01-06 05:36
@samouss Any progress on a PR for this?

**Comment by samouss** [comment] 2018-01-06 13:25
Nope, I don't have the time to work on it yet. But I hope I will have it in the coming days!

**Comment by shilman** [comment] 2018-01-07 01:01
Fixed in #2666

**Comment by Hypnosphi** [comment] 2018-01-07 13:45
Fix released as [`3.3.4`](https://github.com/storybooks/storybook/releases/tag/v3.3.4)

**Closed by Hypnosphi** 2018-01-07 13:45 UTC
Labels: app: react, bug, high priority, todo
