### ISSUE TITLE
Separate snapshots into the folders close to each story

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#887] opened 2017-04-15 17:39 UTC
<a href="https://github.com/xareelee"><img src="https://avatars2.githubusercontent.com/u/804308?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [xareelee](https://github.com/xareelee)**
_Wednesday Mar 15, 2017 at 08:06 GMT_
_Originally opened as https://github.com/storybooks/storyshots/issues/84_

----

Currently, the `.snap` files generated by storyshots will be put in the `__snapshots__` folder where the `Storyshots.test.js` is.

```
snapshots/
  ┣━ Storyshots.test.js   // run for storyshots
  ┗━ __snapshots__       // current we put snapshots for storyshots in this folder
          ┗━ Storyshots.test.js.snap    // we should separate the snapshots to be close to the .stories file
```

This results in a huge `.snap` file with thousands lines of code. It's hard for code review. 

I think that the snapshots should be put in the  `__snapshots__` folder being close to the related `.stories`.

```
src/components/
  ┗━ SomeComponent   // for import
          ┣━ index.js                                // to export the component
          ┣━ SomeComponent.js              
          ┣━ SomeComponent.styles.js   
          ┣━ SomeComponent.stories.js  // Storybooks
          ┗━ __snapshots__                       // we should put .snap files here for storyshots
                 ┗━ Storyshots.test.js.snap // generated by Storyshots.test.js  (should put it here)
```

This will make code review easier. It's easy to know a change from which `.stories.js` file.

It would be better when we need to move the whole component folder into a separated module or project without losing its snapshots, doesn't it?

**Comment by tmeasday** [comment] 2017-05-15 09:38
I think it would be best if we could make Jest consider the story tests as coming from the story file as opposed to the `Storyshots.test.js` file (I think this would have the side-effect of solving this problem).

Does anyone know of a way to alter the location that Jest considers a test as coming from?

**Comment by orta** [comment] 2017-05-29 21:02
Well I just looked through the source code and there _is_ a [private, but accessible API](https://github.com/facebook/jest/blob/master/packages/jest-matchers/src/index.js#L288) you could abuse:

e.g. 

```js
const thisTestPath = expect.getState("testPath")
expect.setState("testPath", "path/to/story")
runStoryshot()
expect.setState("testPath", thisTestPath)
```

/cc @cpojer

**Comment by tmeasday** [comment] 2017-05-30 04:45
@orta have you tried messing with that? I gave it a go but it didn't seem to affect things. Reading the source code a bit, it seems like reading the snapshots is done per-test-file at startup time: https://github.com/facebook/jest/blob/9b157c3a7c325c3971b2aabbe4c8ab4ce0b0c56d/packages/jest-jasmine2/src/setup-jest-globals.js

This implies to me that "fooling" jest into thinking a single test file (like so: https://github.com/storybooks/storybook/blob/master/examples/test-cra/src/storyshots.test.js) is providing tests for multiple files isn't really going to work. I could be wrong though.

Maybe a better way forward is rather than storyshots reading all the stories in, *and then* looping over the stories, setting up a test for each story, it could instead hook into the `.add()` behaviour, so that if you `.add` a story and Jest globals are defined, it creates a test at "add time".

I've no idea if the above would work, I'm just noting it down as something to investigate help with this issue.

**Comment by ndelangen** [comment] 2017-07-07 18:34
I think you're onto something there @tmeasday.

You could use jest mocking to facade storybook's `storyriesOf()` &  `.add` into `describe()` & `.it()`!

**Comment by tmeasday** [comment] 2017-07-10 01:34
Yeah, that's my thinking. Pretty much the exact opposite to what https://www.npmjs.com/package/jest-storybook-facade does.

**Comment by ndelangen** [comment] 2017-07-10 09:21
Would be a real big improvement for storyshots if you ask me!

**Comment by igor-dv** [comment] 2017-08-02 06:07
Hey, I've created an [experimental jest matcher](https://github.com/igor-dv/jest-specific-snapshot#example) that will probably help here..  Will try to have a working demo with storyshots soon.

**Comment by ndelangen** [comment] 2017-08-02 08:32
Wow cool! @igor-dv! I was talking with @kentcdodds, this came up as well! 

Although there was a misconception Storyshots was outputting as 1 big snapshot (which it is NOT). It outputs all snapshots individually into 1 file.

We're hoping to find a way to store the snapshots near the sourcefiles.

Looking forward to seeing your proposal @igor-dv, You're on a roll!

**Comment by tmeasday** [comment] 2017-08-02 10:51
Oh, that's really interesting @igor-dv! Let's give it a try!!

**Comment by igor-dv** [comment] 2017-08-02 11:54
So far

![storyshots-example](https://user-images.githubusercontent.com/7867954/28872506-2c85f682-7792-11e7-8a15-cfb373be6ea3.gif)

**Comment by xareelee** [comment] 2017-08-19 02:54
By the way, we should avoid to update a gigantic file frequently using git.

My current `Storyshots.test.js.snap` file is a size of 1.1 MB, and my git repo is going big as the project goes on.

**Comment by igor-dv** [comment] 2017-08-27 21:21
Should it be marked as merged if it's merged to the release branch ?

**Comment by tmeasday** [comment] 2017-08-27 23:48
Not sure. I guess so, so people know it is solved?

**Comment by xareelee** [comment] 2017-08-28 02:26
Has it been released? When or how can I start to use this nice feature? 😄

**Comment by tmeasday** [comment] 2017-08-28 02:53
Hi @xareelee -- we'll do a 3.3 alpha soon, you can try installing that.

**Comment by Hypnosphi** [comment] 2017-11-28 22:05
Works in `3.3.0-alpha.4`

**Closed by Hypnosphi** 2017-11-28 22:05 UTC
Labels: addon: storyshots, compatibility with other tools, feature, help wanted, merged

**Comment by sashless** [comment] 2018-01-10 11:36
Using "multiSnapshots" the package https://github.com/styled-components/jest-styled-components stopped working. I guess the problem is that the method to change the serializer changed as the result snapshot is missing all the styles.

**Comment by igor-dv** [comment] 2018-01-10 12:33
@sashless , can you please try adding this serializer to 'jest-specifics-snapshot' directly ?

```js
  import { addSerializer } from 'jest-specifics-snapshot';

  addSerializer(styleSheetSerializer);
```

(`jest-specifics-snapshot` is used in Storyshots)

**Comment by greggb** [comment] 2018-01-10 18:18
Yes! This fixed my serializer issue @igor-dv 

The package is` jest-specific-snapshot` without the `s` on specific, btw

**Comment by igor-dv** [comment] 2018-01-10 19:23
@greggb , cool !
BTW, @brentmclark, @zvictor we talked earlier [here](https://github.com/storybooks/storybook/pull/1584#issuecomment-350348274) about exposing the `addSerializer` from Storyshots. Do you think we still need to do it? Or this solution is good enough?

**Comment by sashless** [comment] 2018-01-11 08:36
@igor-dv thanks, works for me too 👍

**Comment by sashless** [comment] 2018-01-11 08:52
@igor-dv I replaced the line `expect.addSnapshotSerializer(styleSheetSerializer)` with your proposal inside the plugin i mentioned but it did not fix the issue

**Comment by sashless** [comment] 2018-01-11 16:32
I created a repo to show the problem https://github.com/sashless/storyshot-styled-components-with-multisnapshots-broken @igor-dv

**Comment by igor-dv** [comment] 2018-01-11 21:55
You didn't really add custom serializer in your example. Here is how it should look like.

```js
import initStoryshots, { multiSnapshotWithOptions } from '@storybook/addon-storyshots';
import styleSheetSerializer from 'jest-styled-components/src/styleSheetSerializer';
import { addSerializer } from 'jest-specific-snapshot'

addSerializer(styleSheetSerializer);

initStoryshots({
    suite: 'FileProperties',
    test: multiSnapshotWithOptions({}),
});
```

`jest-specific-snapshot` is used in multiSnapshotWithOptions. If you want to add a custom serializer you need to add it directly there.

**Comment by sashless** [comment] 2018-01-12 08:15
awesome, thanks @igor-dv

**Comment by brentmclark** [comment] 2018-01-24 05:08
I'm a little late to the party, @igor-dv; sorry for the slow response.

My preference is for more control, but I willing to try without `addSerializer` if you're on the fence about exposing it.

**Comment by Braden1996** [comment] 2018-04-16 23:47
Hey everyone!

I'm struggling to get this working :( Any advice as to what I am doing wrong?
**Storyshots.test.ts**
```js
import initStoryshots, {
  multiSnapshotWithOptions
  // @ts-ignore
} from '@storybook/addon-storyshots';

// @ts-ignore
import styleSheetSerializer from 'jest-styled-components/src/styleSheetSerializer';

import { addSerializer } from 'jest-specific-snapshot'

addSerializer(styleSheetSerializer);

initStoryshots({
  test: multiSnapshotWithOptions({})
});
```

**Error message:**
```
  ● Storyshots › atoms/tags/Button › basic Button

    TypeError: Cannot read property 'test' of undefined
      at findPlugin (node_modules/pretty-format/build/index.js:214:22)      at prettyFormat (node_modules/pretty-format/build/index.js:328:22)      at Object.toMatchSpecificSnapshot (node_modules/jest-specific-snapshot/dist/index.js:52:10)      at Object.throwingMatcher [as toMatchSpecificSnapshot] (node_modules/expect/build/index.js:147:24)      at match (node_modules/@storybook/addon-storyshots/dist/test-bodies.js:25:22)      at node_modules/@storybook/addon-storyshots/dist/test-bodies.js:39:12      at node_modules/@storybook/addon-storyshots/dist/test-bodies.js:48:40      at Object.<anonymous> (node_modules/@storybook/addon-storyshots/dist/index.js:120:20)
```

**Comment by Braden1996** [comment] 2018-04-17 08:32
Fixed! Nothing fresh morning eyes couldn't solve 🤪
I needed to import like this:
```js
import * as styleSheetSerializer from 'jest-styled-components/src/styleSheetSerializer';
```

**Comment by SteffenGorenflo** [comment] 2018-07-12 09:24
Right now, all the screenshots are saved in only one folder ``__image_snapshots__`` at the same level where ``Storyshots.test.js`` is located.

Currently: 
```
src/components/
  ┗━ __image_snapshots__  // Global image snapshot folder, which should be split and saved in each component folder separately
  ┗━ Storyshots.test.js  
  ┗━ SomeComponent  
          ┣━ SomeComponent.jsx              
          ┣━ SomeComponent.css
          ┣━ SomeComponent.stories.js 
          ┗━ __snapshots__                       
                 ┗━ SomeComponent.test.js.snap
```
But we like to have a ``__image_snapshots__`` folder in each component folder - just like the ``__snapshots__`` folder.

```
src/components/
  ┗━ Storyshots.test.js  
  ┗━ SomeComponent  
          ┣━ SomeComponent.jsx              
          ┣━ SomeComponent.css
          ┣━ SomeComponent.stories.js 
          ┗━ __image_snapshots__   // move folder here with screenshots only of this component
          ┗━ __snapshots__                       
                 ┗━ SomeComponent.test.js.snap
```

**Comment by igor-dv** [comment] 2018-07-12 15:05
You can possible use [this](https://github.com/storybooks/storybook/tree/master/addons/storyshots/storyshots-puppeteer#specifying-options-to-jest-image-snapshots) to customize the options passed to [`toMatchImageSnapshot`](https://github.com/americanexpress/jest-image-snapshot#optional-configuration)

**Comment by SteffenGorenflo** [comment] 2018-07-19 14:51
Ah yes, thank you! Works perfectly 👍

**Comment by Stupidism** [comment] 2019-04-29 06:39
> You didn't really add custom serializer in your example. Here is how it should look like.
> 
> ```js
> import initStoryshots, { multiSnapshotWithOptions } from '@storybook/addon-storyshots';
> import styleSheetSerializer from 'jest-styled-components/src/styleSheetSerializer';
> import { addSerializer } from 'jest-specific-snapshot'
> 
> addSerializer(styleSheetSerializer);
> 
> initStoryshots({
>     suite: 'FileProperties',
>     test: multiSnapshotWithOptions({}),
> });
> ```
> 
> `jest-specific-snapshot` is used in multiSnapshotWithOptions. If you want to add a custom serializer you need to add it directly there.

Your solution helped me a lot.

Here comes another problem. Storyshots does not re-run after stories update anymore. It seems to be solved before in https://github.com/storybooks/storybook/issues/2936#issuecomment-416057127
