### ISSUE TITLE
'Unhandled promise rejection' for first time loading of Storybook in React Native

### ISSUE THREAD

**Issue by jangnezda** [storybooks/storybook#5361] opened 2019-01-24 12:36 UTC
**Describe the bug**
When an app tries to load the Storybook for the first time, it fails with 'Unhandled promise rejection'. If error is dismissed, the Storybook's UI loads with the stories in the Navigator, however the Preview is empty. Then, if I reload the app, the exception doesn't happen, i.e. everything works normally.

This seems to be linked to how the Storybook loads initially selected story. The first time the app runs there's no information of the story selection, so it fails. If the error is dismissed and I click a story, then this selection is stored and running next time, storybooks succeeds loading the selected story. More specifically, I think the [_getInitialStory function](https://github.com/storybooks/storybook/blob/30144da395c2d2cfebdf8fb3029872a06369cc96/app/react-native/src/preview/index.js#L154) should be looked at to fix this problem.

**To Reproduce**
1. Follow [the guide](https://storybook.js.org/basics/guide-react-native/) to add Storybook to your React Native project
2. Start the android emulator
3. Run `react-native run-android` to build and deploy app to the emulator
4. Open Storybook  (depends on how you implemented the Storybook loading from your app - button press, gesture, option in the developer menu, ...)

**Expected behavior**
Storybook should load without errors when the app runs for the first time.

**Screenshots**
![rec3](https://user-images.githubusercontent.com/554544/51678553-f8dcd900-1fdc-11e9-9c6c-7e6c1739cefd.gif)

**Code snippets**
Workaround is to set the initial story selection. I had to change following code:
```js
import {
  getStorybookUI,
  configure,
} from '@storybook/react-native';

configure(() => {
  require('@components/__stories__');
});

const StorybookUIRoot = getStorybookUI({
  onDeviceUI: true,
  disableWebsockets: true,
});
```

to:
```js
import {
  getStorybookUI,
  configure,
  getStorybook,
} from '@storybook/react-native';

configure(() => {
  require('@components/__stories__');
});

const initialStory = getStorybook()[0];

const StorybookUIRoot = getStorybookUI({
  onDeviceUI: true,
  disableWebsockets: true,
  initialSelection: {
    kind: initialStory.kind,
    story: initialStory.stories[0].name,
  },
});
```

**System:**
 - OS: MacOS Mojave
 - Device: Macbook Pro 2018
 - Browser: Android emulator, avd=Nexus 5x (api level=28)
 - Framework: React Native 0.57.7
 - Version: @storybook/react-native 4.1.7

**Comment by jangnezda** [comment] 2019-01-25 08:09
Note to anyone looking at the workaround I've described above: it's pretty bad hack, because it will always revert to the first story when hot reloading.

**Comment by Gongreg** [comment] 2019-01-30 10:40
Hey, @jangnezda. I think AsyncStorage.getItem may be the root cause here. Could you wrap it in try catch and try it out?

**Comment by jangnezda** [comment] 2019-01-30 12:51
Yes, `AsyncStorage.getItem()` is indeed the root cause. Or more precisely, `AsyncStorage` returns null and the next line that tries to json parse throws exception. So it's just a matter of adding an `if` that checks the result of `AsyncStorage.getItem()` call.

**Comment by Gongreg** [comment] 2019-01-30 13:06
Maybe you could create a pull request for that fix? :)

**Comment by jangnezda** [comment] 2019-01-30 13:21
ACtually, looking at transpiled code in the `dist` directory, it looks like the problem is neither in `AsyncStorage.getItem()` nor in subsequent `JSON.parse()`. They both handle null just fine. A few lines after that there is a call to `_checkStory()` function and that one somehow triggers error:
```
'Unhandled promise rejection', { [TypeError: undefined is not a function (evaluating '_iterator[typeof Symbol === "function" ? Symbol.iterator : "@@iterator"]()')]
```

This will sound crazy, but if I comment out `console.warn()` in `@storybook/react-native/dist/preview/index.js`, everything works. The actual code snippet:
```
      key: "_checkStory",
      value: function _checkStory(selection) {
        if (!selection || _typeof(selection) !== 'object' || !selection.kind || !selection.story) {
          // Following line throws 'Unhandled promise rejection'. I have no idea why.
          // It must fire off a promise somewhere behind the scenes.
          console.warn('invalid storybook selection'); // eslint-disable-line no-console
          return null;
        }

        var story = this._getStory(selection);

        if (story.storyFn === null) {
          console.warn('invalid storybook selection'); // eslint-disable-line no-console

          return null;
        }

        return story;
      }
```

**Comment by Gongreg** [comment] 2019-01-30 13:23
Could you try out storybook version v4.1.11 ?

**Comment by jangnezda** [comment] 2019-01-30 13:32
Ha, works like a charm 👍 I see that `console.warn()` have been removed from the code. Weird that it could cause issues like that. Thanks a lot for the suggestion!

**Comment by Gongreg** [comment] 2019-01-30 13:34
Closing the issue then :)

**Closed by Gongreg** 2019-01-30 13:34 UTC
Labels: app: react-native, bug
