### ISSUE TITLE
Storybook v5.0.5 upgrade broken

### ISSUE THREAD

**Issue by TheKnarf** [storybooks/storybook#6255] opened 2019-03-25 08:22 UTC
**Describe the bug**
Using ` yarn upgrade-interactive --latest` I just upgraded from Storybook v5.0.3 to v5.0.5 and it broke my build. Does Storybook v5.0.5 work at all? I tried upgrading two different projects and both broke.

**Console output**
```
yarn run v1.13.0
$ start-storybook -p 9009 -s public
info @storybook/react v5.0.5
info
info => Loading static files from: /Users/fl-macbook-retina/Dropbox/Projects/poc-css-komponenter/public .
info => Loading presets
WARN   Failed to load preset: "/Users/fl-macbook-retina/Dropbox/Projects/poc-css-komponenter/node_modules/@storybook/core/dist/server/manager/manager-preset.js"
ERR! Error: Cannot find module '@emotion/core/package.json'
ERR!     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:609:15)
ERR!     at Function.resolve (internal/modules/cjs/helpers.js:28:19)
ERR!     at Object.<anonymous> (/Users/fl-macbook-retina/Dropbox/Projects/poc-css-komponenter/node_modules/@storybook/ui/paths.js:6:36)
ERR!     at Module._compile (internal/modules/cjs/loader.js:734:30)
ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)
ERR!     at Module.load (internal/modules/cjs/loader.js:626:32)
ERR!     at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
ERR!     at Function.Module._load (internal/modules/cjs/loader.js:558:3)
ERR!     at Module.require (internal/modules/cjs/loader.js:663:17)
ERR!     at require (internal/modules/cjs/helpers.js:20:18)
ERR!     at Object.<anonymous> (/Users/fl-macbook-retina/Dropbox/Projects/poc-css-komponenter/node_modules/@storybook/core/dist/server/manager/manager-webpack.config.js:18:37)
ERR!     at Module._compile (internal/modules/cjs/loader.js:734:30)
ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)
ERR!     at Module.load (internal/modules/cjs/loader.js:626:32)
ERR!     at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
ERR!     at Function.Module._load (internal/modules/cjs/loader.js:558:3)
ERR!  { Error: Cannot find module '@emotion/core/package.json'
ERR!     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:609:15)
ERR!     at Function.resolve (internal/modules/cjs/helpers.js:28:19)
ERR!     at Object.<anonymous> (/Users/fl-macbook-retina/Dropbox/Projects/poc-css-komponenter/node_modules/@storybook/ui/paths.js:6:36)
ERR!     at Module._compile (internal/modules/cjs/loader.js:734:30)
ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)
ERR!     at Module.load (internal/modules/cjs/loader.js:626:32)
ERR!     at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
ERR!     at Function.Module._load (internal/modules/cjs/loader.js:558:3)
ERR!     at Module.require (internal/modules/cjs/loader.js:663:17)
ERR!     at require (internal/modules/cjs/helpers.js:20:18)
ERR!     at Object.<anonymous> (/Users/fl-macbook-retina/Dropbox/Projects/poc-css-komponenter/node_modules/@storybook/core/dist/server/manager/manager-webpack.config.js:18:37)
ERR!     at Module._compile (internal/modules/cjs/loader.js:734:30)
ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)
ERR!     at Module.load (internal/modules/cjs/loader.js:626:32)
ERR!     at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
ERR!     at Function.Module._load (internal/modules/cjs/loader.js:558:3)
ERR!   stack:
ERR!    "Error: Cannot find module '@emotion/core/package.json'\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:609:15)\n    at Function.resolve (internal/modules/cjs/helpers.js:28:19)\n    at Object.<anonymous> (/Users/fl-macbook-retina/Dropbox/Projects/poc-css-komponenter/node_modules/@storybook/ui/paths.js:6:36)\n    at Module._compile (internal/modules/cjs/loader.js:734:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)\n    at Module.load (internal/modules/cjs/loader.js:626:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:566:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:558:3)\n    at Module.require (internal/modules/cjs/loader.js:663:17)\n    at require (internal/modules/cjs/helpers.js:20:18)\n    at Object.<anonymous> (/Users/fl-macbook-retina/Dropbox/Projects/poc-css-komponenter/node_modules/@storybook/core/dist/server/manager/manager-webpack.config.js:18:37)\n    at Module._compile (internal/modules/cjs/loader.js:734:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)\n    at Module.load (internal/modules/cjs/loader.js:626:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:566:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:558:3)",
ERR!   code: 'MODULE_NOT_FOUND' }
info => Loading presets
info => Loading custom webpack config (full-control mode).
info => Loading create-react-app config.
 10% building 4/5 modules 1 active ...oc-css-komponenter/.storybook/config.js

WARN force closed preview build

WARN FATAL broken build!, will close the process,
WARN Fix the error below and restart storybook.

EntryModuleNotFoundError: Entry module not found: Error: Can't resolve './src' in '/Users/fl-macbook-retina/Dropbox/Projects/poc-css-komponenter'
    at moduleFactory.create (/Users/fl-macbook-retina/Dropbox/Projects/poc-css-komponenter/node_modules/@storybook/core/node_modules/webpack/lib/Compilation.js:980:31)
    at factory (/Users/fl-macbook-retina/Dropbox/Projects/poc-css-komponenter/node_modules/@storybook/core/node_modules/webpack/lib/NormalModuleFactory.js:397:22)
    at resolver (/Users/fl-macbook-retina/Dropbox/Projects/poc-css-komponenter/node_modules/@storybook/core/node_modules/webpack/lib/NormalModuleFactory.js:130:21)
    at asyncLib.parallel (/Users/fl-macbook-retina/Dropbox/Projects/poc-css-komponenter/node_modules/@storybook/core/node_modules/webpack/lib/NormalModuleFactory.js:224:22)
    at /Users/fl-macbook-retina/Dropbox/Projects/poc-css-komponenter/node_modules/neo-async/async.js:2825:7
    at /Users/fl-macbook-retina/Dropbox/Projects/poc-css-komponenter/node_modules/neo-async/async.js:6886:13
    at normalResolver.resolve (/Users/fl-macbook-retina/Dropbox/Projects/poc-css-komponenter/node_modules/@storybook/core/node_modules/webpack/lib/NormalModuleFactory.js:214:25)
    at doResolve (/Users/fl-macbook-retina/Dropbox/Projects/poc-css-komponenter/node_modules/enhanced-resolve/lib/Resolver.js:184:12)
    at hook.callAsync (/Users/fl-macbook-retina/Dropbox/Projects/poc-css-komponenter/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/fl-macbook-retina/Dropbox/Projects/poc-css-komponenter/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at resolver.doResolve (/Users/fl-macbook-retina/Dropbox/Projects/poc-css-komponenter/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5)
    at hook.callAsync (/Users/fl-macbook-retina/Dropbox/Projects/poc-css-komponenter/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/fl-macbook-retina/Dropbox/Projects/poc-css-komponenter/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at hook.callAsync (/Users/fl-macbook-retina/Dropbox/Projects/poc-css-komponenter/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/fl-macbook-retina/Dropbox/Projects/poc-css-komponenter/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:12:1)
    at resolver.doResolve (/Users/fl-macbook-retina/Dropbox/Projects/poc-css-komponenter/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
resolve './src' in '/Users/fl-macbook-retina/Dropbox/Projects/poc-css-komponenter'
  using description file: /Users/fl-macbook-retina/Dropbox/Projects/poc-css-komponenter/package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: /Users/fl-macbook-retina/Dropbox/Projects/poc-css-komponenter/package.json (relative path: ./src)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /Users/fl-macbook-retina/Dropbox/Projects/poc-css-komponenter/src is not a file
      .wasm
        Field 'browser' doesn't contain a valid alias configuration
        /Users/fl-macbook-retina/Dropbox/Projects/poc-css-komponenter/src.wasm doesn't exist
      .mjs
        Field 'browser' doesn't contain a valid alias configuration
        /Users/fl-macbook-retina/Dropbox/Projects/poc-css-komponenter/src.mjs doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /Users/fl-macbook-retina/Dropbox/Projects/poc-css-komponenter/src.js doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        /Users/fl-macbook-retina/Dropbox/Projects/poc-css-komponenter/src.json doesn't exist
      as directory
        existing directory
          using path: /Users/fl-macbook-retina/Dropbox/Projects/poc-css-komponenter/src/index
            using description file: /Users/fl-macbook-retina/Dropbox/Projects/poc-css-komponenter/package.json (relative path: ./src/index)
              no extension
                Field 'browser' doesn't contain a valid alias configuration
                /Users/fl-macbook-retina/Dropbox/Projects/poc-css-komponenter/src/index doesn't exist
              .wasm
                Field 'browser' doesn't contain a valid alias configuration
                /Users/fl-macbook-retina/Dropbox/Projects/poc-css-komponenter/src/index.wasm doesn't exist
              .mjs
                Field 'browser' doesn't contain a valid alias configuration
                /Users/fl-macbook-retina/Dropbox/Projects/poc-css-komponenter/src/index.mjs doesn't exist
              .js
                Field 'browser' doesn't contain a valid alias configuration
                /Users/fl-macbook-retina/Dropbox/Projects/poc-css-komponenter/src/index.js doesn't exist
              .json
                Field 'browser' doesn't contain a valid alias configuration
                /Users/fl-macbook-retina/Dropbox/Projects/poc-css-komponenter/src/index.json doesn't exist
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
**System:**
 - OS: macOS Mojave
 - Device: Macbook Pro
 - Framework: React
 - Version: v5.0.5

**git diff package.json**
```
diff --git a/package.json b/package.json
index ead4ddb..e9f8d5f 100644
--- a/package.json
+++ b/package.json
@@ -4,11 +4,11 @@
   "private": true,
   "dependencies": {
     "@types/jest": "24.0.11",
-    "@types/node": "11.11.4",
+    "@types/node": "11.11.6",
     "@types/react": "16.8.8",
-    "@types/react-dom": "16.8.2",
-    "react": "^16.7.0",
-    "react-dom": "^16.7.0",
+    "@types/react-dom": "16.8.3",
+    "react": "^16.8.5",
+    "react-dom": "^16.8.5",
     "react-scripts": "2.1.8",
     "typescript": "3.3.4000"
   },
@@ -31,14 +31,14 @@
   ],
   "devDependencies": {
     "@babel/core": "^7.4.0",
-    "@storybook/addon-a11y": "^5.0.3",
-    "@storybook/addon-actions": "^5.0.3",
-    "@storybook/addon-info": "^5.0.3",
-    "@storybook/addon-knobs": "^5.0.3",
-    "@storybook/addon-links": "^5.0.3",
-    "@storybook/addon-storysource": "^5.0.3",
-    "@storybook/addons": "^5.0.3",
-    "@storybook/react": "^5.0.3",
+    "@storybook/addon-a11y": "^5.0.5",
+    "@storybook/addon-actions": "^5.0.5",
+    "@storybook/addon-info": "^5.0.5",
+    "@storybook/addon-knobs": "^5.0.5",
+    "@storybook/addon-links": "^5.0.5",
+    "@storybook/addon-storysource": "^5.0.5",
+    "@storybook/addons": "^5.0.5",
+    "@storybook/react": "^5.0.5",
     "babel-loader": "^8.0.5"
   }
 }
```

**Comment by monsterkrampe** [comment] 2019-03-25 08:56
Strangely it seems to work after deleting `node_modules` and `yarn.lock` and running `yarn` again...

**Comment by Adrien-D** [comment] 2019-03-25 09:19
Same here, but the problem is when you upgrade React to `v16.8.5` along with storybook `v5.0.5` (React v16.8.4 seems to work)

**Comment by shilman** [comment] 2019-03-25 09:49
My test project with `react@16.8.5` and `@storybook/react@5.0.5` is working fine. I think this is the same `yarn` upgrading problem that we've been having for the past month or so. 😦

**Comment by SleepWalker** [comment] 2019-03-25 13:41
@shilman nope, the only thing, that helps is to rollback `react` to `16.8.4`. I have this issue on two different projects (one is cra and another is custom config) in both cases `rm -r node_modules && yarn` does not help.

Downgrading storybook does not help too. Looks like something was changed in react, which breaks storybook

**Comment by SleepWalker** [comment] 2019-03-25 13:47
Before upgrade:

```
$ qnm react
react
└── 16.8.4
```

After upgrade:

```
$ qnm react
react
├── 16.8.5
├─┬ @emotion/styled-base
│ └── 16.8.4
├─┬ @storybook/addon-actions
│ └── 16.8.4
├─┬ @storybook/components
│ └── 16.8.4
├─┬ @storybook/router
│ └── 16.8.4
├─┬ @storybook/theming
│ └── 16.8.4
├─┬ @storybook/ui
│ └── 16.8.4
└─┬ react-inspector
  └── 16.8.4
```

After upgrade for some reason we have two different versions of react

**Comment by mohamedmansour** [comment] 2019-03-25 17:58
You need to install `@emotion/core `to make this work, which I did.

**Comment by kakadiadarpan** [comment] 2019-03-27 09:08
@mohamedmansour tried that, didn't work. 😕 

Breaks with `react@16.8.4` as well.

**Comment by jcampalo** [comment] 2019-03-27 09:30
I have the same error:

`
ModuleNotFoundError: Module not found: Error: Can't resolve '../src/themes' in '/Users/jcampalopez/Projects/tangram/storybook'
    at factory.create (/Users/jcampalopez/Projects/tangram/node_modules/webpack/lib/Compilation.js:823:10)
    at factory (/Users/jcampalopez/Projects/tangram/node_modules/webpack/lib/NormalModuleFactory.js:397:22)
    at resolver (/Users/jcampalopez/Projects/tangram/node_modules/webpack/lib/NormalModuleFactory.js:130:21)
    at asyncLib.parallel (/Users/jcampalopez/Projects/tangram/node_modules/webpack/lib/NormalModuleFactory.js:224:22)
    at /Users/jcampalopez/Projects/tangram/node_modules/neo-async/async.js:2825:7
    at /Users/jcampalopez/Projects/tangram/node_modules/neo-async/async.js:6886:13
    at normalResolver.resolve (/Users/jcampalopez/Projects/tangram/node_modules/webpack/lib/NormalModuleFactory.js:214:25)
    at doResolve (/Users/jcampalopez/Projects/tangram/node_modules/enhanced-resolve/lib/Resolver.js:184:12)
    at hook.callAsync (/Users/jcampalopez/Projects/tangram/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/jcampalopez/Projects/tangram/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at resolver.doResolve (/Users/jcampalopez/Projects/tangram/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5)
    at hook.callAsync (/Users/jcampalopez/Projects/tangram/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/jcampalopez/Projects/tangram/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at hook.callAsync (/Users/jcampalopez/Projects/tangram/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/jcampalopez/Projects/tangram/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:12:1)
    at resolver.doResolve (/Users/jcampalopez/Projects/tangram/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
    at hook.callAsync (/Users/jcampalopez/Projects/tangram/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn43 (eval at create (/Users/jcampalopez/Projects/tangram/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:402:1)
    at hook.callAsync (/Users/jcampalopez/Projects/tangram/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/jcampalopez/Projects/tangram/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:12:1)
    at resolver.doResolve (/Users/jcampalopez/Projects/tangram/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
    at hook.callAsync (/Users/jcampalopez/Projects/tangram/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
resolve '../src/themes' in '/Users/jcampalopez/Projects/tangram/storybook'
  using description file: /Users/jcampalopez/Projects/tangram/package.json (relative path: ./storybook)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: /Users/jcampalopez/Projects/tangram/package.json (relative path: ./src/themes)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /Users/jcampalopez/Projects/tangram/src/themes is not a file
      .mjs
        Field 'browser' doesn't contain a valid alias configuration
        /Users/jcampalopez/Projects/tangram/src/themes.mjs doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /Users/jcampalopez/Projects/tangram/src/themes.js doesn't exist
      .jsx
        Field 'browser' doesn't contain a valid alias configuration
        /Users/jcampalopez/Projects/tangram/src/themes.jsx doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        /Users/jcampalopez/Projects/tangram/src/themes.json doesn't exist
      as directory
        existing directory
          using path: /Users/jcampalopez/Projects/tangram/src/themes/index
            using description file: /Users/jcampalopez/Projects/tangram/package.json (relative path: ./src/themes/index)
              no extension
                Field 'browser' doesn't contain a valid alias configuration
                /Users/jcampalopez/Projects/tangram/src/themes/index doesn't exist
              .mjs
                Field 'browser' doesn't contain a valid alias configuration
                /Users/jcampalopez/Projects/tangram/src/themes/index.mjs doesn't exist
              .js
                Field 'browser' doesn't contain a valid alias configuration
                /Users/jcampalopez/Projects/tangram/src/themes/index.js doesn't exist
              .jsx
                Field 'browser' doesn't contain a valid alias configuration
                /Users/jcampalopez/Projects/tangram/src/themes/index.jsx doesn't exist
              .json
                Field 'browser' doesn't contain a valid alias configuration
                /Users/jcampalopez/Projects/tangram/src/themes/index.json doesn't exist
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @xivart/tangram@5.11.9 storybook: `npm run build:assets && STORYBOOK_LOCAL=true start-storybook -p 9001 -s ./assets -c storybook`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @xivart/tangram@5.11.9 storybook script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jcampalopez/.npm/_logs/2019-03-27T07_57_57_994Z-debug.log
`

It seems the issue is with webpack resolvers, for some reason is ignoring the custom webpack configuration.

**Comment by erikdstock** [comment] 2019-03-27 14:26
Should `@emotion/core` be a dev or peer dependency? Adding that addressed this issue for me but seems like something is missing there. From the OP:
```WARN   Failed to load preset: ".../node_modules/@storybook/core/dist/server/manager/manager-preset.js"
ERR! Error: Cannot find module '@emotion/core/package.json'```

I haven't deciphered all of this yet but it starts around here: https://github.com/storybooks/storybook/tree/next/lib/core/src/server/manager

**Comment by SleepWalker** [comment] 2019-03-31 06:57
Hey, looks like this issue is resolved now. I've just updated to the recent React version and everything looks fine again. Here is the dependency tree:

```
qnm react
react
└── 16.8.6
```

I think this issue was due to `emotion` package, which was updated to 10.0.10 recently (6 days ago), were this issue seems to be fixed.

**Comment by mbifulco** [comment] 2019-04-02 17:56
Chiming in to say that `react@16.8.6` does indeed seem to work for me, but I had to delete `node_modules` and `yarn.lock` and then run `yarn` to get everything working again. 🎉

**Comment by ckeeney** [comment] 2019-04-03 00:58
I encountered a similar issue when upgrading from `react@16.8.5` to `react@16.8.6`.

I upgraded using `yarn upgrade-interactive --latest`.

After upgrading, running storybook errored out:

```
EntryModuleNotFoundError: Entry module not found: Error: Can't resolve './src' in '/home/ckeeney/project'
    at moduleFactory.create (/home/ckeeney/project/node_modules/webpack/lib/Compilation.js:980:31)
    at factory (/home/ckeeney/project/node_modules/webpack/lib/NormalModuleFactory.js:397:22)
    at resolver (/home/ckeeney/project/node_modules/webpack/lib/NormalModuleFactory.js:130:21)
    at asyncLib.parallel (/home/ckeeney/project/node_modules/webpack/lib/NormalModuleFactory.js:224:22)
    at /home/ckeeney/project/node_modules/neo-async/async.js:2825:7
    at /home/ckeeney/project/node_modules/neo-async/async.js:6886:13
    at normalResolver.resolve (/home/ckeeney/project/node_modules/webpack/lib/NormalModuleFactory.js:214:25)
    at doResolve (/home/ckeeney/project/node_modules/enhanced-resolve/lib/Resolver.js:184:12)
    at hook.callAsync (/home/ckeeney/project/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/home/ckeeney/project/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at resolver.doResolve (/home/ckeeney/project/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5)
    at hook.callAsync (/home/ckeeney/project/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/home/ckeeney/project/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at hook.callAsync (/home/ckeeney/project/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/home/ckeeney/project/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:12:1)
    at resolver.doResolve (/home/ckeeney/project/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
resolve './src' in '/home/ckeeney/project'
  using description file: /home/ckeeney/project/package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: /home/ckeeney/project/package.json (relative path: ./src)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /home/ckeeney/project/src doesn't exist
      .wasm
        Field 'browser' doesn't contain a valid alias configuration
        /home/ckeeney/project/src.wasm doesn't exist
      .mjs
        Field 'browser' doesn't contain a valid alias configuration
        /home/ckeeney/project/src.mjs doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /home/ckeeney/project/src.js doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        /home/ckeeney/project/src.json doesn't exist
      as directory
        /home/ckeeney/project/src doesn't exist
```
I checked my `yarn.lock` to see how `react` had resolved, and it... resolved twice?

```
# yarn.lock
... other modules...

react@^16.8.1:
  version "16.8.5"
  resolved "https://registry.yarnpkg.com/react/-/react-16.8.5.tgz#49be3b655489d74504ad994016407e8a0445de66"
  integrity sha512-daCb9TD6FZGvJ3sg8da1tRAtIuw29PbKZW++NN4wqkbEvxL+bZpaaYb4xuftW/SpXmgacf1skXl/ddX6CdOlDw==
  dependencies:
    loose-envify "^1.1.0"
    object-assign "^4.1.1"
    prop-types "^15.6.2"
    scheduler "^0.13.5"

react@^16.8.6:
  version "16.8.6"
  resolved "https://registry.yarnpkg.com/react/-/react-16.8.6.tgz#ad6c3a9614fd3a4e9ef51117f54d888da01f2bbe"
  integrity sha512-pC0uMkhLaHm11ZSJULfOBqV4tIZkx87ZLvbbQYunNixAAvjnC+snJCg0XQXn9VIsttVsbZP/H/ewzgsd5fxKXw==
  dependencies:
    loose-envify "^1.1.0"
    object-assign "^4.1.1"
    prop-types "^15.6.2"
    scheduler "^0.13.6"
... other modules...
```

Deleting `yarn.lock` and re-running `yarn` fixed my corrupt `yarn.lock` and storybook works again.

**Comment by devrelm** [comment] 2019-04-07 03:10
I've opened #6435 to fix this.

**Comment by shilman** [comment] 2019-04-08 10:34
Shiver me timbers!! I just released https://github.com/storybooks/storybook/releases/tag/v5.1.0-alpha.23 containing PR #6435 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Closed by shilman** 2019-04-08 10:34 UTC
Labels: app: react, question / support, yarn / npm

**Comment by ChuckJHardy** [comment] 2019-05-05 15:16
As of `5.0.11` Referencing the fix from https://github.com/storybooks/storybook/issues/5706#issuecomment-469865797

Including `@storybook/theming` to `package.json` solved the `EntryModuleNotFoundError` issues for me.

**Comment by rbardini** [comment] 2019-11-11 09:25
Modifying the Webpack config for Storybook manager as described in https://github.com/storybookjs/storybook/issues/7196#issuecomment-505858914 solved the issue for me:

`.storybook/presets.js`

```js
const path = require("path");

module.exports = [
    path.resolve(__dirname, "./ts-preset"),
];
````

`.storybook/ts-preset.js`

```js
async function managerWebpack(baseConfig, options) {
    baseConfig.resolve.extensions.push(".ts", ".tsx");
    baseConfig.module.rules.push({ test: /\.tsx?$/, use: "ts-loader" });
    return baseConfig;
}

module.exports = {
    managerWebpack: managerWebpack,
};
```

**Comment by kakadiadarpan** [comment] 2019-11-11 09:36
@shilman Does it make sense to lock this issue as it is has been resolved?

**Comment by shilman** [comment] 2019-11-11 09:48
@kakadiadarpan What, you don't like being reminded of Storybook upgrade pains from earlier this year? 😜

I haven't locked any issues yet, mostly since useful comments can come many months after the fact. I'd recommend unsubscribing from the issue if you don't want notifications.

**Comment by kakadiadarpan** [comment] 2019-11-11 10:00
@shilman Haha, I've already unsubscribed actually. 😜 😂 

Was just thinking that since it has been fixed in the later version, maybe it's a good idea to lock it down. But I also agree with your point that some useful comments can come many months later.

PS: Thanks for all the work done on Storybook(and I mean everyone who has contributed to Storybook). 🙌

**Comment by hasparus** [comment] 2020-03-03 16:58
xD I just had this error. Reinstalling node_modules helped.

**Comment by AriaMoradpour** [comment] 2021-04-20 19:51
@shilman Hello, running into the same issue when upgrading to storybook 6.2. what was the solution here?

**Comment by haase1020** [comment] 2021-04-27 23:26
I am also running into the same issue with Storybook 6.2  --> what is the solution?

**Comment by zielinsm** [comment] 2021-04-29 07:35
I've managed to solve the issue by changing the fallback Webpack configuration:
```
    config.resolve.fallback = {
      crypto: false,
      path: require.resolve("path-browserify")
    }
```

**Comment by dwjohnston** [comment] 2021-05-15 02:39
I've just run into this issue creating a new create-react-app + typescript + storybook. I believe the issue probably was that I didn't run the `yarn start` to start the CRA dev server, and create the tsconfig, as per the instructions here: https://create-react-app.dev/docs/adding-typescript

**Comment by florianmartens** [comment] 2022-02-12 22:50
Still running into this. Not very pleasant.

**Comment by ElForastero** [comment] 2022-05-02 05:23
I'm using Next.js and default storybook setup.

I've just added styles import and everything got broken. Fixed it changing the styles import path to relative one:

`.storybook/preview.js`
```diff
- import 'src/shared/assets/styles/global.css';
+ import '../src/shared/assets/styles/global.css';

export const parameters = {
  actions: { argTypesRegex: "^on[A-Z].*" },
  controls: {
    matchers: {
      color: /(background|color)$/i,
      date: /Date$/,
    },
  },
}

```

**Comment by ryrocks** [comment] 2022-08-12 04:35
I upgraded to Webpack 5 and encountered the same issue.
After I browsed the [documents](https://storybook.js.org/docs/react/builders/webpack#lazy-compilation), and add `lazyCompilation: true` fixed the problem.

```
// .storybook/main.js

module.exports = {
  core: {
    builder: {
      name: 'webpack5',
      options: {
        lazyCompilation: true,
      },
    },
  },
};
```

**Comment by garvae** [comment] 2022-12-16 02:43
Maybe will be helpful: https://storybook.js.org/docs/react/builders/webpack#typescript-module-resolution

**Comment by sethburtonhall** [comment] 2023-08-30 18:41
> This might be helpful: https://storybook.js.org/docs/react/builders/webpack#typescript-module-resolution

Yes, adding the below snippet to `.storybook/main.ts` did the trick

```
  webpackFinal: async (config) => {
    if (config.resolve) {
      config.resolve.alias = {
        ...config.resolve.alias,
        "@": path.resolve(__dirname, "../"),
      };
    }
    return config;
  },
```
