### ISSUE TITLE
Addon-comments does not work with React Native

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#783] opened 2017-04-15 15:15 UTC
<a href="https://github.com/xareelee"><img src="https://avatars2.githubusercontent.com/u/804308?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [xareelee](https://github.com/xareelee)**
_Friday Mar 10, 2017 at 07:06 GMT_
_Originally opened as https://github.com/storybooks/storybook-addon-comments/issues/51_

----

After installation, my Storybook UI was stuck.

Does this library support React Native?

**Comment by tmeasday** [comment] 2017-06-23 03:13
Can someone reproduce this? Is it still a problem?

**Comment by shilman** [comment] 2017-06-23 06:46
@tmeasday this is comments addon, so I propose we kill it and close all these down 😜

**Comment by tmeasday** [comment] 2017-06-23 06:48
Oh, yeah I guess this is dupe of #1190

**Closed by tmeasday** 2017-06-23 06:48 UTC
Labels: addon: comments, app: react-native, bug, needs reproduction
