### ISSUE TITLE
Unexpected Token async function

### ISSUE THREAD

**Issue by apurvaojas** [storybooks/storybook#6381] opened 2019-04-02 10:55 UTC
**Describe the bug**
Upgrading strorybook@3 to latest version gives the following error
Bug in @storybook\core\dist\server\build-static.js:31

`async function  Unexpected Token`

As i am using node 6.9.1 and async support is from node version 7.4
So its node compilation error.

**Expected behavior**
package.json should have "engines"
https://docs.npmjs.com/files/package.json#engines

**Comment by MadebyAe** [comment] 2019-04-05 04:02
Hi @apurvaojas `async` is only available for node >=7.x

**Comment by ndelangen** [comment] 2019-04-05 06:40
Can you upgrade to the Node 8?

Node 7 isn't LTS, and Node 6 is end of life:
https://github.com/nodejs/Release

**Comment by shilman** [comment] 2019-04-05 07:08
@ndelangen He knows what the problem is, he's saying we need to update our package.json to document the incompatibility.

**Comment by shilman** [comment] 2019-04-26 09:28
NOTE: we do have `engines` in our root `package.json`: https://github.com/storybooks/storybook/blob/next/package.json#L203

Maybe we need to add it to the rest of our packages? @ndelangen

**Comment by ndelangen** [comment] 2019-05-17 10:39
My bad, I'll open a PR adding engines

**Comment by shilman** [comment] 2019-05-21 11:24
Ooh-la-la!! I just released https://github.com/storybooks/storybook/releases/tag/v5.1.0-rc.0 containing PR #6809 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Closed by shilman** 2019-05-21 11:24 UTC
Labels: maintenance
