### ISSUE TITLE
Color in the latest knobs version is broken

### ISSUE THREAD

**Issue by EloB** [storybooks/storybook#4223] opened 2018-09-24 13:33 UTC
The colorpicker is totally broken and cannot be used. Provided a PR to fix it.

https://github.com/storybooks/storybook/pull/4222

The bug is also reproducible in your examples. Try to update the `background` property here: 
https://storybooks-official.netlify.com/?selectedKind=Addons%7CKnobs.withKnobs&selectedStory=tweaks%20static%20values&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybooks%2Fstorybook-addon-knobs

**Comment by Keraito** [comment] 2018-09-24 15:11
Duplicate of #4093, closing this issue in favour of that one, thanks for the PR tho!

**Closed by Keraito** 2018-09-24 15:11 UTC
