### ISSUE TITLE
Using react-native-mock with storyshots will raise abnormal Error messages

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#888] opened 2017-04-15 17:39 UTC
<a href="https://github.com/xareelee"><img src="https://avatars2.githubusercontent.com/u/804308?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [xareelee](https://github.com/xareelee)**
_Thursday Mar 16, 2017 at 02:00 GMT_
_Originally opened as https://github.com/storybooks/storyshots/issues/85_

----

I'm developing React Native (RN) apps for iOS and Android.

I use [storyshots](https://github.com/storybooks/storyshots)/[storybook](https://github.com/storybooks/react-native-storybook) to snapshot the vDOM(s) of RN components with specific props for UI tests.

However, [Jest](https://facebook.github.io/jest/) lacks the functionality to mimic RN events to test whether the buttons work correctly. Then I found [airbnb's enzyme](https://github.com/airbnb/enzyme).

When I tested RN components with enzyme, I needed to install and set up [react-native-mock](https://github.com/airbnb/enzyme/blob/master/docs/guides/react-native.md). Then the issue happened:

Before I introduced [react-native-mock](https://github.com/airbnb/enzyme/blob/master/docs/guides/react-native.md) to my project, I had an unsolved snapshot conflict.

```
  ● Storyshots › LoginMsg › entry

    expect(value).toMatchSnapshot()
    
    Received value does not match stored snapshot 1.
    
    - Snapshot
    + Received
    
    @@ -314,42 +314,49 @@
               />
             </View>
           </Modal>
           <View
             style={
    -          Object {
    -            "alignItems": "center",
    -            "backgroundColor": "#F7F7F7",
    -            "flex": 1,
    -            "justifyContent": "center",
    -          }
    +          Array [
    +            Object {
    +              "alignItems": "center",
    +              "backgroundColor": "#F7F7F7",
    +              "flex": 1,
    +            },
    +            Object {},
    +          ]
             }
           >
```

After I add `react-native-mock`, the test error became:

```
  ● Storyshots › LoginMsg › entry

    TypeError: _setter is not a function
      
      at Component.requestAnimationFrame (node_modules/react-timer-mixin/TimerMixin.js:16:14)
      at Component.componentDidMount (node_modules/react-native/Libraries/Components/TextInput/TextInput.js:567:6)
      at node_modules/react-test-renderer/lib/ReactCompositeComponent.js:265:25
      at measureLifeCyclePerf (node_modules/react-test-renderer/lib/ReactCompositeComponent.js:75:12)
      at node_modules/react-test-renderer/lib/ReactCompositeComponent.js:264:11
      at CallbackQueue.notifyAll (node_modules/react-test-renderer/lib/CallbackQueue.js:76:22)
      at ReactTestReconcileTransaction.close (node_modules/react-test-renderer/lib/ReactTestReconcileTransaction.js:36:26)
      at ReactTestReconcileTransaction.closeAll (node_modules/react-test-renderer/lib/Transaction.js:206:25)
      at ReactTestReconcileTransaction.perform (node_modules/react-test-renderer/lib/Transaction.js:153:16)
      at batchedMountComponentIntoNode (node_modules/react-test-renderer/lib/ReactTestMount.js:69:27)
```

I think `react-native-mock` changes the behavior of storyshots, and make it report conflict incorrectly.

I'll post this issue on both `storyshots` and `react-native-mock`.

#[react-native-mock/issues/126](https://github.com/RealOrangeOne/react-native-mock/issues/126)

**Comment by tmeasday** [comment] 2017-05-15 09:40
@xareelee thanks for reporting this. By the sounds of the linked issue, the problem is with `react-native-mock` and Jest. Did you find a workaround?

I'll close this as it doesn't sound like there is much we can do. Let me know if not.

**Closed by tmeasday** 2017-05-15 09:40 UTC
Labels: bug, compatibility with other tools, storyshots
