### ISSUE TITLE
[BUG] Style: Title of Panels

### ISSUE THREAD

**Issue by wcastand** [storybooks/storybook#959] opened 2017-04-25 21:37 UTC
Hi,

I'm developing an [addon](https://github.com/Kilix/storybook-addon-jsx) for storybook and i create a panel with a custom React component as `title` and the title aren't centered with flex so it doesn't look really nice.

![screenshot](http://img4.hostingpics.net/pics/863457Capturedecran20170425a233057.png)

Is it possible to center the Panel's titles or he can break something i'm not aware of ?

If it's possible, i'd love to help and do a PR :)

**Comment by UsulPro** [comment] 2017-04-26 10:19
Hi @wcastand!

Thank you for the great addon!
You reported the cool feature, wich I guess didn't mention in our docs. How do you think should we add this?

The place you want to fix is [here](https://github.com/storybooks/storybook/blob/master/packages/storybook-ui/src/modules/ui/components/down_panel/index.js#L24). But before creating PR did you consider the possibility that the issue is on your addon side? Because when I

**Comment by wcastand** [comment] 2017-04-26 12:25
Hi ! 

Thank you for storybook !! :)
Yeah it's not mentionned that title can be a react component but i test and it worked so i was happy.

I think my addon break the layout of the titles because he contains a button and he's larger than other title.

I try to add `align-items: 'center';` on the container div and it work pretty well.

![capture d ecran 2017-04-26 a 14 22 55](https://cloud.githubusercontent.com/assets/2178244/25434273/eabd2fa2-2a8b-11e7-8bc6-d444a5d8026a.png)

Right now, no align-items is specified so he take the default which is `flex-start`

I use Chrome on OSX (Just in case)

**Comment by UsulPro** [comment] 2017-04-26 13:46
Yeap @wcastand I got your point!

I think PR for fixing that would be very welcomed!
At the same time, how do you think is it worth to add some reasonable limit of `max-height`?

**Comment by wcastand** [comment] 2017-04-26 13:55
I'll do a PR tonight then :)

For the max-height, it could be a good idea. Or maybe we fix the height and put a `align-items: stretch`. That way all the title will be the same height and centered properly and the developer know which height it can use.

Let me know if you prefer a max-height or fixed height with a `align-items: stretch` and which max height you think would be enough. A max-height of 60px seems good and allow the developer some freedom in what he can put in the title (like my addon which add a copy button).

**Comment by UsulPro** [comment] 2017-04-26 14:10
`align-items: stretch` lefts tubs stuck to the top of panel, so `max-height` and `overflow: hidden` in [tablink](https://github.com/storybooks/storybook/blob/master/packages/storybook-ui/src/modules/ui/components/down_panel/style.js#L38) seems a better solution. Agree 60px would be quite enough

**Comment by wcastand** [comment] 2017-04-26 14:27
Ok, i'll make the Pr with the max-height solution.

**Comment by UsulPro** [comment] 2017-04-29 15:11
Fixed by #961

**Closed by UsulPro** 2017-04-29 15:11 UTC
Labels: bug, needs docs, needs PR
