### ISSUE TITLE
addon API for storing state per-session or per-app.

### ISSUE THREAD

**Issue by tmeasday** [storybooks/storybook#5271] opened 2019-01-16 23:26 UTC
Issue: we removed the use of URL params for storing state. This will be an issue if apps reload (e.g. because HMR isn't working right, see for instance https://github.com/storybooks/storybook/issues/5267).

Right now we have an adhoc way of using `session/localStorage` for storing things. We also have retained `setQueryParams` but it no longer actually affects the URL so will not survive reloads etc.

We should resolve this for v5.

**Comment by tmeasday** [comment] 2019-01-17 09:15
Here's what I sketched out in my head:

What if we update `setState` to have the signature:

```js
function setState(update: object, persistence: 'none' | 'session' | 'forever') {}
```

When we `setState`, we may also set a "subset" of the state into `sessionStorage` and `localStorage` based on the above.

When we initialize the state, we will combine:
  1. The default initial state returned by each module
  2. The `forever` state
  3. The `session` state

Merging them with preference in that order (i.e. `session` > `forever` > defaults)

**Comment by shilman** [comment] 2019-01-23 13:48
w00t!! I just released https://github.com/storybooks/storybook/releases/tag/v5.0.0-alpha.9 containing PR #5289 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Closed by shilman** 2019-01-23 13:48 UTC
Labels: api: addons, feature request, high priority

**Comment by leoyli** [comment] 2019-02-07 21:21
@shilman, this is not working in the beta.1 version. (not sure about the prior versions)

For example, in a decorator I call `api.setQueryParams({ test: 'abc' })`. The URL is not changed and the subsequent call both (`console.dir(api.getUrlState())` and `console.dir(api.getQueryParam())`) was not showing the query parameter I provided...

Any clue or should I open a new issue?!

**Comment by tmeasday** [comment] 2019-02-07 21:55
@leoyli -- I think open a new issue. This issue was specifically about an API to replace the `setQueryParams` API, but we are aiming for back-compat there, so if it is broken, it is worth fixing.

**Comment by leoyli** [comment] 2019-02-08 02:34
I see, I will take a time to gather enough information and try to reproduce it using some sandbox or in a new project. After that I can open an issue! Thanks!

**Comment by andyindahouse** [comment] 2019-03-13 16:36
any news with this? `setQueryParams` is broken. Maybe is this a breaking change in v5?
