### ISSUE TITLE
Storybook 3.3 Release Checklist

### ISSUE THREAD

**Issue by danielduan** [storybooks/storybook#2316] opened 2017-11-15 19:23 UTC
Trying to get a sense of the work still left for 3.3.

Maintainers - feel free to add to this list:
- [x] Alpha test
- [ ] Angular support

**Comment by Hypnosphi** [comment] 2017-11-15 19:40
> Angular support
Do you mean that it also needs testing?

**Comment by danielduan** [comment] 2017-11-15 20:10
@Hypnosphi I actually have no idea what the status of it is. Is it finished and relatively stable?

**Comment by ndelangen** [comment] 2017-11-15 20:11
Should we do this checklist in the PR?

**Comment by Hypnosphi** [comment] 2017-11-15 20:12
@danielduan it's released with `3.3.0-alpha.3`

**Comment by danielduan** [comment] 2017-11-15 20:14
I'd like to get a list of things that should happen before merging `3.3.0` into master and releasing the final `3.3.0`. @ndelangen 

There's lots of different discussions in different issues and PRs about what should go in here, but I think we should have a comprehensive list and get to the release sooner rather than later.

**Comment by Hypnosphi** [comment] 2017-11-15 20:31
We have the milestone list and it's kinda empty for now: https://github.com/storybooks/storybook/milestone/9

**Comment by danielduan** [comment] 2017-11-15 21:21
If we're ready, should we get a push for users to help test 3.3-alpha and release soon after then?

1. There are some pretty important bug fixes that were merged to 3.3 around August/Sept and haven't gotten to users who require stable builds yet, myself included.
2. I'd like to alleviate the burden of having two development branches and merging between them.
3. The scope of the 3.3 update has been slowly expanding. I think we should define what we want in 3.3, finish it, and publish so we can move on to 3.4 and give users a more predictable release schedule.

**Comment by Hypnosphi** [comment] 2017-11-25 14:05
@storybooks/team how do we decide that alpha is tested enough?

**Comment by ndelangen** [comment] 2017-11-26 12:33
I've used alpha.4 react version on my current project, works great!

**Comment by Hypnosphi** [comment] 2017-11-26 13:35
I use it on mine since day one =)

**Comment by bjankord** [comment] 2017-11-28 10:10
Is this alpha.4 version published to npm? Trying to figure out how I can test it in my projects.

**Comment by Hypnosphi** [comment] 2017-11-28 22:49
There is also a regression that has to be fixed: https://github.com/storybooks/storybook/pull/1887#discussion_r148990688

@rhalff did you have any success with fixing it?

**Comment by rhalff** [comment] 2017-11-29 20:18
Yes I had success, the fix contained more then fixing that issue though, will try to create a pull request this week, sorry for the delay.

**Closed** 2018-01-02 15:48 UTC
Labels: maintenance
