### ISSUE TITLE
Error with 'getstorybook' ?

### ISSUE THREAD

**Issue by Safa2222** [storybooks/storybook#3571] opened 2018-05-11 13:25 UTC
I have just created a react app with create-react-app and tried to install storybook in it (npm i -g @storybook/cli  then getstorybook) but each time i get the same error and i have no clue on how to fix this : 
![error](https://user-images.githubusercontent.com/39192658/39926408-21854460-54fd-11e8-8d6a-4e03d5bd385e.png)
 HELP PLZ !!

**Comment by Keraito** [comment] 2018-05-11 13:54
Thanks for noticing us, @Safa2222. There is a similar issue right now, which is caused by a combination of factors between Windows and `npm`. The more thorough explanation that will help you is and how you can solve it is at https://github.com/storybooks/storybook/issues/3529#issuecomment-388006708. A fix has already been merged into the repository.

**Comment by Safa2222** [comment] 2018-05-11 14:08
Hmmm Okay thanks !

**Comment by Keraito** [comment] 2018-05-11 17:38
Closing this issue as it's the same as #3529 and the conversation is moved there.

**Closed by Keraito** 2018-05-11 17:38 UTC
Labels: question / support
