### ISSUE TITLE
Unable to start storybook

### ISSUE THREAD

**Issue by Eth3rnit3** [storybooks/storybook#5956] opened 2019-03-07 20:52 UTC
**Describe the bug**
Unable to launch the startup script `npm run storybook`

**To Reproduce**
Tried with node `8.11.3` and `10.15.1` same result
1 - `rm -rf node_modules && npm install` Clean install of node_modules
2 - `npx -p @storybook/cli sb init` Create React App has been detected, full install is ok !
3 - run startup script and crash

**Console Errors**
```shell
ModuleNotFoundError: Module not found: Error: Can't resolve 'core-js/modules/es7.symbol.async-iterator' in '/Users/eth3rnit3/code/Eth3rnit3/lunch-du-bureau-react-app/node_modules/@storybook/ui/dist/settings'
    at factory.create (/Users/eth3rnit3/code/Eth3rnit3/lunch-du-bureau-react-app/node_modules/@storybook/core/node_modules/webpack/lib/Compilation.js:823:10)
    at factory (/Users/eth3rnit3/code/Eth3rnit3/lunch-du-bureau-react-app/node_modules/@storybook/core/node_modules/webpack/lib/NormalModuleFactory.js:397:22)
    at resolver (/Users/eth3rnit3/code/Eth3rnit3/lunch-du-bureau-react-app/node_modules/@storybook/core/node_modules/webpack/lib/NormalModuleFactory.js:130:21)
    at asyncLib.parallel (/Users/eth3rnit3/code/Eth3rnit3/lunch-du-bureau-react-app/node_modules/@storybook/core/node_modules/webpack/lib/NormalModuleFactory.js:224:22)
    at /Users/eth3rnit3/code/Eth3rnit3/lunch-du-bureau-react-app/node_modules/neo-async/async.js:2825:7
    at /Users/eth3rnit3/code/Eth3rnit3/lunch-du-bureau-react-app/node_modules/neo-async/async.js:6886:13
    at normalResolver.resolve (/Users/eth3rnit3/code/Eth3rnit3/lunch-du-bureau-react-app/node_modules/@storybook/core/node_modules/webpack/lib/NormalModuleFactory.js:214:25)
    at doResolve (/Users/eth3rnit3/code/Eth3rnit3/lunch-du-bureau-react-app/node_modules/enhanced-resolve/lib/Resolver.js:184:12)
    at hook.callAsync (/Users/eth3rnit3/code/Eth3rnit3/lunch-du-bureau-react-app/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/eth3rnit3/code/Eth3rnit3/lunch-du-bureau-react-app/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at resolver.doResolve (/Users/eth3rnit3/code/Eth3rnit3/lunch-du-bureau-react-app/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5)
    at hook.callAsync (/Users/eth3rnit3/code/Eth3rnit3/lunch-du-bureau-react-app/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/eth3rnit3/code/Eth3rnit3/lunch-du-bureau-react-app/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at hook.callAsync (/Users/eth3rnit3/code/Eth3rnit3/lunch-du-bureau-react-app/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/Users/eth3rnit3/code/Eth3rnit3/lunch-du-bureau-react-app/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:12:1)
    at resolver.doResolve (/Users/eth3rnit3/code/Eth3rnit3/lunch-du-bureau-react-app/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
resolve 'core-js/modules/es7.symbol.async-iterator' in '/Users/eth3rnit3/code/Eth3rnit3/lunch-du-bureau-react-app/node_modules/@storybook/ui/dist/settings'
  Parsed request is a module
  using description file: /Users/eth3rnit3/code/Eth3rnit3/lunch-du-bureau-react-app/node_modules/@storybook/ui/package.json (relative path: ./dist/settings)
    aliased with mapping 'core-js': '/Users/eth3rnit3/code/Eth3rnit3/lunch-du-bureau-react-app/node_modules/core-js' to '/Users/eth3rnit3/code/Eth3rnit3/lunch-du-bureau-react-app/node_modules/core-js/modules/es7.symbol.async-iterator'
      using description file: /Users/eth3rnit3/code/Eth3rnit3/lunch-du-bureau-react-app/node_modules/@storybook/ui/package.json (relative path: ./dist/settings)
        Field 'browser' doesn't contain a valid alias configuration
        using description file: /Users/eth3rnit3/code/Eth3rnit3/lunch-du-bureau-react-app/node_modules/core-js/package.json (relative path: ./modules/es7.symbol.async-iterator)
          no extension
            Field 'browser' doesn't contain a valid alias configuration
            /Users/eth3rnit3/code/Eth3rnit3/lunch-du-bureau-react-app/node_modules/core-js/modules/es7.symbol.async-iterator doesn't exist
          .mjs
            Field 'browser' doesn't contain a valid alias configuration
            /Users/eth3rnit3/code/Eth3rnit3/lunch-du-bureau-react-app/node_modules/core-js/modules/es7.symbol.async-iterator.mjs doesn't exist
          .js
            Field 'browser' doesn't contain a valid alias configuration
            /Users/eth3rnit3/code/Eth3rnit3/lunch-du-bureau-react-app/node_modules/core-js/modules/es7.symbol.async-iterator.js doesn't exist
          .jsx
            Field 'browser' doesn't contain a valid alias configuration
            /Users/eth3rnit3/code/Eth3rnit3/lunch-du-bureau-react-app/node_modules/core-js/modules/es7.symbol.async-iterator.jsx doesn't exist
          .json
            Field 'browser' doesn't contain a valid alias configuration
            /Users/eth3rnit3/code/Eth3rnit3/lunch-du-bureau-react-app/node_modules/core-js/modules/es7.symbol.async-iterator.json doesn't exist
          as directory
            /Users/eth3rnit3/code/Eth3rnit3/lunch-du-bureau-react-app/node_modules/core-js/modules/es7.symbol.async-iterator doesn't exist
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! front@0.1.0 storybook: `start-storybook -p 9009 -s public`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the front@0.1.0 storybook script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/eth3rnit3/.npm/_logs/2019-03-07T20_36_25_847Z-debug.log
```

**2019-03-07T20_36_25_847Z-debug.log**
```shell
0 info it worked if it ends with ok
1 verbose cli [ '/Users/eth3rnit3/.nvm/versions/node/v8.11.3/bin/node',
1 verbose cli   '/Users/eth3rnit3/.nvm/versions/node/v8.11.3/bin/npm',
1 verbose cli   'run',
1 verbose cli   'storybook' ]
2 info using npm@6.5.0
3 info using node@v8.11.3
4 verbose run-script [ 'prestorybook', 'storybook', 'poststorybook' ]
5 info lifecycle front@0.1.0~prestorybook: front@0.1.0
6 info lifecycle front@0.1.0~storybook: front@0.1.0
7 verbose lifecycle front@0.1.0~storybook: unsafe-perm in lifecycle true
8 verbose lifecycle front@0.1.0~storybook: PATH: /Users/eth3rnit3/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/eth3rnit3/code/Eth3rnit3/lunch-du-bureau-react-app/node_modules/.bin:/Users/eth3rnit3/.avn/bin:/Users/eth3rnit3/.nvm/versions/node/v8.11.3/bin:./bin:/Users/eth3rnit3/.rbenv/shims:/usr/local/opt/rbenv/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin
9 verbose lifecycle front@0.1.0~storybook: CWD: /Users/eth3rnit3/code/Eth3rnit3/lunch-du-bureau-react-app
10 silly lifecycle front@0.1.0~storybook: Args: [ '-c', 'start-storybook -p 9009 -s public' ]
11 silly lifecycle front@0.1.0~storybook: Returned: code: 1  signal: null
12 info lifecycle front@0.1.0~storybook: Failed to exec storybook script
13 verbose stack Error: front@0.1.0 storybook: `start-storybook -p 9009 -s public`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/eth3rnit3/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/Users/eth3rnit3/.nvm/versions/node/v8.11.3/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid front@0.1.0
15 verbose cwd /Users/eth3rnit3/code/Eth3rnit3/lunch-du-bureau-react-app
16 verbose Darwin 18.2.0
17 verbose argv "/Users/eth3rnit3/.nvm/versions/node/v8.11.3/bin/node" "/Users/eth3rnit3/.nvm/versions/node/v8.11.3/bin/npm" "run" "storybook"
18 verbose node v8.11.3
19 verbose npm  v6.5.0
20 error code ELIFECYCLE
21 error errno 1
22 error front@0.1.0 storybook: `start-storybook -p 9009 -s public`
22 error Exit status 1
23 error Failed at the front@0.1.0 storybook script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**System:**
 - OS: MacOS
 - Device: Macbook Pro 2017
 - Framework: Create React App
 - Version: 5.0.0

**Comment by Eth3rnit3** [comment] 2019-03-07 20:59
### Solved by using yarn
- `rm -rf node_modules && yarn install`
- `npx -p @storybook/cli sb init` (I don't know if it's possible with yarn)
- `yarn storybook` 

It work fine !

**Comment by shilman** [comment] 2019-03-08 03:45
Glad you fixed it!

Closing this as a dupe of https://github.com/storybooks/storybook/issues/5831

**Closed by shilman** 2019-03-08 03:45 UTC

**Comment by Paratron** [comment] 2020-09-22 11:03
Same problem here after migrating from Storybook 5 to 6 and the removal of node_modules and package-lock did not solve anything :(

**Comment by shilman** [comment] 2020-09-25 06:03
@Paratron try `yarn storybook --no-dll`
