### ISSUE TITLE
@storybook/react package problems

### ISSUE THREAD

**Issue by char0n** [storybooks/storybook#2643] opened 2018-01-04 14:37 UTC
### Issue details

When installing @storybook/react@3.3.3 there is a problem with package.json

### Steps to reproduce

`npm install @storybook/react@3.3.3`

Inspect `./node_modules/@storybook/react/package.json`

There is following property: `"jsnext:main": "src/client/index.js",`

Notice that the path `src/client/index.js` doesn't exist in the package tree. This is causing multiple issues like linting, building, etc...

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react 3.3.3

### Affected platforms 

All

**Comment by igor-dv** [comment] 2018-01-04 15:06
This is duplicate of #2627. Was already fixed, and will be released soon.
Thanks =)

**Closed** 2018-01-04 15:06 UTC
