### ISSUE TITLE
Absolute imports broken in v4

### ISSUE THREAD

**Issue by arvigeus** [storybooks/storybook#4700] opened 2018-11-02 21:27 UTC
**Describe the bug**
Absolute imports no longer work.

**To Reproduce**
1. Clone https://github.com/arvigeus/storytime
2. Run storybook to confirm it's working
3. Update to storybook 4

**Expected behavior**
Should keep working as it was in v3

**Comment by chadfawcett** [comment] 2018-11-02 22:19
I believe this is a duplicate of #4496

**Comment by igor-dv** [comment] 2018-11-03 09:57
Yep, it is.

**Closed by igor-dv** 2018-11-03 09:57 UTC
