### ISSUE TITLE
"Can't find variable: document" React Native error (3.3.0-alpha.2)

### ISSUE THREAD

**Issue by hellogerard** [storybooks/storybook#2096] opened 2017-10-19 16:03 UTC
Hello,

I am trying to get 3.3 up & running so that I can have accessibility labels (#1780) for Detox testing. Everything installs fine, but when I start up the app, I get a RSOD on `Can't find variable: document`.

<img width="300" src="https://user-images.githubusercontent.com/200488/31780810-ce57c0ac-b4c4-11e7-899d-bdc53f658185.png">

The `sheet.js` in the trace is inside of the `glamor` package. That particular line looks like:

```js
const oldIE = (() => {  
  if(isBrowser) {
    let div = document.createElement('div') // <--- this line 
    div.innerHTML = '<!--[if lt IE 10]><i></i><![endif]-->'
    return div.getElementsByTagName('i').length === 1
  }  
})()
```

`isBrowser` looks like:

```js
const isBrowser = typeof window !== 'undefined'
```

(https://github.com/threepointone/glamor/blob/master/src/sheet.js)

Maybe there is a `global.window` defined in Storybook 3.3 that wasn't there in 3.2?

P.S. I realize this is alpha release, but I figured I'd report it sooner rather than later if it is legit. Also, my setup is a tad bit complicated — I'm using `react-native-storybook-loader` — so I tried to create a vanilla CRNA/Storybook repo for you, but I couldn't get past #1943.

_Edit: Additional info_

React Native: 0.47.2
Some `npm ls` output:

```
├─┬ @storybook/react-native@3.3.0-alpha.2
...
│ ├─┬ @storybook/addon-links@3.3.0-alpha.2
│ │ ├── @storybook/addons@3.3.0-alpha.2 deduped
│ │ ├─┬ @storybook/components@3.3.0-alpha.2
│ │ │ ├─┬ glamor@2.20.40
```

**Comment by danielduan** [comment] 2017-11-02 02:43
looks like this change made the `linkTo` component dependent on styled components. https://github.com/storybooks/storybook/pull/1829/files

this seems to affect the `Welcome.js` template, but the same error still occurs when I remove that instance and make `linkTo` render null. I can't seem to find any other React only components that are leaking into React-Native but it seems to be a problem.

**Comment by danielduan** [comment] 2017-11-02 02:49
Help highly appreciated!

Somehow react-native bundler is bundling glamorous and some React styled components inside the react-native bundle. I can't pin where this is happening because I'm not too familiar with the rn cli tools. If anyone has time, I'd love some help.

**Comment by tmeasday** [comment] 2017-11-06 03:01
Had a look at this with @danielduan's help.

The issue comes from this line: https://github.com/storybooks/storybook/blob/release/3.3/addons/links/src/index.js#L8

The problem is that `addon-links` is imported from RN's preview context (which runs inside react native, not a web browser). As addon links is importing our components (which are *web* components, reliant on glamorous which doesn't run in RN) we get an exception.

**Comment by tmeasday** [comment] 2017-11-06 03:02
I'm not sure what the best solution is but it probably involves separating the "UI" exports from `addon-links` from the "functionality" exports. @Hypnosphi, what do you think?

**Comment by Hypnosphi** [comment] 2017-11-06 03:03
Ok, so I can remove the reexport, and add a deprecation placeholder in case someone used it, right?

**Comment by tmeasday** [comment] 2017-11-06 03:03
Probably -- perhaps it should be exported by `addon-links/UI` or something so people can use it?

**Comment by Hypnosphi** [comment] 2017-11-06 03:04
maybe event `addon-links/react`

**Comment by tmeasday** [comment] 2017-11-06 03:05
That's technically accurate but maybe a little confusing as you may want to use the export within an addon which can work with any framework (but in the react-based manager UI of course). What do you think?

**Comment by tmeasday** [comment] 2017-11-06 03:06
(updated my comment above with the opposite opinion ;) )

**Comment by Hypnosphi** [comment] 2017-11-06 03:11
This component is rendered in preview not manager, so it's usable only in React environment

**Comment by tmeasday** [comment] 2017-11-06 03:15
> This component is rendered in preview not manager, so it's usable only in React environment

Oh, right. Even moreso then :)

**Comment by danielduan** [comment] 2017-11-06 17:13
verified fixed with PR ^

**Closed by danielduan** 2017-11-06 17:13 UTC
Labels: app: react-native, bug, help wanted, high priority

**Comment by apawar14** [comment] 2018-04-19 06:27
Hi,

I am not able to print "Hi" on screen.

![screenshot_1524119087](https://user-images.githubusercontent.com/38472918/38974707-f9f41402-435f-11e8-9bab-3fb5b0ad0215.png)

**Comment by MaulikPlutus** [comment] 2018-05-03 00:04
Can't find variable: autobind.
<img width="316" alt="screen shot 2018-05-03 at 5 33 49 am" src="https://user-images.githubusercontent.com/36003390/39555003-9f4ceb2a-4e93-11e8-9185-064efdb8c20a.png">

**Comment by MaulikPlutus** [comment] 2018-05-03 00:05
`// @flow
import moment from "moment";
import * as React from "react";
import { StyleSheet, View, Text, TextInput, Switch } from "react-native";
import { H1, ListItem, List, Item, Body, Right, Icon, Picker, CheckBox, Button, SettingsSwitch, Container, Content, Segment } from "native-base";
import { BaseContainer, Styles, Avatar, Field, Small } from "../components";

import type {ScreenProps } from "../components/Types";

import variables from "../../native-base-theme/variables/commonColor";

export default class Contact extends React.Component<ScreenProps<>> {

    //Variable define
    // http://dev-app.pamtree.com/dashboard/contacts/put
    // Note : Marital Status
    // Note : confirmation 
    // Note : Custum fields (Add Button) click to add fields 
    // note : delete button after submit
    constructor(props) {
        super(props);
        // For Maritial Status
        this.state = {
            selectedItem: undefined,
            selected1: 'key1',
            results: {
                items: []
            },
            customerTitle: [],
            customerValue: [],
            toggled: true
        }
    }
    //  Marital status Change valice
    onValueChange(value: string) {
        this.setState({
            selected1: value
        });
    }

    go(key: string) {
        this.props.navigation.navigate(key);
    }

    //start code of adding dynamically custome fields
    addTextInput = (key) => {
        console.log('key 1 --', key);
        let customerTitle = this.state.customerTitle;
        customerTitle.push(<View key={key}><Field key={key} label="Customer Field Title" defaultValue="Customer Title" />
            <Field label="Value" key={key} defaultValue="Field value" /></View>);
        this.setState({ customerTitle })
    }

    toggleSwitch1 = () => {
        let switchValue = !this.state.toggled;
        this.setState({ toggled: switchValue })
        console.log(' this.state.toggled -', this.state.toggled);
    }
    //end

    render(): React.Node {
        return <BaseContainer title="Contact" navigation={this.props.navigation} scrollable>
            <View style={[Styles.center, style.header]}>
                <H1>Add New Contact</H1>
            </View>

            {/* <Switch
                onValueChange={props.toggleSwitch2}
                value={props.switch2Value} /> */}
            <List>
                <ListItem itemDivider>
                    <Text>Personal Information</Text>
                </ListItem>
                <Field
                    label="First name"
                    defaultValue="Type first name here"
                    textInputRef={this.setFirstnameRef}
                    onSubmitEditing={this.goToSurname}
                    returnKeyType="next"
                />
                <Field
                    label="Surname"
                    defaultValue="Type last name here"
                    textInputRef={this.setSurnameRef}
                    onSubmitEditing={this.goToOccupation}
                    returnKeyType="next"
                />
                <Field
                    label="Occupation"
                    defaultValue="Occupation"
                    textInputRef={this.setOccupationRef}
                    onSubmitEditing={this.goToPhone}
                    returnKeyType="next"
                />
                <Field
                    label="Phone Number"
                    defaultValue="0123-123456789"
                    textInputRef={this.setPhoneRef}
                    onSubmitEditing={this.goToEmail}
                    returnKeyType="next"
                />
                <Field
                    label="Email"
                    defaultValue="email@gmail.com"
                    textInputRef={this.setEmailRef}
                    onSubmitEditing={this.goToAge}
                    returnKeyType="next"
                />
                <Field
                    label="Age"
                    defaultValue="25"
                    textInputRef={this.setAgeRef}
                    onSubmitEditing={this.goToStatus}
                    returnKeyType="next"
                />
                <Picker
                    mode='dropdown'
                    selectedValue={this.state.selected1}
                    onValueChange={this.onValueChange.bind(this)}>
                    <Item label='Marital Status' value='' />
                    <Item label='Single' value='Single' />
                    <Item label='Married' value='Married' />
                    <Item label='Separated' value='Separated' />
                    <Item label='Divorced' value='Divorced' />
                    <Item label='Civil Partnership' value='Civil Partnership' />
                    <Item label='Widowed' value='Widowed' />
                </Picker>
                <Field
                    label="Address"
                    defaultValue="Address"
                    textInputRef={this.setAddressRef}
                    onSubmitEditing={this.goToImg_url}
                    returnKeyType="next"
                />
                <ListItem itemDivider>
                    <Text>Image</Text>
                </ListItem>
                <Field
                    label="Image"
                    defaultValue="Image"
                    textInputRef={this.setImg_urlRef}
                    onSubmitEditing={this.goToTags}
                    returnKeyType="next"
                    secureTextEntry
                />
                <ListItem itemDivider>
                    <Text>Tags</Text>
                </ListItem>
                <Picker
                    mode='dropdown'
                    selectedValue={this.state.selected1}
                    onValueChange={this.onValueChange.bind(this)}>
                    <Item label='stage 1' value='stage 1' />
                    <Item label='stage 2' value='stage 2' />
                </Picker>
                <ListItem itemDivider>
                    <Text>Confirmation</Text>
                </ListItem>
                <CheckBox checked={false} />
                <Text>This person gave me permission to contact them This person will not receive a confirmation email from Pamtree as you are
                adding this recipient manually so be sure you have permission to contact them first.</Text>

                <ListItem itemDivider>
                    <Text>Custom Fields</Text>
                </ListItem>
                <View>
                    {this.state.customerTitle.map((value, index) => {
                        return value
                    })}
                    <Button primary Small onPress={() => this.addTextInput(this.state.customerTitle.length)}>
                        <Text>Add</Text>
                    </Button>
                </View>
                <ListItem itemDivider>
                    <Text>Other Information</Text>
                </ListItem>
                <View>
                    <Text>Drives ?</Text>
                    <Switch
                        onValueChange={() => this.toggleSwitch1()}
                        value={this.state.toggled}
                    />
                </View>
                <Field
                    label="Objective"
                    textInputRef={this.setDrivesRef}
                    onSubmitEditing={this.goToObjective}
                    returnKeyType="next"
                />

                <ListItem itemDivider>
                    <Text>Notes</Text>
                </ListItem>
                <Field
                    label="Notes"
                    defaultValue="Notes"
                    textInputRef={this.setNotesRef}
                    onSubmitEditing={this.submit}
                    returnKeyType="go"
                    last
                />
                <Button primary full>
                    <Text> Submit </Text>
                </Button>
            </List>
            <Container>
                <Content>
                    {/* {this.state.customerTitle.map((value, index) => {
                        return value
                    })} */}
                </Content>
            </Container>
        </BaseContainer>;
    }
}

const style = StyleSheet.create({
    header: {
        backgroundColor: variables.lightGray
    },
    icon: {
        color: variables.brandInfo,
        fontSize: 30
    },
    avatars: {
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "center"
    },
    avatar: {
        marginRight: variables.contentPadding / 2
    }
});
`

**Comment by michaelduminy** [comment] 2018-08-22 16:04
This is a problem again due to `components/GroupTabs` importing `@storybook/components` and `components/types/Date/index` imports and references `insert-css`. Commenting these out makes it work.

**Comment by krishna4157** [comment] 2019-11-02 04:48
> I'm not sure what the best solution is but it probably involves separating the "UI" exports from `addon-links` from the "functionality" exports. @Hypnosphi, what do you think?

can u explain in detailed?
