### ISSUE TITLE
Remember panel sizes in local-storage.

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#869] opened 2017-04-15 15:46 UTC
<a href="https://github.com/philcockfield"><img src="https://avatars2.githubusercontent.com/u/185555?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [philcockfield](https://github.com/philcockfield)**
_Thursday Nov 24, 2016 at 19:50 GMT_
_Originally opened as https://github.com/storybooks/storybook-ui/issues/62_

----

Cross referencing this issue over to the actual repo: https://github.com/storybooks/react-storybook/issues/466

-----

Would be great if the action-logger panel, and the index panel, didn't not lose their size between page loads.

![image](https://cloud.githubusercontent.com/assets/185555/20609002/2d9ad814-b2ec-11e6-893e-7b906af66520.png)

**Comment by shilman** [comment] 2017-04-15 15:46
<a href="https://github.com/willowcheng"><img src="https://avatars0.githubusercontent.com/u/6239076?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [willowcheng](https://github.com/willowcheng)**
_Tuesday Apr 11, 2017 at 03:47 GMT_

----

Would love to see that width can be remembered if down panel is configured to be displayed on right.

**Comment by shilman** [comment] 2017-04-15 15:46
<a href="https://github.com/ndelangen"><img src="https://avatars1.githubusercontent.com/u/3070389?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [ndelangen](https://github.com/ndelangen)**
_Tuesday Apr 11, 2017 at 05:04 GMT_

----

PR is very much welcome @willowcheng ❤️

**Comment by shilman** [comment] 2017-04-15 15:46
<a href="https://github.com/benediktvaldez"><img src="https://avatars1.githubusercontent.com/u/1928103?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [benediktvaldez](https://github.com/benediktvaldez)**
_Tuesday Apr 11, 2017 at 20:24 GMT_

----

Does this previous change not solve this issue as well @willowcheng ? Haven't tried it out though, but if not, it could at least be an idea of how to tackle it.

https://github.com/storybooks/storybook-ui/pull/74/files#diff-45accb91d04d726de15be9e2a89530ebR172

**Comment by shilman** [comment] 2017-04-15 15:46
<a href="https://github.com/willowcheng"><img src="https://avatars0.githubusercontent.com/u/6239076?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [willowcheng](https://github.com/willowcheng)**
_Wednesday Apr 12, 2017 at 03:51 GMT_

----

Hi @benediktvaldez, it actually works and I thought it's already available to newest storybook release. 

Created #80 to remember both width and height in case of use cases that need to switch panel position. I found that by dragging splitter and then changing down panel position, the `height` would be instantly carried to `width` without applying rendering, no idea how to solve it.

**Comment by ndelangen** [comment] 2017-07-07 12:23
I will close this as a duplicate of #466

**Closed by ndelangen** 2017-07-07 12:23 UTC
Labels: feature, help wanted, ui
