### ISSUE TITLE
assets.preview is undefined

### ISSUE THREAD

**Issue by sir-marc** [storybooks/storybook#663] opened 2017-01-10 09:48 UTC
pendant to https://github.com/storybooks/react-storybook/pull/640

i got the same error: 

>     js: assets.preview.find(function (filename) {
                      ^
> TypeError: Cannot read property 'find' of undefined

when i changed the code like the mentioned pull request in `iframe.html.js` on line 38 to:
```
if (!assets || !assets.preview) {
    return {
      js: 'static/preview.bundle.js',
    };
  }
```

I did not get an error message anymore, but the site is still not working. It does not create a static folder in which the `manager.bundle.js` should be.

@kadira/storybook v2.35.2

**Comment by kylpo** [comment] 2017-01-11 00:59
For me, this was a webpack.config.js issue. When I deleted the file to reverted back to storybook's default webpack config, `build-storybook` worked without the 'find' error.

**Comment by sir-marc** [comment] 2017-01-11 07:19
This is not an option for me as I'm depending on vairous things from webpack such as loaders (not included in the base setup e.g. TS or Sass), Path mappings and Plugins.

**Comment by arunoda** [comment] 2017-01-12 17:38
The fix you did is a good one.
If I can get a sample repo, I could work on this more.

**Comment by ndelangen** [comment] 2017-07-07 13:04
I think the problem is you node version doesn't have `Array.prototype.find`. Can you use a more modern version of node?

Please re-open if you are experiencing this issue with a modern version of node.

**Comment by syabro** [comment] 2017-07-20 15:23
@ndelangen have the same error
and how with error `TypeError: Cannot read property 'find' of undefined` you got the idea of not modern version of node
Does `undefined` in your node have `.find` method?

**Comment by syabro** [comment] 2017-07-20 15:25
UPD: I've fixed the issue by disabling `HotModuleReplacementPlugin` in plugins

**Comment by ndelangen** [comment] 2017-07-21 09:43
> Does undefined in your node have a .find method?

Whoops, my bad; you're right.

**Comment by danielduan** [comment] 2017-08-31 03:46
Closing issue because it's v2. Please reopen if this is still an issue on the latest v3.

**Closed by danielduan** 2017-08-31 03:46 UTC
Labels: bug, needs reproduction
