### ISSUE TITLE
Passing event.target causes Storybook to hang

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#779] opened 2017-04-15 06:28 UTC
<a href="https://github.com/TheSisb"><img src="https://avatars0.githubusercontent.com/u/1592327?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [TheSisb](https://github.com/TheSisb)**
_Thursday Jan 19, 2017 at 00:52 GMT_
_Originally opened as https://github.com/storybooks/storybook-addon-actions/issues/27_

----

I have a story that passes `onFocus={action('Focused')}`
The component is an input element with `onFocus={this.onFocus}`

```js
onFocus = e => {
  this.props.onFocus && this.props.onFocus(e.target);  // App hangs.  'e' alone is fine.
};
```

**Comment by shilman** [comment] 2017-04-15 06:28
<a href="https://github.com/timoxley"><img src="https://avatars2.githubusercontent.com/u/43438?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [timoxley](https://github.com/timoxley)**
_Monday Mar 20, 2017 at 07:04 GMT_

----

Can reproduce. I'm getting incredibly slow responses from `action`. Click handler takes about a second, and seems to be stuck stringifying an html element:

![image](https://cloud.githubusercontent.com/assets/43438/24090775/40624b98-0d7e-11e7-9e28-9ec18696bc31.png)

As a quick workaround I suggest the serializer should specifically ignore dom elements.

Why does it need to stringify at all?

**Comment by ndelangen** [comment] 2017-07-07 14:03
I'm going to close this because it's a duplicate of #778, thanks for reporting @TheSisb!

We're looking for a contributor that can make a PR for this, maybe you? or @timoxley ?

**Closed by ndelangen** 2017-07-07 14:03 UTC
Labels: addon: actions, bug
