### ISSUE TITLE
upgrade storybook@alpha to use emotion version 10

### ISSUE THREAD

**Issue by lifeiscontent** [storybooks/storybook#4525] opened 2018-10-23 11:08 UTC
I'm running into an issue using @emotion/core@next

export `withCSSContext` was not found in `@emotion/core`

this is due to the API changing in emotion 10.

**Comment by lifeiscontent** [comment] 2018-11-15 00:15
@igor-dv do you know who might be able to look into this?

**Comment by lifeiscontent** [comment] 2018-11-28 23:46
@igor-dv it's no longer in beta.

**Comment by igor-dv** [comment] 2018-11-29 08:01
🔥 
I suppose it will be handled soon by our @dependabot-bot . But you can submit a PR 😉

**Comment by heetrew** [comment] 2018-12-12 06:48
If in one project use last versions of storybook and emotion it cases missing styles in storybook UI
<img width="1253" alt="screenshot 2018-12-12 at 09 45 17" src="https://user-images.githubusercontent.com/18642706/49851693-ffc7d780-fdf2-11e8-8f61-7b2719d4e3db.png">

**Comment by ferrybrouwer** [comment] 2018-12-14 13:16
Probably the problem is that `mjs` module is loaded which uses an import statement of @emotion/core. Since it tries to resolve it uses the newer @emotion/core 10 version. Hopefully they fix this in the near future since Emotion 10 has some strong features (such as the css prop/attribute now can be used without the babel plugin which enables to fully compile with only TypeScript)

**Comment by ndelangen** [comment] 2018-12-14 15:01
update on the progress:

I merged the PR into a feature branch that will go live in january.

**Comment by ndelangen** [comment] 2018-12-14 15:01
#4086

**Comment by lifeiscontent** [comment] 2018-12-15 23:17
nice

**Comment by tkh44** [comment] 2019-01-04 20:54
@ndelangen any chance this could be released before that major update? I can help out if needed.

**Comment by tmeasday** [comment] 2019-01-13 03:48
This is merged into the v5 branch which is going into `next` any minute now

**Comment by shilman** [comment] 2019-01-14 06:14
Released here: https://github.com/storybooks/storybook/releases/tag/v5.0.0-alpha.0

**Closed** 2019-01-14 06:18 UTC
Labels: dependencies, merged, question / support
