### ISSUE TITLE
"Error: .sourceMap is an alias for .sourceMaps, cannot use both" on Storybook start, RN 0.56

### ISSUE THREAD

**Issue by todorone** [storybooks/storybook#3936] opened 2018-07-31 10:41 UTC
### Bug or support request summary

The mobile application starts correctly, but the web part throws an error and stays blank. I guess it's somehow related to babel 6 -> 7 transition, but although I tried all workarounds, nothing did help...

### Steps to reproduce

Running `yarn storybook` results in:

```
yarn run v1.9.2
$ storybook start -p 7007
=> Loading custom .babelrc from project directory.
=> Loading custom addons config.
=> Using default webpack setup based on "Create React App".
Scanning folders for symlinks in /Users/fedirushakov/Documents/phyzeek-mobile/node_modules (20ms)

React Native Storybook started on => http://localhost:7007/

webpack built b2e6af571a2cf9d68fed in 4404ms
✖ ｢wdm｣: Hash: b2e6af571a2cf9d68fed
Version: webpack 4.16.3
Time: 4404ms
Built at: 07/31/2018 1:31:37 PM
                   Asset       Size   Chunks             Chunk Names
static/manager.bundle.js   6.04 MiB  manager  [emitted]  manager
              index.html  637 bytes           [emitted]  
Entrypoint manager = static/manager.bundle.js
[./node_modules/@storybook/channel-websocket/dist/index.js] 2.76 KiB {manager} [built]
[./node_modules/@storybook/core-events/index.js] 412 bytes {manager} [built]
[./node_modules/@storybook/react-native/dist/manager/index.js] 511 bytes {manager} [built]
[./node_modules/@storybook/react-native/dist/manager/provider.js] 4.24 KiB {manager} [built]
[./node_modules/@storybook/ui/dist/index.js] 2.38 KiB {manager} [built]
[./node_modules/@storybook/ui/dist/modules/ui/index.js] 1010 bytes {manager} [built]
[./node_modules/babel-runtime/core-js/object/get-prototype-of.js] 104 bytes {manager} [built]
[./node_modules/babel-runtime/helpers/classCallCheck.js] 208 bytes {manager} [built]
[./node_modules/babel-runtime/helpers/createClass.js] 904 bytes {manager} [built]
[./node_modules/babel-runtime/helpers/inherits.js] 1.08 KiB {manager} [built]
[./node_modules/global/window.js] 232 bytes {manager} [built]
[./node_modules/react/index.js] 190 bytes {manager} [built]
[0] multi ./storybook/addons.js ./node_modules/@storybook/react-native/dist/manager/index.js 40 bytes {manager} [built]
[./node_modules/uuid/index.js] 120 bytes {manager} [built]
[./storybook/addons.js] 1.3 KiB {manager} [built] [failed] [1 error]
    + 559 hidden modules

ERROR in ./storybook/addons.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: .sourceMap is an alias for .sourceMaps, cannot use both
    at assertNoDuplicateSourcemap (/Users/fedirushakov/Documents/phyzeek-mobile/node_modules/@babel/core/lib/config/validation/options.js:123:11)
    at validate (/Users/fedirushakov/Documents/phyzeek-mobile/node_modules/@babel/core/lib/config/validation/options.js:68:3)
    at loadPrivatePartialConfig (/Users/fedirushakov/Documents/phyzeek-mobile/node_modules/@babel/core/lib/config/partial.js:38:28)
    at loadFullConfig (/Users/fedirushakov/Documents/phyzeek-mobile/node_modules/@babel/core/lib/config/full.js:43:18)
    at transformSync (/Users/fedirushakov/Documents/phyzeek-mobile/node_modules/@babel/core/lib/transform-sync.js:15:18)
    at Object.transform (/Users/fedirushakov/Documents/phyzeek-mobile/node_modules/@babel/core/lib/transform.js:22:38)
    at transpile (/Users/fedirushakov/Documents/phyzeek-mobile/node_modules/babel-loader/lib/index.js:50:20)
    at /Users/fedirushakov/Documents/phyzeek-mobile/node_modules/babel-loader/lib/fs-cache.js:118:18
    at ReadFileContext.callback (/Users/fedirushakov/Documents/phyzeek-mobile/node_modules/babel-loader/lib/fs-cache.js:31:21)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)
 @ multi ./storybook/addons.js ./node_modules/@storybook/react-native/dist/manager/index.js manager[0]
Child html-webpack-plugin for "index.html":
         Asset      Size  Chunks  Chunk Names
    index.html  1.38 MiB       0  
    Entrypoint undefined = index.html
    [./node_modules/html-webpack-plugin/lib/loader.js!./node_modules/@storybook/core/src/server/index.html.ejs] 926 bytes {0} [built]
    [./node_modules/lodash/lodash.js] 527 KiB {0} [built]
    [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 489 bytes {0} [built]
    [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {0} [built]
ℹ ｢wdm｣: Failed to compile.
```

### Please specify which version of Storybook and optionally any affected addons that you're running

Bug reproduced on both @storybook/react-native@4.0.0-aplha.14 and @storybook/react-native@3.4.8

### Affected platforms 

Mac OS 10.13.6
React Native 0.56

**Comment by wildseansy** [comment] 2018-08-08 19:04
I'm seeing the same 👍

**Comment by no23reason** [comment] 2018-09-13 07:06
This is still an issue, tested on
react-native 0.56
@storybook/react-native 3.4.10

**Comment by Hypnosphi** [comment] 2018-09-13 10:18
Duplicate of https://github.com/storybooks/storybook/issues/4011

**Closed by Hypnosphi** 2018-09-13 10:18 UTC
Labels: app: react-native
