### ISSUE TITLE
Automatically create knobs based on PropTypes

### ISSUE THREAD

**Issue by shilman** [storybooks/storybook#796] opened 2017-04-15 15:19 UTC
<a href="https://github.com/lucasconstantino"><img src="https://avatars1.githubusercontent.com/u/2688512?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [lucasconstantino](https://github.com/lucasconstantino)**
_Wednesday Oct 19, 2016 at 20:23 GMT_
_Originally opened as https://github.com/storybooks/storybook-addon-knobs/issues/63_

----

It would be awesome if this addon could automatically create knobs based on propTypes. [Atellier](https://github.com/scup/atellier) does this kind of work already, but the project's development looks frozen.

Here goes a work in progress project based on Atellier: https://github.com/lucasconstantino/storybook-addon-smart-knobs

**Comment by ndelangen** [comment] 2017-07-07 14:30
Thanks good suggestion, I'll close this as a duplicate of #792.

We definitely want to integrate this into addon-knobs somehow.

**Closed by ndelangen** 2017-07-07 14:30 UTC
Labels: addon: knobs, feature
