### ISSUE TITLE
Error importing scss file

### ISSUE THREAD

**Issue by maxlibin** [storybooks/storybook#708] opened 2017-03-01 10:04 UTC
need help with "You may need an appropriate loader to handle this file type."

in compontent file:
`import "../src/components/Header.scss";`

here is my webpack config:

```
const BASE_CSS_LOADER = "css?sourceMap&-minimize";

webpackConfig.module.loaders.push({
  test: /\.scss$/,
  exclude: null,
  loaders: [
    "style",
    BASE_CSS_LOADER,
    "postcss",
    "sass?sourceMap",
  ],
});
webpackConfig.module.loaders.push({
  test: /\.css$/,
  exclude: null,
  loaders: [
    "style",
    BASE_CSS_LOADER,
    "postcss",
  ],
});
webpackConfig.sassLoader = {
  includePaths: project.paths.client("styles"),
};

// File loaders
/* eslint-disable */
webpackConfig.module.loaders.push(
  { test: /\.woff(\?.*)?$/,  loader: "url?prefix=fonts/&name=[path][name].[ext]&limit=10000&mimetype=application/font-woff" },
  { test: /\.woff2(\?.*)?$/, loader: "url?prefix=fonts/&name=[path][name].[ext]&limit=10000&mimetype=application/font-woff2" },
  { test: /\.otf(\?.*)?$/,   loader: "file?prefix=fonts/&name=[path][name].[ext]&limit=10000&mimetype=font/opentype" },
  { test: /\.ttf(\?.*)?$/,   loader: "url?prefix=fonts/&name=[path][name].[ext]&limit=10000&mimetype=application/octet-stream" },
  { test: /\.eot(\?.*)?$/,   loader: "file?prefix=fonts/&name=[path][name].[ext]" },
  { test: /\.svg(\?.*)?$/,   loader: "url?prefix=fonts/&name=[path][name].[ext]&limit=10000&mimetype=image/svg+xml" },
  { test: /\.(png|jpg)$/,    loader: "url?limit=8192" }
)
/* eslint-enable */

// ------------------------------------
// Finalize Configuration
// ------------------------------------
// when we don't know the public path (we know it only when HMR is enabled [in development]) we
// need to use the extractTextPlugin to fix this issue:
// http://stackoverflow.com/questions/34133808/webpack-ots-parsing-error-loading-fonts/34133809#34133809
if (!__DEV__) {
  debug("Applying ExtractTextPlugin to CSS loaders.");
  webpackConfig.module.loaders.filter((loader) =>
    loader.loaders && loader.loaders.find((name) => /css/.test(name.split("?")[0]))
  ).forEach((loader) => {
    const first = loader.loaders[0];
    const rest = loader.loaders.slice(1);
    loader.loader = ExtractTextPlugin.extract(first, rest.join("!"));
    delete loader.loaders;
  });

  webpackConfig.plugins.push(
    new ExtractTextPlugin("[name].css", {
      allChunks: true,
    })
  );
}

module.exports = webpackConfig;
```

**Comment by tmeasday** [comment] 2017-03-30 01:56
Hi @maxlibin -- have you seen this documentation: https://getstorybook.io/docs/react-storybook/configurations/custom-webpack-config

It sounds like you need to apply the first part of your config to storybook's config, in a similar way to the "Simple Mode" example. You could extract it to a common JS file to do so.

**Comment by maxlibin** [comment] 2017-03-30 10:44
@tmeasday I have this webpack.config.js in .storybook

<img width="281" alt="screen shot 2017-03-30 at 6 43 35 pm" src="https://cloud.githubusercontent.com/assets/1277038/24500657/d72dd54a-1578-11e7-89c3-415af91b791c.png">

**Comment by tmeasday** [comment] 2017-03-31 01:22
@maxlibin -- I tried to reproduce the problem here: https://github.com/tmeasday/storybook-708, but it seems to be working.

Note this is an app created with `create-react-app` so the SCSS doesn't actually work in the main app (no way to modify the webpack config), but the SCSS is working just fine in storybook.

Any ideas about what's different? Maybe you could fork the above and try and reproduce there?

**Comment by gthomas-appfolio** [comment] 2017-06-01 18:10
I'm also seeing issues with the storybook 2->3 upgrade. We use scss and cssmodules (without extract text plugin) and do not use `create-react-app`.    The loaders we specify in `.storybook/webpack.config.js` seem to be ignored, or at least the errors are identical if we have the custom `webpack.config.js` or not.  This approach worked with storybook 2.

Errors:

```ERROR in ./src/components/datemonth/DateMonth.scss
Module parse failed: /Users/gary.thomas/Desktop/react-gears-2/src/components/datemonth/DateMonth.scss Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
| .date_month {
|   display: inline-block;
|   font-family: sans-serif;
 @ ./src/components/datemonth/DateMonth.js 29:17-44
 @ ./src/index.js
 @ ./.storybook/config.js
 @ multi ./~/@storybook/react/dist/server/config/polyfills.js ./~/@storybook/react/dist/server/config/globals.js (webpack)-hot-middleware/client.js?reload=true ./.storybook/config.js
```

webpack.config.js:

```javascript
const autoprefixer = require('autoprefixer');
const path = require('path');
const webpack = require('webpack');

module.exports = {
  plugins: [
    new webpack.LoaderOptionsPlugin({
      options: {
        postcss: [
          autoprefixer({ browsers: ['last 2 versions'] })
        ]
      }
    })
  ],
  module: {
    loaders: [
      {
        test: /\.css$/,
        loader: 'style-loader!css-loader!postcss-loader!sass-loader',
        include: path.resolve(__dirname, '../')
      },
      {
        test: /\.scss$/,
        loader: 'style-loader!css-loader?modules&camelCase&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!postcss-loader!sass-loader',
        include: path.resolve(__dirname, '../')
      }
    ],
  },
};
```

**Comment by tmeasday** [comment] 2017-06-01 23:11
@maxlibin did you ever sort it out? I might close this issue as @gthomas-appfolio's instructions are hopefully the solution for anyone else finding this, but we can reopen it if you haven't been able to solve the problem.

**Closed by tmeasday** 2017-06-01 23:11 UTC
Labels: question / support

**Comment by joscha** [comment] 2017-06-28 16:52
This issue has been fixed in `3.1.7` via https://github.com/storybooks/storybook/pull/1363 - `extract-text-webpack-plugin` can now be used again in a standard storybook build.

**Comment by MohamedHamed83** [comment] 2017-09-15 02:09
I had the same issue and i fix it by adding scss loader to .storybook>webpack.config.js
        {
            test: /\.scss$/,
            exclude: /node_modules/,
            loaders: [{ loader: 'style-loader' },
            { loader: 'css-loader' },
            {
              loader: 'postcss-loader',
              options: {
                postcss: [
                  precss(),
                  autoprefixer(),
                  mqpacker(),
                ],
              },
            },
            { loader: 'sass-loader' }
            ],
        }

**Comment by wangjitai** [comment] 2019-04-16 06:22
> `yarn add -D react-scripts` worked for me

Thanks @nataliepan , I tried almost all methods through research online, only your answer is suitable for me!
