### ISSUE TITLE
@storybook/react uses babel-loader version incompatible with react-scripts

### ISSUE THREAD

**Issue by cfv1984** [storybooks/storybook#5208] opened 2019-01-10 20:54 UTC
**Describe the bug**
```react-scripts``` demands babel-loader 8.0.4 and ```@storybook/react``` demands 8.0.5

**To Reproduce**
1. With CRA 2, create a new react app
2. With sb-cli, add a new storybook
3. Start the CRA React app

**Expected behavior**
Tools should not be mutually incompatible if they are advertised as compatible.

**Comment by aericson** [comment] 2019-01-11 13:59
duplicate of #5183

**Comment by mrmckeb** [comment] 2019-01-20 17:58
Closing as a duplicate of #5183 (thanks @aericson).

I'll comment on that issue, @cfv1984.

**Closed by mrmckeb** 2019-01-20 17:58 UTC
