### ISSUE TITLE
action-logger addon don't show Array<File> options

### ISSUE THREAD

**Issue by bustEXZ** [storybooks/storybook#1945] opened 2017-10-03 13:37 UTC
Deps:  "@storybook/addon-actions": "^3.2.12"

I send in callbacks 2 arrays with type File (acceptedFiles, rejectedFiles).
But logger dont see options (because its File object) and shows them empty.

What can i do, to fix this? (I dont need to convert File type to Object)

Thanks!

**Comment by danielduan** [comment] 2017-10-03 19:52
Anything passed into the addons should be JSON serializable.

I don't believe files work but there might be workarounds.

**Comment by Hypnosphi** [comment] 2017-10-03 21:47
> Anything passed into the addons should be JSON serializable

That's not exactly the truth, otherwise `addon-actions` would break when receiving native DOM events

**Comment by bustEXZ** [comment] 2017-10-04 05:51
![screen02](https://user-images.githubusercontent.com/5757989/31161625-01d2acf2-a8e1-11e7-9fa4-672276471696.png)

I take file list from `event.dataTransfer` and check the types of files to accept or reject, and then call the method `onSelect.call(this, acceptedFiles, rejectedFiles, evt);`

**Comment by Hypnosphi** [comment] 2017-10-04 09:50
Looks like it's fixed with #1887 and released as `3.3.0-alpha.2`. Please try it and tell us if it works

**Comment by bustEXZ** [comment] 2017-10-04 10:24
If i install @storybook/addon-actions@3.3.0-alpha.2 he stop work, and dont create new Tab "ACTION LOGGER" in panel (but witout errors). If i update all for 3.3.0-alpha.2 all don't work and try to redirect me to this page https://storybook.js.org/basics/faq/#why-is-there-no-addons-channel.

Cant resolve this error and check

**Comment by Hypnosphi** [comment] 2017-10-04 10:26
@shilman do you know what happens here?

**Comment by rhalff** [comment] 2017-11-07 16:56
I'm fixing the bug @Hypnosphi reported in[ a comment](https://github.com/storybooks/storybook/pull/1887#pullrequestreview-74315778) on the pull request at the moment.

Also found some other cases which didn't work like logging functions.

@bustEXZ you have a simplified code snippet which would reproduce your case?

**Comment by bustEXZ** [comment] 2017-11-08 08:36
@rhalff 
Hm, i take Array<File> from drop action. I think you can create File object as
`var file = new File([""], "filename.txt", {type: "text/plain", lastModified: new Date()})`.

Add custom option to `file.text = 'test value'`.
When i tested, i saw only `{text: 'test value'}`, without other File object data.

**Comment by shilman** [comment] 2017-11-10 02:55
@bustEXZ @Hypnosphi sorry i missed this mention. Try clearing out your node_modules, it's probably an NPM version issue.

**Comment by bustEXZ** [comment] 2017-11-10 10:03
Test on `3.3.0-alpha.3`.
Now i saw type of File:
![screenshot at 12-06-12](https://user-images.githubusercontent.com/5757989/32653031-6ab1e55a-c617-11e7-9035-dcd7e53c8446.png)

But without default default File options.

**Comment by Hypnosphi** [comment] 2017-11-28 22:10
I think the problem is that those properties are non-enumerable:

```
var file = new File([""], "filename.txt", {type: "text/plain", lastModified: new Date()})
console.log(Object.keys(file)) // logs empty array
```

**Comment by rhalff** [comment] 2017-12-04 13:08
I came to the same conclusion and currently using:
```js
export default function getPropertiesList(value) {
  const keys = Object.getOwnPropertyNames(value);

  // eslint-disable-next-line no-restricted-syntax
  for (const name in value) {
    if (keys.indexOf(name) === -1) {
      keys.push(name);
    }
  }

  return keys;
}
```

It's not perfect though, while console.log only shows the properties: `lastModified`, `lastModifiedDate`, `name`, `size`, `type` and `webkitRelativePath` and does not show the `slice` function.

I'm not sure how chrome / firefox determine what to log, if I knew I could perhaps mimic that behavior.

**Comment by bustEXZ** [comment] 2017-12-04 13:49
Maybe like this?
```js
function getPropertiesList(value) {
  const keys = Object.getOwnPropertyNames(value);
  const objKeys = Object.getOwnPropertyNames(Array.prototype);

  for (const name in value) {
    if (keys.indexOf(name) === -1 && objKeys.indexOf(name) === -1) {
      keys.push(name);
    }
  }

  return keys;
}

var file = new File([""], "filename.txt", {type: "text/plain", lastModified: new Date()})

file.custom = 'Hello';

console.log(getPropertiesList(file));

// ["custom", "name", "lastModified", "lastModifiedDate", "webkitRelativePath", "size", "type"]
```

**Comment by Hypnosphi** [comment] 2017-12-04 14:39
> and does not show the `slice` function

That's OK in my view. It doesn't present any data

**Comment by Hypnosphi** [comment] 2017-12-04 14:43
> const objKeys = Object.getOwnPropertyNames(Array.prototype);

Why only Array?

**Comment by bustEXZ** [comment] 2017-12-04 14:52
Static methods. Its just example. We cant use File, because method delete our properties.

**Comment by rhalff** [comment] 2017-12-04 17:07
I'm now trying this:
```js
export default function getPropertiesList(value) {
  const keys = Object.getOwnPropertyNames(value);

  // eslint-disable-next-line no-restricted-syntax
  for (const name in value) {
    if (keys.indexOf(name) === -1 && !(typeof value[name] === 'function' && !value.hasOwnProperty(name))) {
      keys.push(name);
    }
  }

  return keys;
}
```
Which ignores any functions not being an own property.

**Comment by Hypnosphi** [comment] 2017-12-05 00:40
@rhalff @bustEXZ  What's wrong with the approach from #2401? Looks like it logs exactly what's needed

**Comment by bustEXZ** [comment] 2017-12-05 05:20
Looks great! Thanks

**Comment by rhalff** [comment] 2017-12-05 23:45
@Hypnosphi I've created a new pull request (#2438) which also incorporates your changes and fixes the bug reported in [your comment](https://github.com/storybooks/storybook/pull/1887#pullrequestreview-74315778). I refactored the code a bit and have added tests.

[Live example](https://storybook-dev-rhalff.c9users.io/?selectedKind=Addon%20Actions&selectedStory=All%20types&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybook%2Factions%2Factions-panel)

**Comment by Hypnosphi** [comment] 2018-01-27 13:43
Merge and released about a month ago

**Closed by Hypnosphi** 2018-01-27 13:43 UTC
Labels: addon: actions, feature request, in progress
