### ISSUE TITLE
5.1.x scrollbars do not scroll and exhibit strange behavior with external mice

### ISSUE THREAD

**Issue by domyen** [storybooks/storybook#6753] opened 2019-05-09 08:55 UTC
**Describe the bug**
- Scrolling does not scroll 
- Scrollbars remain visible when using an external mouse (i.e., in a desktop setup)

**To Reproduce**
1. Go to Storybook `next` branch. View the [default story](https://next--storybooks-official.netlify.com/?path=/story/ui-panel--default) or the [about page](https://next--storybooks-official.netlify.com/?path=/settings/about) 
2. See that scroll bars render strangely on in the default Storybook UI. And notice you cannot scroll on the about page.

**Expected behavior**
- I expect the scrollbar to not have artifacts
- I expect the scrollbar to scroll 

**Screenshots**
Image of broken scrollbar:
![image](https://user-images.githubusercontent.com/263385/57440151-0e1f0000-727a-11e9-965c-56a602f2d72f.png)

Video recording of scrolling not working on about page:
![Screen Recording 2019-05-09 at 04 47 PM](https://user-images.githubusercontent.com/263385/57440281-4f171480-727a-11e9-9be0-6971f18ee15f.gif)

**System:**
 - OS: Mac OSX Mojave
 - Device: Macbook Pro 2018
 - Mouse: Microsoft Intellimouse 
 - Browser: Chrome
 - Version: 5.1.X

**Additional context**
This regression was introduced in 5.1.x. I've seen the visible scrollbars happen when simplebar is broken -- perhaps the update to `simplebar-react 1.0-alpha` could have caused this? This behavior does not exist in my 5.0.x Storybooks.

**Comment by ymcnicoll** [comment] 2019-05-09 12:02
This behavior also shows on Windows machines. 

This started to happen when I upgraded from alpha.31 to alpha.40

**Comment by Grsmto** [comment] 2019-05-10 11:42
Hi,
SimpleBar maintainer here, I'll look into this, I think this is an upstream bug. I think I know the cause but I'm still unsure on why this is happening as the usage in Storybook seems quite straightforward.

>Video recording of scrolling not working on about page:

After debugging quickly this, it seems like it's unrelated to SimpleBar and it's a `z-index` issue. An element on top is blocking any mouse interaction.

**Comment by Grsmto** [comment] 2019-05-10 12:04
So after investigation, this is because SimpleBar V4 has breaking changes that have been taken into account in Storybook. Actually it's not due to the breaking changes exactly, it's just that you have hardcoded the core CSS of SimpleBar [in this file](https://github.com/storybooks/storybook/blob/bf76760d333436fde7b408fe2eb63e03a2822133/lib/components/src/ScrollArea/ScrollAreaStyles.tsx) so the CSS in there is outdated!

You should just have to update the CSS to the latest SimpleBar version and that should work again fine.

Thanks for using SimpleBar, please don't hesitate to file an issue in our repo if you encounter anything!

**Comment by shilman** [comment] 2019-05-10 15:19
Thanks so much @Grsmto ! Much appreciated!

**Comment by artyomtrityak** [comment] 2019-05-10 16:01
Having similar issue on Mac 5.1-beta0

![Storybook (1)](https://user-images.githubusercontent.com/957406/57540735-3a7e5f00-7302-11e9-878a-f7c32bc0fda0.png)
![Storybook](https://user-images.githubusercontent.com/957406/57540737-3a7e5f00-7302-11e9-890b-733ab9b4f34e.png)

**Comment by domyen** [comment] 2019-05-11 05:15
Thanks @Grsmto 🙏. I totally forgot about that hack 😅, will have to figure out why we ended up doing that - a setting-specific reason I'm sure.

**Comment by domyen** [comment] 2019-05-14 03:05
Tried to debug this using @Grsmto's suggestion to update the CSS; that ended up causing different layout bugs. @ndelangen can you lend a hand here?

**Comment by ndelangen** [comment] 2019-05-14 10:06
I'm on it

**Comment by ndelangen** [comment] 2019-05-14 10:27
@artyomtrityak are you on our discord by any chance?
https://discord.gg/sMFvFsG

**Comment by Grsmto** [comment] 2019-05-14 10:58
Make sure to apply the right css properties on the host (element on which you apply SimpleBar). As it doesn't do it for you anymore (that's a breaking change on V4).
So for ex for the left sidebar it won't work unless you define `max-height: 100%;` on the element.

**Comment by Grsmto** [comment] 2019-05-14 11:09
If you guys struggle let me know and I could work on a PR!
I had a quick look and was able to fix it with the tips I provided in my previous comment.

**Comment by ndelangen** [comment] 2019-05-14 13:46
@Grsmto I'm running into a problem where (at least on my machine, I can't scroll all the way to the right, when scrolling on both axis:

[![](http://img.youtube.com/vi/kp-om1IryaQ/0.jpg)](http://www.youtube.com/watch?v=kp-om1IryaQ "")

I can reproduce this on http://grsmto.github.io/simplebar/examples too

**Comment by Grsmto** [comment] 2019-05-14 14:34
@ndelangen what we can see in the video is actually the "normal" behaviour. If you check when you're testing the "Both axis + padding native" it's having the exact same behaviour.
If you apply a padding inside an `overflow: auto` element, the browser does not take that padding into account for the `padding-right`. I'm not sure exactly why but that's the native CSS behaviour!

If you want to fix this "issue" you can just apply the padding to an inner element instead of applying it on your SimpleBar host element.

**Comment by ndelangen** [comment] 2019-05-14 14:48
browsers suck

**Comment by ndelangen** [comment] 2019-05-14 17:18
@domyen or anyone else, are you able to confirm the issue is resolved in my PR?
https://github.com/storybooks/storybook/pull/6785

**Comment by artyomtrityak** [comment] 2019-05-15 17:33
@ndelangen yes i am :)

**Comment by domyen** [comment] 2019-05-16 01:24
Added theming support back in #6794. can @ndelangen or anyone confirm 🙏

**Comment by shilman** [comment] 2019-05-16 06:08
w00t!! I just released https://github.com/storybooks/storybook/releases/tag/v5.1.0-beta.1 containing PR #6794 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Closed by shilman** 2019-05-16 06:08 UTC
Labels: bug, high priority, ui
