### ISSUE TITLE
【Help Wanted】Failed to mount Vue component error

### ISSUE THREAD

**Issue by andoshin11** [storybooks/storybook#4644] opened 2018-10-30 14:35 UTC
### Bug or support request summary
Custom components registered to stories are not mounted when running storyshots.

```
console.error node_modules/vue/dist/vue.esm.js 591
  [Vue warn]: Failed to mount component: template or render function not defined.

  found in

  ---> <Pager>
             <Root>
```

I pretty much followed every steps displayed on the example.

Package versions:
- "@storybook/vue": "4.0.0"
- "@storybook/addon-storyshots": "4.0.0"
- "jest-vue-preprocessor": "^1.4.0"
- "jest-serializer-vue": "^2.0.2"
- "typescript": "^3.1.3"
- "vue-loader": "^15.4.2"
- "vue": "^2.5.17"

```
// package.json
...
{
  "scripts": {
    "snapshot": "jest --config=jest.config.snapshot.js",
    ...
  }
}
```

```
// jest.config.snapshot.js
module.exports = {
  moduleFileExtensions: ['vue', 'js', 'ts', 'json'],
  moduleDirectories: ['node_modules'],
  transform: {
    '^.+\\.js$': 'ts-jest',
    '^.+\\.ts$': 'ts-jest',
    '.*\\.(vue)$': '<rootDir>/node_modules/jest-vue-preprocessor'
  },
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
    '[^/]vue$': 'vue/dist/vue.esm.js',
    '^@storybook/(.*)$': '<rootDir>/node_modules/@storybook/$1'
  },
  snapshotSerializers: ['jest-serializer-vue'],
  testMatch: ['<rootDir>/test/snapshot/*.js'],
  verbose: true,
  setupFiles: ['<rootDir>/.jest/register-context.js'],
  transformIgnorePatterns: [
    './node_modules/(?!vue)',
    './node_modules/@storybook'
  ],
  globals: {
    'ts-jest': {
      babelConfig: '.babelrc'
    }
  }
}
```

```
// .jest/register-context.js
import registerRequireContextHook from 'babel-plugin-require-context-hook/register'
registerRequireContextHook()
```

```
// Pager.vue
<template>
  <div class="Pager">
    <button
      :disabled="internalCurrentPage === 1"
      class="Pager__ArrowButton"
      @click="onClickPrev"
    >←</button>
    <button
      :disabled="internalCurrentPage === maxPage"
      class="Pager__ArrowButton"
      @click="onClickNext"
    >→</button>
  </div>
</template>

<script lang="ts">
import Vue from 'vue'

interface IData {
  internalCurrentPage: number
}

export default Vue.extend({
  props: {
    currentPage: {
      type: Number,
      default: 1
    },
    size: {
      type: Number,
      default: 1
    },
    total: {
      type: Number,
      default: 20
    }
  },
  data(): IData {
    return {
      internalCurrentPage: 1
    }
  },
  computed: {
    maxPage(): number {
      return Math.ceil(this.total / this.size)
    }
  },
  watch: {
    currentPage: {
      immediate: true,
      handler(val) {
        this.internalCurrentPage = val
      }
    }
  },
  methods: {
    onClickNumButton(pageNum: number) {
      this.internalCurrentPage = pageNum
      this.$emit('change', this.internalCurrentPage)
    },
    onClickPrev() {
      this.internalCurrentPage -= 1
      this.$emit('change', this.internalCurrentPage)
    },
    onClickNext() {
      this.internalCurrentPage += 1
      this.$emit('change', this.internalCurrentPage)
    }
  }
})
</script>

<style scoped>
...
</style>
```

```
// Pager.story.ts
import { storiesOf } from '@storybook/vue'

import Pager from './Pager.vue'

storiesOf('components/Base/Pager', module).add('Default', () => ({
  components: { Pager },
  data() {
    return {
      currentPage: 1
    }
  },
  template: `
    <div class="Storybook">
      <div class="StorybookSection">
        <div class="StorybookSection__Header">Pager</div>
        <div class="StorybookSection__Body dark">
          <div class="wrapper" style="width: 100%">
            <div style="color: #fff;margin-bottom: 16px;font-size: 18px;font-weight: bold;">Current Page: {{ currentPage }}</div>
            <Pager :currentPage="currentPage" :size="1" :total="10" @change="num => currentPage = num" />
          </div>
        </div>
      </div>
    </div>
  `
}))
```

### Storybook
Yes, everything is working on Storybook.

![2018-10-30 23 34 50](https://user-images.githubusercontent.com/8381075/47725765-7e7e1080-dc9c-11e8-9f57-a5c0b8d2273f.png)

It breaks only when running on Jest.

Looking forward any advice could fix my issue.Thanks

**Comment by igor-dv** [comment] 2018-10-31 16:45
I can't point to something specific in your setup. Having a reproduction will be much helpful

**Comment by andoshin11** [comment] 2018-10-31 22:16
I've pushed a dedicated branch to reproduce the problem in my repo.
https://github.com/andoshin11/spa-playground/tree/fix/storyshots-error

Running `$ yarn run snapshot` will give you the error shown above.

**Comment by igor-dv** [comment] 2018-11-01 17:48
I've tried to figure it out what's going on, but without progress. Will try to debug a bit later.

**Comment by andoshin11** [comment] 2018-11-02 14:07
Thanks a lot for your kindness, Igor

**Comment by igor-dv** [comment] 2018-11-13 16:39
Actually, we are mocking `vue` to use `vue.common` inside the storyshots. So probably ☝️ is not 100% accurate

**Comment by igor-dv** [comment] 2018-11-14 13:07
Got it working with a bit different approach. 

First of all, I can confirm that the problem is with vue/jest/typescript . So probably there is a different solution by changing something in `tsconfig`.

Currently, the `vue-jest-preprocessor` is [using](https://github.com/vire/jest-vue-preprocessor/blob/master/index.js#L65) `typescript` compiler when the `lang="ts"` is defined in the <script> of the vue component. If we are moving to babel, the problem disappears. For that, we need to upgrade babel to babel 7 and use `@babel/plugin-transform-typescript` (you had partialy babel 7 installed)

You need to have these devDeps in package.json:
```json
"@babel/core": "^7.1.5",
"@babel/plugin-transform-typescript": "^7.1.0",
"@babel/preset-env": "^7.1.5",
"babel-core": "^7.0.0-bridge.0",
"babel-jest": "^23.6.0",
```

Notice that `babel-preset-env` is removed in favor of `@babel/preset-env`.

The root .babelrc should be like this now:
```json
{
  "env": {
    "test": {
      "presets": [
        "@babel/preset-env",
        "babel-preset-vue"
      ],
      "plugins": [
        "@babel/plugin-transform-typescript",
        "require-context-hook"
      ]
    }
  }
}
```

Now, in order to use `vue` files with **babel** inspite the `lang="ts"`, we need to copy the preprocessor and a bit change it (maybe there are already other preprocessors that are doing this, but I didn't search)

Put it in `.jest/babel-vue-jest.js`: 

```js
// copy paste from jest-vue-preprocessor

const fs = require('fs');
const path = require('path');
const vueCompiler = require('vue-template-compiler');
const vueNextCompiler = require('vue-template-es2015-compiler');
const transforms = require('jest-vue-preprocessor/transforms');

const extractHTML = (template, templatePath) => {
    let resultHTML = '';

    if (template.content === '' && template.src !== '') {
        template.content = fs.readFileSync(
            path.resolve(path.dirname(templatePath), template.src),
            'utf8'
        );
    }

    if (!template.lang || template.lang === 'resultHTML') {
        resultHTML = template.content;
    } else if (template.lang === 'pug') {
        resultHTML = require('pug').compile(template.content)();
    } else {
        throw templatePath + ': unknown <template lang="' + template.lang + '">';
    }

    return resultHTML;
};

const extractScriptContent = (script, scriptPath) => {
    if (!script) {
        throw 'No script available to transform';
    }
    if (script.content === '' && script.src !== '') {
        script.content = fs.readFileSync(path.resolve(path.dirname(scriptPath), script.src), 'utf8');
    }
    return script.content;
};

const stringifyRender = render => vueNextCompiler('function render () {' + render + '}');

const stringifyStaticRender = staticRenderFns =>
    `[${staticRenderFns.map(stringifyRender).join(',')}]`;

module.exports = {
    process(src, filePath) {
        // code copied from https://github.com/locoslab/vue-typescript-jest/blob/master/preprocessor.js
        // LICENSE MIT
        // @author https://github.com/locobert
        // heavily based on vueify (Copyright (c) 2014-2016 Evan You)

        const { script, template } = vueCompiler.parseComponent(src, { pad: false });

        let render;
        let staticRenderFns;
        if (template) {
            const HTML = extractHTML(template, filePath);
            const res = HTML && vueCompiler.compile(HTML);
            render = stringifyRender(res.render);
            staticRenderFns = stringifyStaticRender(res.staticRenderFns);
        }

        let scriptContent = { code: '' };
        scriptContent = extractScriptContent(script, filePath);

        const transformKey = 'babel'; // here is the changed line. We always use babel.
        return transforms[transformKey](scriptContent, filePath, render, staticRenderFns);
    },
};
```

The last thing, we need to change your `jest.config.snapthost.json` to:

```js
module.exports = {
  moduleFileExtensions: ['vue', 'js', 'ts', 'json'],
  moduleDirectories: ['node_modules'],
  transform: {
    '^.+\\.(js|ts)$': '<rootDir>/node_modules/babel-jest', // <- here we use both ts and js with babel
    '.*\\.(vue)$': '<rootDir>/.jest/babel-vue-jest' // <- here we are using our preprocessor for vue
  },
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
    '^@storybook/(.*)$': '<rootDir>/node_modules/@storybook/$1'
  },
  snapshotSerializers: ['jest-serializer-vue'],
  testMatch: ['<rootDir>/test/snapshot/*.js'],
  verbose: true,
  setupFiles: ['<rootDir>/.jest/register-context.js']
}
```

LMK if it works for you.

**Comment by andoshin11** [comment] 2018-11-17 02:54
Yes! It finally worked for me!
Appreciate your help:)

Here's the tweak I have done 👇 

https://github.com/andoshin11/spa-playground/pull/10

**Closed** 2018-11-17 07:48 UTC
Labels: addon: storyshots, app: vue, question / support
